### ISSUE TITLE
make "empty buffer" key configurable

### ISSUE THREAD

**Issue by mwildehahn** [mhinz/vim-startify#10]
I use command-t and muscle memory is set to open vim, hit the leader key, and go to the file I'm looking for. I think startify is awesome, but it would be great if I could set "leader" as my empty buffer key so I don't have to hit "e" each time when I'm planning on using command-t which is 90% of the time.

**Comment by AmmarCodes** [comment]
In case someone found this issue, the setting to hide new buffer and quit list items is [now](https://github.com/mhinz/vim-startify/blob/master/doc/startify.txt#L445):

```vim
let g:startify_enable_special = 0
```

**Comment by andys8** [comment]
The option was removed:

```
let g:startify_empty_buffer_key = ''
```

And this otptional will only hide it, but it will still work:

```
let g:startify_enable_special = 0
```

I've the issue too, that I'm accidentally hitting `e`. How can it be disabled? @mhinz

**Comment by andys8** [comment]
It looks like a different binding can overwrite the default behavior. Can be done like this:

```
autocmd User Startified nmap <buffer> e <leader>e
```
