### ISSUE TITLE
Can't open files with spaces in the path

### ISSUE THREAD

**Issue by edubxb** [mhinz/vim-startify#102]
When I try to open a file with spaces in the path with startify Vim shows this message:

`E172: Only one file name allowed`

**Comment by gauteh** [comment]
I am getting this for files set in bookmarks. Names with spaces does not work.

**Comment by mhinz** [comment]
@gauteh 

Please show your `g:startify_bookmarks` and what file is actually opened in the end.

I did a quick test by using `let g:startify_bookmarks = ['/tmp/foo  bar']` and it worked as expected.

**Comment by gauteh** [comment]
I am automatically adding all lines from a file, like this:
```
let g:startify_bookmarks = []
"       \ '~/.vim/vimrc',
"       \ ]

for line in readfile (expand('~/.vim/bundle/FavEx/favlist'))
  if line !~ '\"' && line != ""
    call add (g:startify_bookmarks, line)
  endif
endfor
```

Maybe it's the `expand()` in that command that splits the file.

**Comment by mhinz** [comment]
What's the output of `:echo g:startify_bookmarks`?

**Comment by gauteh** [comment]
Actually, after updating the plugin it works :blush:. Sorry for wasting
your time.

**Comment by mhinz** [comment]
Hah, no problem. :-)
