### ISSUE TITLE
something about startify_custom_header

### ISSUE THREAD

**Issue by axiaoxin** [mhinz/vim-startify#108]
It's nice, I wanna kown how to display the animal pattern which in the screenshot, thanks, and I don's think it is cowsay in startify_custom_header.

and how to generate to ascii picture which like the hardcoded example 'vim 7.3' , thanks a lot.

**Comment by tolinwei** [comment]
@mhinz Hi, after adding this line to my vimrc, the cowsay is still not showing
`let g:startify_custom_header =
        \ map(split(system('tips | cowsay -f apt'), '\n'), '"   ". v:val') + ['']`

Do I need to do some extra configuration around this repo? https://github.com/mhinz/dotfiles/blob/master/bin/tips

**Comment by mhinz** [comment]
There's a rogue `\`. :-) It's just needed if you break the assignment up into multiple lines.
