### ISSUE TITLE
Integration with vim-session / use `OpenSession` if it exists

### ISSUE THREAD

**Issue by blueyed** [mhinz/vim-startify#131]
It would be useful if startify would call `:OpenSession` (from https://github.com/xolox/vim-session), and then stop handling of sessions from there (e.g. do not handle persistence etc).

I like the list of sessions in Startify, but would like to keep using vim-session for them.

**Comment by mhinz** [comment]
I stand by the above comment. Due to the combination of lack of time, not using that plugin and thinking it wouldn't be used by many people.. I won't implement it myself, but I'd certainly appreciate any patches.

 So I close it for the time being. Feel free to reopen!

**Comment by wanderer2** [comment]
Hi @mhinz! I just wanted to add myself to the list of users who would appreciate vim-startify playing well with vim-session. Thanks for making vim-startify and making it available to all!

**Comment by mhinz** [comment]
@wanderer2 Hi!

Same questions as before: What feature do you miss? Maybe it's something all Startify users could profit from? (I hope it's understandable that I'm a bit reluctant to add support for third-party code that I don't use myself.)
