### ISSUE TITLE
quickfix windows isn't saved properly withing session

### ISSUE THREAD

**Issue by sergey-vlasov** [mhinz/vim-startify#134]
The window layout is restored, but it's missing these crustal settings:
```
setlocal buftype=quickfix
setlocal syntax=qf
setlocal filetype=qf
```
so an empty no name buffer created instead.

Is it possible to exclude quickfix window from being saved? Based on buftype for example. Or save it but with buftype/syntax/filetype settings?

**Comment by mhinz** [comment]
Please reopen, if this is still an issue.
