### ISSUE TITLE
Session.vim Autoload from Bookmarks Broken

### ISSUE THREAD

**Issue by amadeus** [mhinz/vim-startify#144]
It seems in the latest commit, if I select a bookmarked folder, it doesn't autoload my Session.vim file in that folder.

If I go back a commit, everything works as expected.

![example1](https://dl.dropboxusercontent.com/s/0un2sb1krugyel5/Scratch_2015-01-13_12-44-44.png?dl=0)

I pressed `enter` to load that bookmark, and I get:
![example2](https://dl.dropboxusercontent.com/s/det0r66y4a2sx3t/app.kiip.me_2015-01-13_12-45-34.png?dl=0)

If I call `:source Session.vim` then I get the expected result:
![example3](https://dl.dropboxusercontent.com/s/1e24qkzfg49hzwd/Campaign.Settings.js_2015-01-13_12-46-10.png?dl=0)

**Comment by amadeus** [comment]
P.S. I tried setting `let g:startify_session_autoload = 1` in my .vimrc and it still did not work as expected

**Comment by mhinz** [comment]
*cough*

Sorry for this regression.

**Comment by amadeus** [comment]
No problemo. Fix works great, thanks!
