### ISSUE TITLE
Error on Windows without `shellslash`

### ISSUE THREAD

**Issue by salviati6** [mhinz/vim-startify#146]
Environment: Windows 7 SP1 64-bit, VIM 7.4.589 64-bit
Related issues: #25, #52
Symptom: the following error shows up at VIM startup with `vim-startify` default settings (nothing other than `Plugin 'mhinz/vim-startify'` in my `.vimrc`):

> Error detected while processing function startify#insane_in_the_membrane..\<SNR\>64_show_dir..\<SNR\>64_display_by_path..\<SNR\>64_filter_oldfiles:
> line   20:
> E867: (NFA) Unknown operator '\zh'

It seems the error is from the `dir` list while `vim-startify` is loading files from my `%PROFILE%` path: `C:\Users\zhang`. With `shellslash` set, the path becomes `C:/Users/zhang` and everything works fine. However, `shellslash` is a global option and some other plugins have difficulties with this option on.

**Comment by mhinz** [comment]
This is a simple workaround but should do the trick.

Please try `git pull && git checkout issue146`.

**Comment by salviati6** [comment]
I am sorry to report that the error persists after applying this fix... the only thing changed is the line number in the error information:

> Error detected while processing function startify#insane_in_the_membrane..<SNR>64_show_dir..<SNR>64_display_by_path..<SNR>64_filter_oldfiles:
> line 25:
> E867: (NFA) Unknown operator '\zh'

I confirm that my local `autoload/startify.vim` has been successfully patched and I have restarted my VIM after the patch.

**Comment by salviati6** [comment]
I looked into the code and found that the problem is yielded by `match()` when a Windows-style (backslash) path is provided as the matching pattern. Simply changing [`autoload/startify.vim:423` (master branch)](https://github.com/mhinz/vim-startify/blob/b184b92e963dd1d8504c451f9226f56bf8fbacfa/autoload/startify.vim#L423) to
```viml
    if match(absolute_path, escape(a:path_prefix, '\'))
```
solves the problem.

**Comment by Oberon00** [comment]
What if the `path_prefix` contains `.` or other characters with special meaning? These should probably escaped too; or better: prefix the prefix with [`\V` (very no magic)](http://vimdoc.sourceforge.net/htmldoc/pattern.html#/\\V) and escape only `\`.

**Comment by salviati6** [comment]
You are right @Oberon00! I forgot that there are other regex metacharacters that are legal in a file name. Since we are simply performing literal substring search here, the following solution is more appropriate:
```viml
    if match(absolute_path, '\V' . escape(a:path_prefix, '\'))
```

**Comment by mhinz** [comment]
I was actually thinking of verbatim matching, but not at escaping backslashes before that. Good idea!

**Comment by salviati6** [comment]
I confirm that the new fix works on Windows both with and without `shellslash`. Thanks!

Sorry for my late report because I don't have a Windows environment for test on weekends.

**Comment by mhinz** [comment]
> Sorry for my late report because I don't have a Windows environment for test on weekends.

I don't have a Windows environment neither, thus I have to pester other people to try out patches for it.. :-)

> I confirm that the new fix works on Windows both with and without shellslash. Thanks!

Thanks for reporting this!
