### ISSUE TITLE
startify does not autostart in terminal vim anymore

### ISSUE THREAD

**Issue by 0ax1** [mhinz/vim-startify#147]
Hey,

I've been using startify for quite a while now and it always worked perfectly.
Curiously since a few days startify refuses to start automatically in terminal vim
but continuous to do that in MacVim. I haven't changed any settings regarding startify recently. 
Any hint what could be the reason?

**Comment by mhinz** [comment]
Hi,

How do you start Vim and what terminal emulator are you using?

**Comment by 0ax1** [comment]
I'm using xterm-256color in Iterm.

I start vim this way:
vi: aliased to stty -ixon; reattach-to-user-namespace -l
/Applications/MacVim.app/Contents/MacOS/Vim

So the binary from macvim is used. stty -ixon; is to make c-s c-q
available for custom mappings. reattach-to-user-namespace is for
pbpaste and pbcopy under tmux.

**Comment by mhinz** [comment]
What's the output of `:echo v:progname`?

**Comment by 0ax1** [comment]
-Vim

**Comment by mhinz** [comment]
Really "-Vim"? The exact spelling is important, since startify checks v:progname against this regexp: `^[gmnq]\=vim\=x\=\%[\.exe]$`.

**Comment by 0ax1** [comment]
Yes, that's the exact output (with big V).

**Comment by mhinz** [comment]
Guess I'll have to alter the regexp then, but now I'm curious.. what's the output of `:echo v:progname` in MacVim?

**Comment by 0ax1** [comment]
...
it's: Vim (same but without the hyphen)

**Comment by mhinz** [comment]
The latest commit should make it working.

**Comment by 0ax1** [comment]
It does! Thanks a lot, also for this awesome plugin!

**Comment by mhinz** [comment]
I'm glad you like it! And thanks for reporting this issue.
