### ISSUE TITLE
Escape path with "~"

### ISSUE THREAD

**Issue by sergey-vlasov** [mhinz/vim-startify#152]
When I run vim in directories which names contain tilde I get:
```
Error detected while processing function <SNR>43_PlugPost..startify#insane_in_the_membrane..<SNR>144_show_dir.
.<SNR>144_display_by_path..<SNR>144_filter_oldfiles:
line   20:
E33: No previous substitute regular expression
```

For example
```
mkdir test\~
cd test\~
gvim
```

**Comment by mhinz** [comment]
Hmm, your example works for me.

By the way, are you using the latest version? Because [line 20](https://github.com/mhinz/vim-startify/blob/master/autoload/startify.vim#L42) in master shouldn't produce any `E33` errors.

**Comment by sergey-vlasov** [comment]
Sorry, I was on old version :)

**Comment by mhinz** [comment]
Hah, no problem. :)
