### ISSUE TITLE
Vim-Startify and pterosaur don't work together

### ISSUE THREAD

**Issue by michaelmrose** [mhinz/vim-startify#153]
Pterosaur, a firefox plugin, runs an embedded vim instance to give you vim like editing in any text field.  Unfortunately with vim-startify this embedded vim ends up with the contents of its buffer being the startify startup screen.  I'm not sure how this could be avoided.

**Comment by mhinz** [comment]
I'm neither a user of Firefox nor Pterosaur, but I will look into it.

**Comment by mhinz** [comment]
Timeout. :) Please reopen, if you think it's still a problem.
