### ISSUE TITLE
Error detected while processing function <SNR>15_genesis...startify#insane in the membrane

### ISSUE THREAD

**Issue by Fruglemonkey** [mhinz/vim-startify#154]
Getting what I think is a viminfo-related error.

```
Error detected while processing function <SNR>15_genesis..startify#insane_in_the_membrane..<SNR>73_show_files..<SNR>73_display_by_path..<SNR>73_filter_oldfile..<SNR>73_is_in_skiplist:
line    2:
E33: No previous substitute regular expression
```

If I delete the viminfo file, the first time I run vim I just get a warning 
```
startify: Can't read viminfo file.  Read :help startify-faq-02
```
But then running vim a second time will bring up the first error.

I am running the latest master version.

Any advice?

**Comment by Fruglemonkey** [comment]
I don't get that error if I go down to version 1.6, and in version 1.7 I get the following errors:
![image](https://cloud.githubusercontent.com/assets/7358629/7151203/a0912866-e37a-11e4-88a6-b3e7bf1640a7.png)

**Comment by mhinz** [comment]
Wow, this really shouldn't happen. But the errors are bit weird somehow..

What startify options have you set?

**Comment by Fruglemonkey** [comment]
This is the relevant parts of my .vimrc:
![image](https://cloud.githubusercontent.com/assets/7358629/7173743/3275bd2a-e450-11e4-9149-f7b2a04126c1.png)

I get this error now in 1.8 release.

![image](https://cloud.githubusercontent.com/assets/7358629/7173730/ff34875c-e44f-11e4-97b1-e837f61966f2.png)

I think it also has something to do with my viminfo file, or how my system handles paths, because if I remove all startify options and just load the plugin, I still get errors.

**Comment by Fruglemonkey** [comment]
I'm thinking it's something to do with my system at the moment, because the same .vimrc on my laptop works fine.

**Comment by mhinz** [comment]
Please use the latest master. Release 1.8 is over a year old.

**Comment by Fruglemonkey** [comment]
Running vim 7.4.683 on Arch Linux.

When I use the master version, this is the error output:

![image](https://cloud.githubusercontent.com/assets/7358629/7221856/61a13f44-e751-11e4-9588-b3c991f47919.png)

This is with an empty vimrc, with vim-startify being the only plugin.

I'll check my laptop later today, but it should be running 7.4.683 as well on Ubuntu Linux.

**Comment by mhinz** [comment]
Okay, the error on the last line can easily reproduced via `:echo 'foo' =~ '~'` and assuming you have no Startify options set, the default skiplist is used:

```vim
let s:skiplist = get(g:, 'startify_skiplist', [
      \ 'COMMIT_EDITMSG',
      \ $VIMRUNTIME .'/doc',
      \ 'bundle/.*/doc',
      \ ])
```

Does `:echo $VIMRUNTIME` contains a `~` by any chance?

**Comment by Fruglemonkey** [comment]
Yep, my $VIMRUNTIME is "~/share/vim/vim74". I built vim locally on this
machine as I have no sudo access.

**Comment by mhinz** [comment]
Aha, then we found the culprit! The latest commit should solve that problem.

**Comment by Fruglemonkey** [comment]
That's fixed it. Thanks for being so responsive! Closing.
