### ISSUE TITLE
Including 'dir' in startify_list_order causes error

### ISSUE THREAD

**Issue by protist** [mhinz/vim-startify#157]
I'm getting the following error when I start vim.

    Error detected while processing function startify#insane_in_the_membrane..<SNR>42_show_dir:
    line   14:
    E128: Function name must start with a capital or "s:": l:compare(x, y)

This occurs with the following in `~/.vimrc`

    let g:startify_list_order = ['files', 'dir', 'bookmarks', 'sessions']

If I remove the `'dir'` item, it starts fine. I attempted deleting all other lines in `~/.vimrc`, but I still encountered the error. I have a few other plugins installed.

Also, I get the following message when I start, but I'm not sure if it's relevant: `No matching autocommands`.

**Comment by mhinz** [comment]
Please update the plugin. `l:compare()` was removed over a year ago.

**Comment by protist** [comment]
Oh, yes, that works. I had downloaded the latest "release", which was marked 1.8. This fixes both problems. Apologies for the noise.

Having said that, would you be tagging versions in the future? I'm just wondering what to follow and install. I can see a rapid spate of releases, then non-release commits for a while. Thanks in advance.

**Comment by mhinz** [comment]
I have to admit, that I forgot that I even used tags for this project in the beginning. I realized that versions are simply not needed for VimL plugins.

Thanks for pointing that out, I'll also remove the version comments from the files.

The master branch should be considered stable nowadays.

**Comment by protist** [comment]
Okay, that sounds fine. Thanks for that.

(Also, just out of curiosity, why do you think that versions are not needed for VimL plugins? I appreciate that the master is stable, but I would've thought that versions might still be useful?)

**Comment by mhinz** [comment]
All functionality I ever planned to add, is added already. Occasional pull requests/issues are mostly bugfixes and doc changes that simply wouldn't warrant a new __release__, but are changes every user should receive immediately.

It's simply too small-scale for proper versioning/releasing efforts.

**Comment by protist** [comment]
Okay, that makes a lot of sense. Thanks for the information.
