### ISSUE TITLE
Unable to load session

### ISSUE THREAD

**Issue by ScriptorNY** [mhinz/vim-startify#158]
Hello,

When I try to load a saved session, I get the following error:

<pre><code>
Error detected while processing BufLeave Auto commands for "NERD_tree_*":
E121: Undefined variable: b:NERDTree
</code></pre>

Thank you in advance :)

**Comment by mhinz** [comment]
Hi,

Can you give a minimal example for reproducing? Just saving any file + nerdtree and reloading doesn't thrown an error for me, although the nerdtree window is blank of course, since local variables don't get saved.

What is your `sessionoptions` set to and do you have any startify options set?

**Comment by ScriptorNY** [comment]
Thank you for your answer :)

So the steps to reproduce :  open gvim from a directory, save the session, save file and close gvim. Reopen gvim, and, from startify, choose the previously saved session.

Concerning the sessionoptions, I haven't touched anything.

Here are all the options concerning startify in my vimrc:

<pre><code>
autocmd VimEnter *
                \   if !argc()
                \ |   Startify
                \ |   NERDTree
                \ |   wincmd w
                \ | endif
let g:startify_session_dir = '~/.vim/sessions'
let g:startify_list_order = [
    \ [ '   Recent files:'],
    \ 'files',
    \ [ '   Recent files in this dir:' ],
    \ 'dir',
    \ [ '   Sessions:' ],
    \ 'sessions']
let g:startify_files_number = 5
let g:startify_custom_indinces = ['f', 'g', 'h']
let g:startify_custom_header =
      \ map(split(system('fortune | cowsay'), '\n'), '"   ". v:val') + ['','']
</code></pre>

Thank you again :)

**Comment by mhinz** [comment]
> open gvim from a directory, save the session, save file and close gvim

Which file?

Please give the exact commands. What I did:

`$ vim` (now I have NERDTree left and Startify right)
`:SS foo` (save session)
`:qa` (quit Vim)
`$ vim`
`:SL foo`

Then I get:

```
Error detected while processing /Users/mhi/.dotfiles/vim/session/foo:
line   23:
E95: Buffer with this name already exists
```
...since NERDTree tries to open a new window called "NERD_tree_1" again.

**Comment by ScriptorNY** [comment]
Oh, sorry for not having being precise enough :/

So when the file I was talking about was about was just a test file to be saved in the session.
So to be clearer, once I performed an <code>:SS</code> I closed vim. Then when I opened it again and chose the session from startify, I got this error.

**Comment by mhinz** [comment]
Okay, I'm using the latest version of Vim, nerdtree and startify.

```vim
call plug#begin('~/.vim/bundle')
  Plug 'scrooloose/nerdtree'
  Plug '/data/github/vim-startify'
call plug#end()

au VimEnter *
      \   if !argc()
      \ |   Startify
      \ |   NERDTree
      \ |   wincmd w
      \ | endif
```

This is the whole vimrc. (You can use `:finish` to stop sourcing the vimrc at a certain line.)

`$ vim`
`:e ~/.vim/vimrc` (so I have nerdtree on the left, file on the right)
`:SS foo`
`:qa`
`$ vim`
`<choose foo>`

I still get the same thing I got before:

```
Error detected while processing /Users/mhi/.dotfiles/vim/session/foo:
line   27:
E95: Buffer with this name already exists
```

**Comment by ScriptorNY** [comment]
Okay, so i'm really sorry but it seems that uninstalling plugins and reinstalling them did the trick :)
So now when loading the session everything is okay :)

Thank you very much and sorry for all the trouble

**Comment by mhinz** [comment]
Hah, no problem. I'm glad it's working now. :-)
