### ISSUE TITLE
Option to remove some vars from session file

### ISSUE THREAD

**Issue by cHoco** [mhinz/vim-startify#159]
I see that there's an option to save additional vars ```startify_session_savevars```. Would it be possible to add an option to remove some vars from the session file?
This would solve a pretty big problem for me. I use a plugin that sets winminheight and winminwidth values and session files contain every time the line ```set winheight=1 winwidth=1``` that triggers a warning during the loading phase. So having an option to remove it would be awesome.
Anyway thank you so much for this plugin, really love it!

**Comment by mhinz** [comment]
`git pull && git checkout session-remove-lines`

vimrc:

```vim
let g:startify_session_remove_lines = ['winheight', 'winwidth']
```

Can you try if this works for you?

> Anyway thank you so much for this plugin, really love it!

I'm glad to hear that!

**Comment by cHoco** [comment]
Thank you for getting back to me and implementing it so fast!
It works perfectly, I just had to change the option in vimrc to:

```
let g:startify_session_remove_lines = ['set winheight=1 winwidth=1']
```

since as you said  both ```winwidth``` and ```winheight``` appear multiple times, and that line is the only one causing problems to me.
Again, many thanks for your hard work, it's really appreciated!

**Comment by mhinz** [comment]
Okay, I merged it into master and added a helptag for it.

Thanks for the feedback! :-)
