### ISSUE TITLE
Filenames with '%' fail to open

### ISSUE THREAD

**Issue by zwerch** [mhinz/vim-startify#160]
When I try to open a file from my mru who's name contains a `%`, it fails to open and shows the following error:
```
Error detected while processing function startify#open_buffers:
line   37:
E499: Empty file name for '%' or '#', only works with ":p:h"
```

I guess these symbols are not escaped, because if I open them with vim itself and type `:e`, it shows an escaped version in the autocomplete suggestion.
I also assume from the error message that it is the same case with `#`.

(In case anyone wonders, `%` are commonly used in BitBake append files.)

**Comment by mhinz** [comment]
Thanks for the report!

Actually `fnameescape()` was used, but before `glob()` which effectively reversed the operation.

It should work now.

**Comment by mhinz** [comment]
Please reopen, if it still isn't working for you.
