### ISSUE TITLE
<SNR>85_genesis..startify#insane_in_the_membrane..<SNR>

### ISSUE THREAD

**Issue by nunoh** [mhinz/vim-startify#161]
Hey. All of the sudden (I think after a recent update) I started getting this message every time I start vim, which I think is something in this plugin's code:

```
Error detected while processing function <SNR>85_genesis..startify#insane_in_the_membrane..<SNR>109_show_dir..<SNR>109_display_by_path..<SNR>109_filter_oldfiles:
line   11:
E16: Invalid range
Press ENTER or type command to continue
Error detected while processing function <SNR>85_genesis..startify#insane_in_the_membrane..<SNR>109_show_dir..<SNR>109_display_by_path..<SNR>109_filter_oldfiles:
line   11:
E16: Invalid range
```

**Comment by mhinz** [comment]
Hi.

Something's fishy here! Are you sure you're on the latest master? Because line 11 in that function is actually: https://github.com/mhinz/vim-startify/blob/master/autoload/startify.vim#L50 an

Hmm, if you're on the latest master, then line 11 in that function should be: https://github.com/mhinz/vim-startify/blob/master/autoload/startify.vim#L415 

The error suggests an `E16`, which is an invalid range given to a command, e.g. `:1000p` in a file with less than 1000 lines.

But I see no way `let absolute_path = glob(fnamemodify(resolve(fname), ":p"))` could produce such an error.

Can you verify that is the line you see?

**Comment by nunoh** [comment]
Thanks for your time.

I've just updated the plugins with the Vundle's `:PluginUpdate` command, so I think I might be using latest master.

> Can you verify that this is the line you see?

Yep. I have that one.
![screen shot 2015-05-21 at 13 28 10](https://cloud.githubusercontent.com/assets/1161423/7748788/be95d3a0-ffbf-11e4-8f32-37559994bc59.png)

Also, I am not getting the error every single time. Apparently it depends where I start `vim`. The weird thing is that it seems to work when I start it in all the paths that are contained in the one where I've been starting `vim` the more lately, which is a project I've been working on. For instance, starting `vim` in these paths I don't get the error:

```
/Users/Nuno/projects/nunoh/aether
/Users/Nuno/projects/nunoh
/Users/Nuno/projects
/Users/Nuno
/Users
/
```

but If I try starting it in something like these ones, I get the error:

```
/Users/Nuno/projects/nunoh/JamBuddy
/Users/Nuno/projects/nunoh/cv
/Users/Nuno/Dropbox
(for any other path really)
```

**Comment by mhinz** [comment]
I have to admit that I currently have no idea what this is causing.

I checked your vimrc and it seems you have all startify options commented out. Good.

Now, the last commit changed that exact line, but it works for me (OSX) and as I said, I have no idea how it could throw an `E11`. Anyway, try `git checkout 1f42935` (or `git checkout HEAD^`) and see if it's still happening.

If it's still happening, please paste the output of `:set viminfo`.

**Comment by nunoh** [comment]
If I try the `1f42935` commit it works ok! Reverting it back to HEAD makes the error appear once again.

Running `:set viminfo` outputs me this `viminfo=!,'100,<50,s10,h`. Thanks for your help!

**Comment by mhinz** [comment]
Okay, so `glob()` is the culprit somehow. Now we need some good, old print debugging, insert this above our faulty line:

```viml
    echomsg 'DEBUG: '. fnamemodify(resolve(fname), ":p")
```

Now, if the error occurs, what's the last `DEBUG` line above it? (You can always use `:messages` to see all last messages.)

**Comment by nunoh** [comment]
I get this:
```
DEBUG: '/Users/Nuno/projects/nunoh/aether/workers/lib/tasks/[[buffergator-buffers]]'
```

**Comment by mhinz** [comment]
Wow, this issue is really weird, but I can finally reproduce it: `:echo glob('[b-a]')`

Thanks, I'm looking into a proper solution!

**Comment by nunoh** [comment]
Glad to be of help and thanks for your time (and plugin!) again.

**Comment by mhinz** [comment]
It took a bit, since I wanted to remove `glob()` without breaking the Win support, but it should work now.

**Comment by nunoh** [comment]
It's working for me no probs. Thanks! :+1: Feel free to close the issue as you please.

**Comment by mhinz** [comment]
Awesome! Thanks for reporting this issue.
