### ISSUE TITLE
Error loading any session

### ISSUE THREAD

**Issue by brychta-v** [mhinz/vim-startify#163]
I updated to most recent version (8fd4247) and now I can't open any session. It displays this error message:
"Error detected while processing function startify#open_buffers..startify#open_buffers:
line 11:
E716: Key not present in Dictionary: 20
E15: Invalid expression: s:entries[markers.original_index]"

I try delete the session and create new one, but the same happens. Before the update it works fine.

**Comment by mhinz** [comment]
I recently started revising the whole buffer opening mechanism.. and introduced some bugs.

Nevertheless, it should work now!

**Comment by kriox26** [comment]
I've just updated and it's not working, can't open any session. I did the same thing that brychta-v, delete sessions and create new ones but it keeps happening. The error message is this one: 
Error detected while processing function startify#open_buffers
Line 8
E132: Function call depth is higher than 'maxfuncdepth'

**Comment by learningjs** [comment]
@mhinz I am unable to open numbered options (i.e.: [0]  /prjs/.../file.something):
```javascript
Error detected while processing function startify#open_buffers..startify#open_buffers
..<SNR>105_set_mark:
line    3:
E716: Key not present in Dictionary: 2
E15: Invalid expression: s:entries[line]
```
Is this related?

**Comment by mhinz** [comment]
Okay.. _now_ everything should work! *crosses fingers*

**Comment by brychta-v** [comment]
I can confirm it works for me now :wink:

**Comment by learningjs** [comment]
Perfect!

**Comment by kriox26** [comment]
It works for me too!! Thanks!

**Comment by mhinz** [comment]
:metal:

Thanks for the feeback!
