### ISSUE TITLE
Error loading bookmarks

### ISSUE THREAD

**Issue by byaruhaf** [mhinz/vim-startify#164]
hi mhinz

my vimrc config for vim-startify is below 

" vim-startify {{{
let g:startify_list_order = [
      \ ['   Bookmarks:'],
      \ 'bookmarks',
      \ ['   MRU:'],
      \ 'files' ,
      \ ['   MRU (dir):'],
      \ 'dir',
      \ ['   Sessions:'],
      \ 'sessions',
      \ ]
let g:fortune_vimtips_auto_display = 0
let g:startify_change_to_vcs_root = 1
let g:startify_change_to_dir = 0
let g:startify_files_number = 8
let g:startify_session_dir = "~/.vim/sessions"
let g:startify_bookmarks = ['/home/byaruhaf/code/erlang/otto/apps/otto/src/fact.erl','/home/byaruhaf/code/erlang/otto/apps/otto/src/powers.erl']

i get the following error when i try to open the Bookmarks 

Error detected while processing function startify#open_buffers..startify#open_buffers:
line   11:
E716: Key not present in Dictionary: 0
E15: Invalid expression: s:entries[markers.original_index]
Press ENTER or type command to continue

**Comment by mhinz** [comment]
Argh, sorry for the inconvenience. Before the weekend I refactored the code so that almost everything gets opened through `startify#open_buffers()`.. but I forgot to include bookmarks.

Thanks for reporting!

**Comment by byaruhaf** [comment]
Thanks its now working :100:
