### ISSUE TITLE
Bookmark / Session Restoration Bug

### ISSUE THREAD

**Issue by amadeus** [mhinz/vim-startify#165]
Seems this commit be8bfe8513bc609e78ec7ac3de3472714e30b8e3 broke my bookmark and session autoloading setups.

My startify screen looks like this:

![before](https://dl.dropboxusercontent.com/s/8ysxnttnwzdrlii/Scratch_2015-06-02_12-45-18.png?dl=0)

If I press 0, Vim would CD into that directory, and autoload my `Session.vim` file in that directory.

Now when I press 0, I get this:

![after](https://dl.dropboxusercontent.com/s/zikt9etsomrgy05/app.kiip.me_2015-06-02_12-47-56.png?dl=0)

It doesn't CD anymore and instead looks like it just tried to perform an `:edit Sites/directoryname` instead.

If necessary, I can post my Startify .vimrc settings as well.

**Comment by mhinz** [comment]
Yup, please list your startify settings as well.

I can actually reproduce the issue with neovim, but not in Vim.

**Comment by amadeus** [comment]
```viml
let g:startify_bookmarks = [
  \ '~/Sites/app.kiip.me',
  \ '~/Sites/kiip.me',
  \ '~/Development/ether/App',
  \ '~/Development/ether-design-docs',
  \ '~/Development/Engine.js',
  \ '~/.vim/bundle',
  \ ]
" \ '~/Sites/eightbit.me',

let g:startify_custom_header = [
  \ '                                _________  __  __',
  \ '            __                 /\_____   \/\ \/\ `\',
  \ '   __   __ /\_\    ___ ___     \/____/   /\ \ \ \  \',
  \ '  /\ \ /\ \\/\ \ /` __` __`\        /   /  \ \ \_\  \__',
  \ '  \ \ \_/ / \ \ \/\ \/\ \/\ \      /   / __ \ \___   __\',
  \ '   \ \___/   \ \_\ \_\ \_\ \_\    /\__/ /\_\ \/___/\_\_/',
  \ '    \/__/     \/_/\/_/\/_/\/_/    \/_/  \/_/      \/_/',
  \ '',
  \ '  ======================================================',
  \ '',
  \ ]

let g:startify_custom_footer = [
  \ '',
  \ '  ======================================================',
  \ '',
  \ '  Copyright Tubez, 2014'
  \ ]

let g:NERDTreeHijackNetrw = 0
let g:startify_session_autoload = 1
let g:ctrlp_reuse_window = 'startify'
let g:startify_files_number = 4
let g:startify_list_order = ['bookmarks', 'files']
let g:startify_change_to_dir = 1

let g:startify_skiplist = [
  \ 'COMMIT_EDITMSG',
  \ $VIMRUNTIME .'/doc',
  \ 'bundle/.*/doc',
  \ '\.DS_Store'
  \ ]


" Disable startify in terminal vim
" it just doesn't feel right
if !has("gui_running")
  let g:startify_disable_at_vimenter = 1
endif

augroup startify
  autocmd!
  " Hacky way to disable Powerline in Startify
  autocmd BufNew * set laststatus=2|highlight CursorLine guibg=NONE
  autocmd FileType startify set laststatus=0|highlight CursorLine guibg=#000000|setlocal cursorline
augroup END

```

**Comment by mhinz** [comment]
The commit above should make it work for you.

Funnily enough I noticed a bug a neovim where `:edit /tmp` would switch to `<cwd>/tmp` instead of `/tmp`. `:edit /tmp/` works, though. In Vim both variants switch to `/tmp`.

**Comment by amadeus** [comment]
Worked like a charm! Thanks a bunch!

**Comment by mhinz** [comment]
Thanks for reporting!

**Comment by amadeus** [comment]
Looks like I found another issue (that I think is related to this last change, thus re-opening).

If I just press `e` from Startify, to simply create a blank doc, I get the following error:

![example](https://dl.dropboxusercontent.com/s/jppto821xwhgzkh/Scratch_2015-06-02_17-25-47.png?dl=0)

After I press a key though, I get the blank document, so it still works, just the error.

**Comment by mhinz** [comment]
The commit above changes `:lcd %:h` to `:lcd %:p:h` which would be enough to prevent this problem, but it made no sense to check the user options for `[e]` in the first place.

This is done only for regular files now.

**Comment by amadeus** [comment]
Fix works great! Thanks again!

**Comment by poohzrn** [comment]
Hi mhinz - Can you help with the following problem?
I am able to save and restore sessions, however I get the following error every time.
```
Error detected while processing function startify#open_buffers..<SNR>77_open_buffer.
.startify#session_load..<SNR>77_create_last_session_link:
line    2:
E484: Cannot open file /tmp/vllxRPo/2
startify: Can't create 'last used session' symlink.
```
```
let g:startify_bookmarks = [ {'c': '~/git/dotfiles/dots/vimrc'} ]
let g:startify_list_order = [
       \ ['   Files'],       'files' ,
       \ ['   Directory '],   'dir',
       \ ['   Sessions '],  'sessions',
       \ ['   Bookmarks '], 'bookmarks',
       \ ]

 let g:startify_skiplist = [
       \ 'COMMIT_EDITMSG',
       \ ]
```
![2015-12-11-024732_1366x768_scrot](https://cloud.githubusercontent.com/assets/4310945/11733811/b04cf9b2-9fb1-11e5-824b-5b4ad2188e53.png)

**Comment by mhinz** [comment]
Under this line: https://github.com/mhinz/vim-startify/blob/master/autoload/startify.vim#L761 add:
```vim
echomsg 'cd '. shellescape(s:session_dir) .' && ln -sf '. shellescape(fnamemodify(a:spath, ':t')) .' __LAST__'
```

**Comment by poohzrn** [comment]
hi again im not sure either, however I get the following output:
```
cd '/home/lasse/.vim/session' && ln -sf 'sessiontest' __LAST__
Error detected while processing function startify#session_save..startify#session_wri
te..<SNR>80_create_last_session_link:
line    3:
E484: Cannot open file /tmp/vq2Q5dr/3
startify: Can't create 'last used session' symlink.
Session saved under: /home/lasse/.vim/session/sessiontest
Press ENTER or type command to continue
```

**Comment by mhinz** [comment]
Hmm, the `cd '/home/lasse/.vim/session' && ln -sf 'sessiontest' __LAST__` looks all right.

Let's break it down. It fails at calling `system()`. That function usually opens a temporary file which seems to fail in your case.

This is the exact command `system()` is using:
```
echo &shell &shellcmdflag &shellxquote 'some command' &shellredir tempname() &shellxquote
```
Can you paste the output?

**Comment by poohzrn** [comment]
Hi. 
```
:echo &shell &shellcmdflag &shellxquote shellescape('some command') &shellredir tempname() &shellxquote
```
using fish:
``` 
/usr/bin/fish -c  'some command' >%s 2>&1 /tmp/vSVWFv3/1
```
Then I tried changing my standard shell to bash:
```
/bin/bash -c  'some command' >%s 2>&1 /tmp/vcGrABL/3
```



Press ENTER or type command to continue

```
:echo system('ls')
```
Works just as expected

**Comment by mhinz** [comment]
And you get the same error with `'shell'` being bash, right?

What about `:echo system('ls && cat')`?

**Comment by poohzrn** [comment]
Same error yep, however I am not able to do
```:echo system('ls && cat')```  using fish as shell. 
I can do :
```:echo system('ls ; cat')``` <-- fish syntax
and get the right output.

**Comment by poohzrn** [comment]
Changing line https://github.com/mhinz/vim-startify/blob/master/autoload/startify.vim#L763
to 
```        \ .' ; ln -sf '. shellescape(fnamemodify(a:spath, ':t')) .' __LAST__') ```
did the trick. 
Thanks for the help.

**Comment by mhinz** [comment]
@poohzrn I assumed every shell would support `&&`. :\

The latest plugin should make it work without issuing any warning messages.

**Comment by poohzrn** [comment]
@mhinz to be fair, that is a reasonable assumption.
I just just updated and it works like a charm. Thanks for a great plugin :+1:

**Comment by mhinz** [comment]
@poohzrn Thank you for the feedback!
