### ISSUE TITLE
:SSave not saving my tabs or SLoad not opening them?

### ISSUE THREAD

**Issue by steadystatic** [mhinz/vim-startify#168]
It's probably another plugin, but for some reason I have tabs open and save my session then when I open vim again and select my session from Startify, the tabs are gone (buffers are still present. Is there an option to set?

**Comment by mhinz** [comment]
Is `:set ssop` listing `tabpages`?

**Comment by steadystatic** [comment]
That was it! PEBKAC :) Thanks for the outstanding vim plugin, I use it every day!

**Comment by mhinz** [comment]
Hah, I'm glad that you like it!
