### ISSUE TITLE
Proposal for adding config option for custom Session.vim filename

### ISSUE THREAD

**Issue by fogine** [mhinz/vim-startify#169]
As the title says, it would be nice if I could tweak file name which startify search for in current dir at vim startup.

Thanks for excellent plugin!

**Comment by mhinz** [comment]
What's your use case? I just wonder, if someone uses the same static session filename for every directory, why choose one different from the default? Another plugin?

**Comment by fogine** [comment]
Sorry for not responding that long time, I've not noticed your response.

`What's your use case? I just wonder, if one uses the same static session filename for every directory, why choose one different from the default? Another plugin?`

I use one static session filename for every directory. I'm just used to name that file differently ... have it already in my mushle memory :) It's not something I could not live without though...

**Comment by mhinz** [comment]
The change itself would be pretty easy, but I think this is too uncommon of a use case to justify yet another option. This plugin has more than enough already.

The customer is king, but unless this is a dealbreaker for you, I'd like to decline this proposal.

Thanks for the feedback nevertheless!

**Comment by fogine** [comment]
`The customer is king, but unless this is a dealbreaker for you, I'd like to decline this proposal.`
Understood. So far, I've not hit any specific issues with the option being set statically...

(Note: It's just harder to type 'Session.vim' than something like 'vimproject' when saving sessions.
 Although `SSave` command allow custom session name, session file isn't sourced automatically if it's not named "Session.vim"  ).

if I hit any issue, I'll reopen and ask you again, politely.
Thank you again, for  sharing your plugin with community!

**Comment by mhinz** [comment]
I don't know your workflow, but just doing `:mks` is writing to `Session.vim` automatically. Starting Vim (or using `:Startify`) in the same directory will find that file and show it automatically.

`:SS` works different anyway as it simply puts all sessions into one directory making it possible to list them all in `:Startify`.

> Thank you again, for sharing your plugin with community!

I'm glad it's useful to other people, too!
