### ISSUE TITLE
Whitespaces in the ascii graphics

### ISSUE THREAD

**Issue by norbertklar** [mhinz/vim-startify#170]
There's always 2 whitespaces in the ascii art, and I don't know how to avoid it.

Used code:

```
let g:startify_custom_header =
          \ map(split(system('fortune | cowsay'), '\n'), '"   ". v:val') + ['']
```

![kkkzpre](https://cloud.githubusercontent.com/assets/9632419/8309714/37b41456-19cc-11e5-80b2-0d963cd614dd.png)

**Comment by mhinz** [comment]
If you're on a Unix-like system, you probably have the program `sed` installed. You could trim the whitespace like this:

```
let g:startify_custom_header =
          \ map(split(system('fortune | cowsay | sed "s/[[:blank:]]*$//"'), '\n'), '"   ". v:val') + ['']
```

**Comment by norbertklar** [comment]
Works like a charm thanks man!

![ehqesln](https://cloud.githubusercontent.com/assets/9632419/8310578/25ab5238-19d1-11e5-89c3-b8ace700f82b.png)

**Comment by mhinz** [comment]
Glad you like it! :-)
