### ISSUE TITLE
this can not be used with nerdtree together ?

### ISSUE THREAD

**Issue by ilovezy** [mhinz/vim-startify#172]
hello there, I  really love this plugin. I use this for a few month, but sometimes I need nerdtree open when I click vim icon, however startify plugin can not showup when I set nerdtree auto open at vim start , is there any way to set these two plugin auto start together?

**Comment by mhinz** [comment]
Hi,

see if `:h startify-faq-6` works for you.

If not, what did you do for NERDTree to autostart?

**Comment by ilovezy** [comment]
thank you sosososo much! It works,yeah
![qq 20150702172940](https://cloud.githubusercontent.com/assets/8774988/8473973/dd6d6dc4-20df-11e5-8301-05376476fe18.png)

**Comment by ilovezy** [comment]
by the way, I think this cow is very cute,but I can't see this.how could I make this showup?
![qq 20150702173055](https://cloud.githubusercontent.com/assets/8774988/8474057/56dfd264-20e0-11e5-90d5-e996e01c796b.png)

**Comment by mhinz** [comment]
The screenshot used `cowthink` from OSX, I'm not sure if that's available on Linux.

But on Linux you could choose different things via flag, e.g. `cowsay -f tux` etc.
