### ISSUE TITLE
Issue when closing GVim with auto-save on.

### ISSUE THREAD

**Issue by MeanEYE** [mhinz/vim-startify#174]
I've been experiencing this issue lately. It's hard to reproduce but every now and then I will get this error when closing GVim. Most of the times it doesn't happen. It might have to do something with `vimdiff` or some other window but I didn't manage to find a pattern yet.
![2015-08-03-220220_901x280_scrot](https://cloud.githubusercontent.com/assets/1911594/9046526/71f36372-3a2b-11e5-95ef-b059337c2ff6.png)

**Comment by mhinz** [comment]
Hmm, `:h E523` seems to suggest that `'secure'` was set. By another plugin?

That said, with "auto-save" you mean `g:startify_session_persistence = 1`? When a `vimdiff` is part of a session.

I'm wondering if writing the session should just be skipped if `&diff` or `&secure` is set.

**Comment by MeanEYE** [comment]
Yes, `session_persistence` is set to `1`. But I am not convinced `vimdiff` is the reason since I can't reproduce. My config does have `secure` set. My question is why doesn't this error always pop up and only sometimes?

**Comment by mhinz** [comment]
I have to admit that I never used that option before. Let me play around with it a bit.

BTW, do you also set `'exrc'`?

**Comment by MeanEYE** [comment]
I do indeed set `exrc` but I don't have those files anywhere. Which make me think I should just get rid of `exrc` all together. Hopefully that will fix it. Strange thing is, I open a session and work on it. If error happens and I close Vim, reopen that session. Error won't happen again. That's what confuses me since I can't reliably reproduce it.

**Comment by MeanEYE** [comment]
Directory in question which produced error in first screen shot I uploaded.
![2015-08-05-105055_503x417_scrot](https://cloud.githubusercontent.com/assets/1911594/9081814/df1785de-3b5f-11e5-97f4-99766a5bd8af.png)

**Comment by mhinz** [comment]
How do you load the session? Or is `/home/meaneye/Development/Vim` your session directory for startify?

**Comment by MeanEYE** [comment]
I load session through Startify buffer/screen. That directory is where all my session files are stored.

**Comment by mhinz** [comment]
Okay, a quick `ag` in Vim sources tells me, that the `E523` is tied to the `secure` option for sure. Will investigate further.

**Comment by MeanEYE** [comment]
Well, I can get rid of it, but I feel it's much more important to find why this is happening.

**Comment by mhinz** [comment]
Yup, same here. I'm curious now.

**Comment by mhinz** [comment]
What's the output of `au VimLeave`?

**Comment by MeanEYE** [comment]
![2015-08-05-122117_450x128_scrot](https://cloud.githubusercontent.com/assets/1911594/9083673/7d875990-3b6c-11e5-8db8-c1e6d3ed54c5.png)

**Comment by mhinz** [comment]
How do you close Vim?

**Comment by MeanEYE** [comment]
Most of the time just by closing window since `:qa` kills windows and that messes up my session.

**Comment by mhinz** [comment]
You attempt to close the window and _then_ get the `E523`?

**Comment by mhinz** [comment]
I'm only grasping straws here, but you could try inserting `stopinsert` between these 2 lines: https://github.com/mhinz/vim-startify/blob/master/plugin/startify.vim#L41-L42

**Comment by MeanEYE** [comment]
Yes, after pressing `Alt+F4` that thing pops up. Let me check about the line.

**Comment by MeanEYE** [comment]
Nope. Happens again. But I am closing in on reproducing it properly. This is what I do to reproduce 1/3 of the times:

- Start GVim;
- Open session by pressing number in Startify buffer;
- Press `O` to insert line before;
- Write something, escape and save;
- Press `Alt+F4`.

Considering others are not complaining about this, am going to try and disable all of my other plugins and see if I can reproduce.

**Comment by MeanEYE** [comment]
Just like I thought. Can't reproduce with other plugin disabled.

**Comment by mhinz** [comment]
Hmmm.. but since there was no other plugin doing stuff on `VimLeave`, it must be a certain option getting set then.

**Comment by MeanEYE** [comment]
Looks like it's `vim-repeat` from @tpope. o_0 And it's conclusive that plugin is the culprit. With it disabled I didn't manage to reproduce the issue at all. With it enabled I get those 1/3 to 1/2 of the times.

**Comment by mhinz** [comment]
Let me install it.

**Comment by MeanEYE** [comment]
It also requires this:

```vimscript
silent! call repeat#set('\<Plug>MyWonderfulMap', v:count)
```

**Comment by MeanEYE** [comment]
And looking at its rather small source, I see he has some `BufLeave` handlers.

**Comment by mhinz** [comment]
Can you also reproduce it without `'secure'`? The sources seem misleading as `E523` is also used in other cases.

**Comment by MeanEYE** [comment]
Yup. Even with `secure` disabled, I get this:
![2015-08-05-132715_822x242_scrot](https://cloud.githubusercontent.com/assets/1911594/9084590/b33729ea-3b75-11e5-8a7a-f307121ff079.png)
And now I can pretty reliably reproduce following the steps above.

**Comment by mhinz** [comment]
This is one of the weirdest issues I had in a long time. I cannot see how anything in `vim-repeat` could interfere with a function called at `VimLeave`.

If you're really bored, you could start removing `autocmd` lines from `vim-repeat`, if you're sure that it's the culprit.

**Comment by MeanEYE** [comment]
I am 80% sure this is where the issue is coming from since I am unable to reproduce with this plugin disabled. Right now I have work to do, so I'll try experimenting on some other occasion. Am not going to give this too much thought though as Vim is getting weird issues lately. I have frequent lockups because of my `iabbrev` definitions and other stupid things like that.

**Comment by mhinz** [comment]
I'm still convinced it's a bug in Vim that happens in combination with ungracefully quitting gvim via `<kbd>Alt</kbd><kbd>F4</kbd>.

The latest patch changes the exception to a mere error message, so gvim should quit in your case, but `:mksession` will fail nevertheless. Nothing I can do about in this plugin.

**Comment by MeanEYE** [comment]
Understandable. I didn't see anything else to indicate it's a plugin error and not a Vim one.
