### ISSUE TITLE
Add to recents list when :saving new file

### ISSUE THREAD

**Issue by thirtythreeforty** [mhinz/vim-startify#175]
I love this plugin!  I have a feature request:  Could Startify add `:new` files that are then `:sav`ed to the list of recent files?  I was a little confused when they didn't appear, but I guess it only tracks files that have been `:e`dited, correct?

**Comment by mhinz** [comment]
> I love this plugin!

Glad to hear that. :)

> I was a little confused when they didn't appear, but I guess it only tracks files that have been :edited, correct?

Vim keeps the last used files in the viminfo file (see `:h viminfo-'`) and exposes it via the internal `v:oldfiles` variable. Unfortunately it only gets updated at exit, so this plugin uses events to edit `v:oldfiles` manually: https://github.com/mhinz/vim-startify/blob/master/plugin/startify.vim#L34-L37

I added the `BufFilePre` event that should handle `:saveas` now.

**Comment by thirtythreeforty** [comment]
Works great! Thanks :)

**Comment by mhinz** [comment]
Thanks for reporting!
