### ISSUE TITLE
Feature request: add custom indices for bookmarks

### ISSUE THREAD

**Issue by pauloromeira** [mhinz/vim-startify#176]
This plugin is really awesome, but it would be great if I could bind custom indices to specific bookmarks (e.g. pressing 'r' to open '~/.vimrc').
P.S. I wish I could have bookmarks on the last section.

Anyway, thanks a lot for the plugin!

**Comment by mhinz** [comment]
__Way A__:

You can change the order of the sections via `:h g:startify_list_order`. You could shuffle `bookmarks` to the top and use `:h g:startify_custom_indices`, so that bookmarks always start with `[a]`, `[b]`, etc.

Example config:

```viml
let g:startify_list_order = ['bookmarks', 'sessions', 'files', 'dir']
let g:startify_custom_indices = ['r']
let g:startify_bookmarks = ['~/.vimrc']
```

__Way B__:

If it's only a few mappings, you could hardcode them via mappings. E.g.

```viml
autocmd User Startified nnoremap <buffer> r :edit ~/.vimrc
```

**Comment by pauloromeira** [comment]
Many thanks for the reply. But don't you think that, since bookmarks are fixed paths, it would make sense to assign them an (optional) hotkey? Something like: 
```viml
let g:startify_bookmarks = [ { 'r': '~/.vimrc' }, 'other/path' ]
```

**Comment by nicolaiskogheim** [comment]
For me, the thing you are requesting is the sole reason I use startify. I want to say `vim` on the commandline and immediately hit a key to edit one of my bookmarked files (which I do very often). I had to put bookmarks on the top, but I, like you, want them on the bottom, and I really, really want to have the same key open the same bookmarked file every time.

**Comment by mhinz** [comment]
@pauloromeira Sorry for the long delay, but I was away from computers for a while.

The latest commit adds support for this:

```vim
let g:startify_bookmarks = [ { 'r': '~/.vimrc' }, 'other/path' ]
```

I chose this approach, because it's the only one I saw that doesn't break backwards-compatability.

Does it work for you?

**Comment by mhinz** [comment]
Well, it's implemented now! Thanks for creating this issue.

**Comment by pauloromeira** [comment]
Thanks a lot! :+1: :+1:
