### ISSUE TITLE
Feat: disabling keys to open multiple files at once

### ISSUE THREAD

**Issue by nicolaiskogheim** [mhinz/vim-startify#178]
From the readme:
> Moreover, you can open several files at one go! Navigate to an entry and hit either b (open in same window), s (open in split), v (open in vertical split) or t (open in tab) for marking it. You can mark several entries and also mix different markers. Afterwards execute all the markers in the order they were given via <cr>.

What startify gives me is a consistent interface for editing my config files. Having the ability to write `vim`, hit `enter` and then one single letter to go edit one of my many bookmarked files is pure gold for me. And, it is close to be the only thing I use `vim-startify` to do, thus, I would like to have keys available that are intuitive to use with a certain bookmark, like 'v' for `.vimrc`.

My wish: To be able to disable mappings. First and foremost the ones discussed in the block of text appearing first in this post. I could even very much like to be able to use every possible key as a shortcut. I can use `ctrl-d` and `ctrl-u` to scroll, and those two mappings is all I need.

1. Can we have the option to disable the v,s,t,b keys?
2. Can we have the option to use every letter on the keyboard for shortcuts?

**Comment by mhinz** [comment]
Hi. Sorry for the late response, but I was away for some time.

You can't disable the mappings per se, but you can simply overwrite them. See `:h g:startify_custom_indices`.

Then there is `:h g:startify_list_order`. So you can reorder the shown lists.

Now you could use a combination of both. Let's assume you always have 2 bookmarks. With `z` you want to open `~/.zshrc` and with `v` you want to open `~/.vim/vimrc`.

```vim
let g:startify_bookmarks = ['~/.zshrc', '~/.vim/vimrc']
let g:startify_list_order = [ 'bookmarks', 'files', 'dir', 'sessions' ] " show bookmarks first
let g:startify_custom_indices = [ 'z', 'v' ]
```

Now you could use `z` and `v` as intended. Would this be a solution to you?

**Comment by nicolaiskogheim** [comment]
Hi. No problem  :)

I have always had this:
```vim
let g:startify_list_order = [ 'bookmarks', 'files', 'sessions', 'dir' ]
let g:startify_bookmarks = [ '~/.vimrc', '~/.bashrc', '~/.zshrc', '~/.tmux.conf', '~/.gitconfig' ]
let g:startify_custom_indices = ['v', 'b', 'z', 't', 'g']
```

But this is not overwriting anything :(
`v` still works as "mark for opening in vsplit".

**Comment by mhinz** [comment]
The latest commit should fix this.

But I just read in another issue that you'd like to have bookmarks at the bottom. I probably really go for this way:

```vim
let g:startify_bookmarks = [ '~/foo', { 'b': '~/bar' } ]
```

This is the only sane way I see at the moment since it doesn't break backwards-compatability.

**Comment by mhinz** [comment]
The above mentioned change to `g:startify_bookmarks` is in effect now!

**Comment by nicolaiskogheim** [comment]
Great!

Thank you :) This is exectly what I wanted.

**Comment by mhinz** [comment]
You're welcome!
