### ISSUE TITLE
Ignore <sessionname>x.vim files in session/ in the session shortlist

### ISSUE THREAD

**Issue by SnoringFrog** [mhinz/vim-startify#179]
Vim uses <sessionname>x.vim files to run extra commands on a session (for instance, I sometimes use it to keep a custom function for a session). These aren't valid session files, but need to be kept alongside the session files. 

Is there anyway to ignore these in the session list? (Maybe like the recent files skiplist, but just for the sessions?)

**Comment by mhinz** [comment]
Thanks for reporting!
