### ISSUE TITLE
Startify main screen options not working

### ISSUE THREAD

**Issue by rajasharan** [mhinz/vim-startify#183]
Hi @mhinz ,

Something happened between last few days - few days ago I uninstalled and re-installed all my plugins. Didn't notice anything unusual.

Now I uninstalled and re-installed all my plugins (playing with pluggin managers) - now I see something broke in Startify

In the :Startify home screen - none of the options are working - e, 0 ,1, 2, q 
Nothing happens - the home screen just stays there.

How can I prove or disprove issue with Startify itself or something else screwed on my side?

**Comment by mhinz** [comment]
Well, I was away for 2 month and started pushing out new commits just today. So.. it must be one of those commits, although everything seems to work as intended for me.

Do you have `g:startify_custom_indices` set?

**Comment by rajasharan** [comment]
I don't have any g:startify* set in my .vimrc

**Comment by mhinz** [comment]
What is the output of `:nmap 0` in the Startify buffer?

**Comment by rajasharan** [comment]
No mapping found

**Comment by mhinz** [comment]
Check if `:scriptnames` is showing `...autoload/startify.vim`. I guess it got never loaded.

**Comment by rajasharan** [comment]
both files do show up at the very end

![snip20151103_3](https://cloud.githubusercontent.com/assets/299522/10924594/b25aab92-8255-11e5-8ca5-f3f88e47acd5.png)

**Comment by rajasharan** [comment]
:verb map 0 
also says No mapping found

**Comment by mhinz** [comment]
Hmm.. this looks about all right. If `autoload/startify.vim` was loaded, it means that `startify#insane_in_the_membrane()` was called which again calls `s:set_mappings()`.

Does it work if you execute `:Startify` before trying any of the mappings?

**Comment by rajasharan** [comment]
yeah I'm on the latest commit 
(I'm using vim-plug, just now deleted the whole plugins folder and re-installed)

:Startify command does work (I removed all the mappings I had in .vimrc)

**Comment by mhinz** [comment]
So it works after `:Startify`, but not when the Startify buffer is automatically shown at startup, correct?

**Comment by rajasharan** [comment]
I tried the whole setup on a different machine - everything worked without trouble.
Something is wrong with my box. I'll close this issue.

**Comment by timss** [comment]
I've not been quite able to narrow down why, but I'm seeing the same behaviour on a setup using Vim 7.3, while 7.4 seems to work fine. Not sure if this bug is really resolved, or if @rajasharan got 'lucky by installing a newer version of Vim.

Latest commit as of date. 

**Non-working:** 7.3 (2010 Aug 15, compiled Oct 26 2012 16:45:32) Included patches: 1-547
**Working:** 7.4 (2013 Aug 10, compiled Mar 31 2015 23:36:07) Included patches: 1-488, 576

For both, this was the rc used:

    $ cat .vimrc
    set nocompatible

**Demo:** https://my.mixtape.moe/onrhyj.webm

>What is the output of :verb map 0 in the Startify buffer?

Index numbers work even for my 7.3 install, `e` does not however.

    :verb map e
    No mapping found

The expected output if it worked (i.e my 7.4 install):

    :verb map e
    n  e           *@:call startify#open_buffers('2')<CR>
            Last set from ~/.vim/autoload/startify.vim

Same story for `<Enter>`, `q` etc.

---

Anything else I could possibly test? I'm assuming it should work with 7.3, or atleast I believe it used to work with 7.3 before.

**Comment by mhinz** [comment]
Hmm, maybe it has problems with the `<nowait>` that was introduced recently. Let me compile 7.3.488 and test.

**Comment by mhinz** [comment]
Okay, `<nowait>` was added in 7.3.1261. I thought it would be much older by now.. hmm.

**Comment by timss** [comment]
Thank you for looking into this. 

While 7.3.1261 is quite some time ago, it did not make its way into for example Debian 7 stable (Vim 7.3.547) or possibly other slow moving distros which will still be around for a while longer. 

Not sure how one would go about checking for this without leaving <7.3.1261 versions lagging behind functionality wise.

**Comment by mhinz** [comment]
Well, they'll have the problem with global mappings starting with `e`, `q` etc.

Could you kindly check if you can still reproduce it with this: `git pull && git checkout fix/nowait`.

**Comment by timss** [comment]
`e`, `q`, and numbers work as intended. 

`<Enter>` does not, and no mapping found with `:verb map <Enter>`. Manually invoking `:call startify#open_buffers()` works.

**Comment by mhinz** [comment]
Oops. Please pull again.

**Comment by timss** [comment]
Hm, not seeing any new commits?

**Comment by mhinz** [comment]
I force pushed into the same commit.

**Comment by timss** [comment]
Sorry, I didn't notice at first :-)

Yup, now everything works! Thanks.

**Comment by mhinz** [comment]
Awesome! I'm glad this bug is solved now.

I have to admit that I thought of `<nowait>` being a much older feature, since I try to be compatible to `>= 7.3` at least.

Thanks for all the feedback, I'll merge it into master now.

**Comment by timss** [comment]
Yeah, I'm a bit suprised it's that "new" as well. 

No problem, glad to help! Your plugins has been most useful.

**Comment by mhinz** [comment]
:metal:
