### ISSUE TITLE
Startify doesn't wait for double digit mappings in neovim

### ISSUE THREAD

**Issue by silenc3r** [mhinz/vim-startify#188]
When starting neovim with startify you can't use double digit mappings to open files. For example when trying to open file with index '11' a file with index '1' is opened immediately after pressing 1.
neovim version 0.1.0
How to reproduce:
run neovim with this config file (requires vim-plug)
```
call plug#begin('~/.config/nvim/plugged')
Plug 'mhinz/vim-startify'
call plug#end()
```

The problem does not exist in vim.

**Comment by mhinz** [comment]
You're probably not using the latest version. Please update.

**Comment by silenc3r** [comment]
I am using the latest version.

**Comment by mhinz** [comment]
D'uh.. please update again. It should be fixed now.

**Comment by silenc3r** [comment]
Fixed, thanks!

**Comment by mhinz** [comment]
Cool, thanks for reporting!
