### ISSUE TITLE
VimWiki

### ISSUE THREAD

**Issue by a-b** [mhinz/vim-startify#189]
I'm starting vimwiki as tmux shortcut
`nvim +VimwikiMakeDiaryNote`
Is there any way to temporary disable vim-startify for this case?

**Comment by mhinz** [comment]
This should work:

```
vim --cmd 'let g:startify_disable_at_vimenter = 1' +VimwikiMakeDiaryNote
```

**Comment by a-b** [comment]
This perfectly works! Thank you very much. I think this worth to be added to the [README.md](https://github.com/mhinz/vim-startify/blob/master/README.adoc)

**Comment by a-b** [comment]
@mhinz please check #190

**Comment by mhinz** [comment]
Splendid!
