### ISSUE TITLE
Using recently used changes context to file directory

### ISSUE THREAD

**Issue by bradurani** [mhinz/vim-startify#191]
I'm noticed that if I do
```
cd ~/project
vim
```
Then I choose a recently used in the current directory, such as
`spec/models/foo.rb`
 that it opens in the directory context of 
`spec/models`
This forces me to have to `cd` from inside Vim to get back to my project directory scope. With my workflow, this negates the advantage of the recently used, to the extent that I'm not really getting anything from the plugin.

Is this intentional? Can it be overriden?

**Comment by mhinz** [comment]
Yup, that's the default.

See `:h g:startify_change_to_dir` and maybe `:h g:startify_change_to_vcs_root`.
