### ISSUE TITLE
MRU (dir):  -->  PWD_MRU (~/working/dir/)

### ISSUE THREAD

**Issue by linuxcaffe** [mhinz/vim-startify#193]
A little thing has been bothering me; with startify, although the $PWD is used for MRU (dir): , I don't see the current working directory anywhere on the startify screen (by default). 

Why not change the MRU (dir): heading to something like PWD_MRU (~/current/working/dir/) ? A bit longer, a lot clearer!

**Comment by mhinz** [comment]
You can do that already, like this:

```vim
let g:startify_list_order = [
      \ ['   MRU'],               'files' ,
      \ ['   MRU '.getcwd().':'], 'dir',
      \ ['   Sessions'],          'sessions',
      \ ['   Bookmarks'],         'bookmarks',
      \ ]
```

But you're right of course, the default should be changed as well.

**Comment by mhinz** [comment]
The default values were too long in the first place, so I changed the whole default `g:startify_list_order`.

**Comment by mhinz** [comment]
*ping*

**Comment by mhinz** [comment]
Well, from the description you have given, the issue should be solved now! (Please reopen otherwise.)
