### ISSUE TITLE
Where is the cow?

### ISSUE THREAD

**Issue by F1LT3R** [mhinz/vim-startify#194]
I don't see the cow :)

**Comment by mhinz** [comment]
The cow is created dynamically! :-)

See `:h g:startify_custom_header`.

My own configuration looks like this: https://github.com/mhinz/dotfiles/blob/bcb3b6de4281f5e8381ff63b9891ecdb94d47dcc/vim/vimrc#L686-L692

**Comment by F1LT3R** [comment]
Thanks. Also found in the `:help startify`, thanks for the awesome plugin!

**Comment by mhinz** [comment]
You're welcome!
