### ISSUE TITLE
Run Command from Startify

### ISSUE THREAD

**Issue by Thubo** [mhinz/vim-startify#196]
Hey there,

Is there a way to run a command directly from Startify?

For example, I'm using [Vim-Plug](https://github.com/junegunn/vim-plug) to manage my plugins and it would be great to add a shortcut for the `:PlugUpdate` command (Or any other command).

A quick look a the help page didn't give me anything useful, but maybe I missed something...

I hope you can help me out :)

Thanks a lot!

**Comment by mhinz** [comment]
Well, you can't show it as an entry, since Startify is only supposed to access recent files, but.. you could simply create a mapping like this:

```vim
autocmd User Startified nnoremap <buffer> u :PlugUpdate<cr>
```

**Comment by Thubo** [comment]
Thanks a lot. That works like a charm!

Maybe you/I can find a way to also show an entry, but this is a non-important-nice-to-have feature request ;)

Thanks again for your quick help :)
