### ISSUE TITLE
Option for replacing environment variables in the path?

### ISSUE THREAD

**Issue by nhooyr** [mhinz/vim-startify#197]
I've created https://github.com/nhooyr/env.vim. It lets you to take the fullpath of a file and replace any environment variables in it with their names to create a short and readable path. I think it'd be a good idea to introduce a option to allow vim-startify to take advantage of it.

Maybe even some syntax highlighting.

I can create a PR for the option but I tried syntax highlighting for environment variables and I have no idea how to do it.

**Comment by mhinz** [comment]
I don't understand. Is this only about adding highlighting to Startify? (Why would one need a new option in that case?)

Could you give an example?

**Comment by nhooyr** [comment]
@mhinz fixed the link, https://github.com/nhooyr/env.vim

Say I have the environment variable `$GOSRC` and its value is `/Users/nhooyr/go/src/github.com/nhooyr`

Now say I am in the file `/Users/nhooyr/go/src/github.com/nhooyr/juke`. Instead of showing me the long filename or `~/go/src/github.com/juke`, env will take that path and return `$GOSRC/juke`.

**Comment by mhinz** [comment]
How about:

```vim
let env = {}
let ignore = { 'PWD': 1, 'OLDPWD': 1 }

for line in split(system('env'), '\n')
  let [k,v] = split(line, '^\w\+\zs\=')
  if v[1] != '/' || has_key(ignore, k)
    continue
  endif
  let env[k] = v[1:]
endfor

let path = '/data/go/src'

for [k,v] in items(env)
  if !stridx(path, v)
    let path = printf('$%s%s', k, path[len(v):])
  endif
endfor

" Assuming GOPATH=/data/go, this gives: $GOPATH/src
echomsg path
```

**Comment by nhooyr** [comment]
@mhinz 
Lets say

```zsh
 DOTFILES=/usr/local/etc/dotfiles
PLUGGED=/usr/local/etc/dotfiles/nvim/plugged
```

If I am in `/usr/local/etc/dotfiles/nvim/plugged` it should return `$PLUGGED` not `$DOTFILES/nvim/plugged`. In fact sometimes the environment variable may instead just make the path longer and thus should not be added.

It should also only replace the environment variables at the start of the path. Lastly it should always return the shortest path possible. Thats what [env.vim](https://github.com/nhooyr/env.vim) does. Its also easy to integrate into your status line and stuff, which is why I made it a separate plugin.

**Comment by mhinz** [comment]
> If I am in /usr/local/etc/dotfiles/nvim/plugged it should return $PLUGGED not $DOTFILES/nvim/plugged

The code above does that.

> It should also only replace the environment variables at the start of the path.

The code above does that.

> Lastly it should always return the shortest path possible.

The code above doesn't handle that, but it's easy to add by changing the conditional to..

```vim
  if v[1] != '/' || has_key(ignore, k) || len(k) > len(v)
```

**Comment by nhooyr** [comment]
I slept only 3 hours last night so I'm probably wrong but how does it make sure only the most specific variable is used and how does it only replace environment variables at the start of the path? The code doesn't even run for me without throwing an error on `let [k,v] = split(line, '^\w\+\zs\=')`

**Comment by mhinz** [comment]
If you mean the variable with the shortest name, it doesn't do that. But you could sort the `items(env)` part by length for that.

It only replaces at the start of the line because of `!stridx()` (which is the same as `stridx() == 0`).

Put `echomsg line` above the line you mentioned and paste the last line before the error is thrown. It's most likely an unexpected format.

**Comment by nhooyr** [comment]
@mhinz I mean the shortest path. Take a look at my example again. `$PLUGGED` is more specific than `$DOTFILES` and thus should match instead. Also you don't need to call the executable `env`. You can get the list of environment variables from within vim. http://stackoverflow.com/questions/11175842/how-to-list-all-the-environment-variables-in-vim.

Ah now I see how the `stridx()` line works.

Also what about mapping `$HOME` to `~`? Gotta expand it during the function because we want to compare and make sure we return the smallest path. Could probably add a special case easily but I went with a map in env.vim.

It really makes much more sense imo to use env.vim because if other plugins use it, its a universal configuration for the paths. One place to fix bugs, one place to add features.

**Comment by mhinz** [comment]
> It really makes much more sense imo to use env.vim because if other plugins use it, its a universal configuration for the paths. One place to fix bugs, one place to add features.

In a perfect world that would be correct. But what I have learned with all my plugins is that duplication is fine if it's convenient for the user. Adding a dependency for basically 2 loops is a bit too much, to be honest. Most people would simply not bother.

Here is the updated version with some configuration boilerplate:

```vim
" Configuration
let $DOTFILES = '/usr/local/etc/dotfiles'
let $PLUGGED  = '/usr/local/etc/dotfiles/nvim/plugged'
let paths     = [
      \ '/usr/local/etc/dotfile',
      \ '/usr/local/etc/dotfiles/nvim/plugge',
      \ '/usr/local/etc/dotfiles/nvim/plugged',
      \ '/usr/local/etc/dotfiles/nvim/plugged/foo',
      \ ]

let env = {}
let ignore = { 'PWD': 1, 'OLDPWD': 1 }

function! s:get_env()
  silent execute "normal! :return $\<c-a>')\<c-b>\<c-right>\<right>\<del>split('\<cr>"
endfunction

function! s:compare(foo, bar)
  return len(a:bar[1]) - len(a:foo[1])
endfunction

for k in s:get_env()
  let v = eval('$'.k)
  if v[0] != '/' || has_key(ignore, k) || len(k) > len(v)
    continue
  endif
  let env[k] = v
endfor

let sorted_by_len = sort(items(env), 's:compare')

for p in paths
  for [k,v] in sorted_by_len
    if !stridx(p, v)
      let p = printf('$%s%s', k, p[len(v):])
      break
    endif
  endfor
  echomsg p
endfor
```

This outputs:

```
/usr/local/etc/dotfile
$DOTFILES/nvim/plugge
$PLUGGED
$PLUGGED/foo
```

This should conform to your requirements now.

**Comment by nhooyr** [comment]
Looks good, thanks!

**Comment by mhinz** [comment]
I didn't want to make it anymore complicated and don't allow customizing which variables other than `PWD` and `OLDPWD` to ignore.

It still uses the old highlighting.

**Comment by mhinz** [comment]
Now you can change the highlighting of env variables via `:hi StartifyVar`.

**Comment by nhooyr** [comment]
@mhinz its great, one last addition.

If two environment variables represent the same directory, can you edit it to choose the smallest one in the length of the name?

**Comment by mhinz** [comment]
Yea, I just have to unfuck it for Windows first.. ;\

**Comment by mhinz** [comment]
Short work now!

**Comment by nhooyr** [comment]
@mhinz Great, think we can close this then.

**Comment by nhooyr** [comment]
Oh never mind, you still need to work on it for windows.

**Comment by mhinz** [comment]
Nope, that's also done already. :)
