### ISSUE TITLE
env variables in the directory specific MRU

### ISSUE THREAD

**Issue by nhooyr** [mhinz/vim-startify#198]
<img width="604" alt="screen shot 2016-02-14 at 1 08 30 am" src="https://cloud.githubusercontent.com/assets/10180857/13032201/8ae3e95e-d2b7-11e5-91ee-f644495c7ea2.png">

Could we have an option for replacing the environment variables in those paths as well? E.g. expand them to the full path first, then replace any environment variables.

**Comment by mhinz** [comment]
Assuming `FOO=/usr/local/dotfiles/nvim`, you want to see entries like `$FOO/init.vim`? That would be confusing together with `MRU /usr/local/etc/dotfiles`.

**Comment by nhooyr** [comment]
@mhinz I guess it would be for some people but it wouldn't be confusing for me. I just prefer everything to be very short.

Also instead of showing the full path of the `CWD`, if it is a environment variable, instead show `MRU $DOTFILES`?

**Comment by mhinz** [comment]
But it's missing the `/nvim` part. So you'd see:

```
MRU /usr/local/etc/dotfiles

[10]  $DOTFILES/init.vim
```
That's confusing, IMHO.

Apart from that, `$DOTFILES/init.vim` is basically an absolute path,  
so it feels wrong to show in the "dir" listing which is relative by nature.

Also consider someone trying to use a non-default topic. At the moment it's simply `'MRU '. getcwd()`. One would also have to expose the "unexpanded path" functionality somehow.

I like the feature for the "files" listing, but for "dir" it's a bit too much.

**Comment by mhinz** [comment]
That doesn't mean we can come up with other means of shorting paths, though. 

E.g. showing `nvim/plugged/foo/blah/file.ext` as `n/p/f/b/file.ext` under certain circumstances.

**Comment by nhooyr** [comment]
@mhinz I meant the top directory part, e.g. it says `MRU /usr/local/etc/dotfiles`. Instead if `foo=/usr/local/etc/dotfiles` then it could just say `MRU $foo`.

What do you mean non-default topic?

**Comment by mhinz** [comment]
Yeah, but I mean tthe case of `foo=/usr/local/etc/dotfiles/nvim`. That's when that weird formatting would arise.

> What do you mean non-default topic?

Actually I meant the section header:

```vim
  get(g:, 'startify_list_order', [
        \ ['   MRU'],            'files',
        \ ['   MRU '. getcwd()], 'dir',
        \ ['   Sessions'],       'sessions',
        \ ['   Bookmarks'],      'bookmarks',
        \ ])
```

**Comment by nhooyr** [comment]
O well, its not a big issue, thanks anyways.
