### ISSUE TITLE
Unable to get Cowsay header working.

### ISSUE THREAD

**Issue by yifanchen** [mhinz/vim-startify#200]
Nice vim plugin, I really like it. However, I can't get Cowsay header working, no error either. Any ideas?

**Comment by mhinz** [comment]
What exactly did you put in your vimrc?

**Comment by yifanchen** [comment]
```
let g:startify_custom_header =
          \ map(split(system('tips | cowsay -f apt'), '\n'), '"   ". v:val') + ['']``` 
I have the above lines of code in my `vimrc`. I think the problem is the `system()` shell? How can I make confirm that's the problem?

**Comment by mhinz** [comment]
Is `tips | cowsay -f apt` working in your shell? Probably not, since `tips` is a personal script of mine: https://github.com/mhinz/dotfiles/blob/master/bin/tips

What OS are you using?

**Comment by yifanchen** [comment]
osx, el cap. 
https://github.com/yifanchen/dotfiles/blob/master/.vimrc

**Comment by mhinz** [comment]
Assuming you're using homebrew, do `brew install fortune cowsay` and replace the `tips | cowsay -f apt` in your vimrc by `fortune | cowsay`.

**Comment by yifanchen** [comment]
yes, I use `brew` for most of things. I know I had it twice just because the `cowsay` header didn't work. Let me try to install `fortune cowsay`.

**Comment by yifanchen** [comment]
works, thanks for your help.

**Comment by mhinz** [comment]
You're welcome!
