### ISSUE TITLE
error when opening session with python file

### ISSUE THREAD

**Issue by kjyv** [mhinz/vim-startify#202]
When opening a session which has a python file in it which in turn enables jedi-vim, the following error appears. It does not appear when opening the same python file from the MRU list.

Error: jedi-vim failed to initialize Python: jedi-vim requires Vim with support for Python 2 or 3. (in function jedi#init_python[3]..<SNR>108_init_python, line 52)

**Comment by kjyv** [comment]
Sorry, for some reason my vim build was currently without python.

**Comment by mhinz** [comment]
:-)
