### ISSUE TITLE
incompatibility with tagbar?

### ISSUE THREAD

**Issue by nhooyr** [mhinz/vim-startify#203]
simple init.vim

```vim
call plug#begin('.')
Plug 'mhinz/vim-startify'
Plug 'nhooyr/tagbar'
call plug#end()
```

Run neovim with that init.vim and then immediately run `:TagbarToggle`. 

```
Error detected while processing function <SNR>29_QuitIfOnlyWindow[27]..<SNR>29_goto_win:
line    8:
E16: Invalid range: 2wincmd w
```

Setting
```vim 
let g:tagbar_autofocus = 1
```
Lets you open tagbar, but the same error when closing it.

**Comment by mhinz** [comment]
I don't see how this is an Startify issue, but I think this PR is related: https://github.com/majutsushi/tagbar/pull/311
