### ISSUE TITLE
How can I make the "custom_header" italic?

### ISSUE THREAD

**Issue by alexbooker** [mhinz/vim-startify#205]
Hi @mhinz :wave:. Awesome work on this plugin, I have just one question:

Is it possible to make the `g:startify_custom_header` italic somehow?

I tried:

```viml
let g:startify_custom_header = system('echo -e "\e[3mitalic\e[0m"')
```

... But Vim does not interpret the escape sequence properly:

![](http://i.imgur.com/uRafslG.png)

Just for the fun of it I tried `printf` but that didn't work either. 

Thanks!

**Comment by mhinz** [comment]
> Awesome work on this plugin

Thanks!

> Is it possible to make the g:startify_custom_header italic somehow?

See `:h startify-colors` for the regions you can customize. `:highlight` does not only allow setting colors, but also terminal attributes like `bold` or `italic`.

Try this:

```
:hi StartifyHeader
```

Note the values for `ctermfg` and `ctermbg`. Then set them again adding `cterm`:

```
:hi StartifyHeader ctermfg=XXX ctermbg=XXX cterm=italic
```

If it's not working after this, your font is either not supporting italic or your terminal emulator doesn't allow it.

**Comment by alexbooker** [comment]
@mhinz Spot on. Thank you :pray:
