### ISSUE TITLE
option to change the cow

### ISSUE THREAD

**Issue by nhooyr** [mhinz/vim-startify#207]
Cowsay lets you change the default cow to milk cartons, dragons, or eyes as below.

```
                                   .::!!!!!!!:.
  .!!!!!:.                        .:!!!!!!!!!!!!
  ~~~~!!!!!!.                 .:!!!!!!!!!UWWW$$$
      :$$NWX!!:           .:!!!!!!XUWW$$$$$$$$$P
      $$$$$##WX!:      .<!!!!UW$$$$"  $$$$$$$$#
      $$$$$  $$$UX   :!!UW$$$$$$$$$   4$$$$$*
      ^$$$B  $$$$\     $$$$$$$$$$$$   d$$R"
        "*$bd$$$$      '*$$$$$$$$$$$o+#"
             """"          """""""
```

It'd be nice to have a option in the startify cowsay implementation that does the same.

**Comment by mhinz** [comment]
I'm really reluctant to introduce yet another option. :) Startify has too many already.

But I can refactor `fortune.vim` a bit. I could basically 3 variants:

```
startify#fortune#quote()  =>  unformatted random quote
startify#fortune#boxed_quote()  => formatted random quote in a box
startify#fortune#cowsay_quote()  =>  the default
```

Afterwards you could simply use `g:startify_custom_header = startify#fortune#boxed_quote() + g:dragon_eyes`.

**Comment by nhooyr** [comment]
great.

**Comment by mhinz** [comment]
So, on latest master you can do:

```vim
let g:dragon_eyes = [
      \ '                                   .::!!!!!!!:.',
      \ '  .!!!!!:.                        .:!!!!!!!!!!!!',
      \ '  ~~~~!!!!!!.                 .:!!!!!!!!!UWWW$$$',
      \ '      :$$NWX!!:           .:!!!!!!XUWW$$$$$$$$$P',
      \ '      $$$$$##WX!:      .<!!!!UW$$$$"  $$$$$$$$#',
      \ '      $$$$$  $$$UX   :!!UW$$$$$$$$$   4$$$$$*',
      \ '      ^$$$B  $$$$/     $$$$$$$$$$$$   d$$R"',
      \ '        "*$bd$$$$      `*$$$$$$$$$$$o+#"',
      \ '             """"          """""""']

let g:startify_custom_header = map(startify#fortune#boxed() + g:dragon_eyes, '"   ".v:val')
```

The only "issue" I see, that always existed, is that `g:startify_custom_header` is only set once, so spamming `:Startify` will always get you the same quote. But I have an idea on how to handle that.

**Comment by nhooyr** [comment]
@mhinz Its always bothered me too, just not enough to create an issue. Perhaps if you set that variable to a function ref it is called? that would be simple and not require a new option.

Thanks though!

**Comment by mhinz** [comment]
Much easier! This is one of the rare situations, where `eval()` can be used for good.

On latest master, just make `g:startify_custom_header` a string instead of a list:

```vim
let g:startify_custom_header = 'map(startify#fortune#boxed() + g:dragon_eyes, "\"   \".v:val")'
```

**Comment by mhinz** [comment]
For the record: I added a small tutorial for dynamic headers to `:h g:startify_custom_header`.
