### ISSUE TITLE
cannot quit (g)vim by pressing 'q'

### ISSUE THREAD

**Issue by winsphinx** [mhinz/vim-startify#208]
At Staritify screen pressing 'q' or 'enter', cannot close vim.

**Comment by mhinz** [comment]
More infos needed.

When does it happen? After calling it manually with `:Startify` or right after start? Mind that `q` is meant to close the Startify buffer, not Vim. It just happens to also close Vim, if there's no other listed buffer.

**Comment by winsphinx** [comment]
When... Right after start, and if manually call :Startify, pressing 'q' will close the startift buffer, and leave other buffer(s)..

After some testing, i've found that's due to the config:

> autocmd User Startified setlocal buflisted

Comment this line, it works as before. Now I guess that a bug of vim itself.

**Comment by mhinz** [comment]
Could you see if the latest master is working correctly for you?

**Comment by wsdjeg** [comment]
I can not reproduce
1. nvim readme.md
2. Startify
3. type q .thank will close startify buffer ,and enter readme.md,I think there is no error,if now type `q` close vim itself,I think it is not right

**Comment by mhinz** [comment]
@wsdjeg I'm not sure I understand 3.

1. `nvim readme.md`
2. `:Startify`
3. Now `q` should only close the Startify buffer and return to the `readme.md` buffer, no matter the setting of `'buflisted'`.

`q` should only close Vim if there's no listed buffer left to switch to.

**Comment by wsdjeg** [comment]
yes,it is, the buffer opened before `Startify`,should not be closed when type q in Startify buffer.before you push `41b5338`,I just works well,and I have not test for `41b5338`

**Comment by mhinz** [comment]
Are you sure the buffer before calling `:Startify` isn't set to `'nobuflisted'`?

Just to be sure.. is this working for you?

1. `nvim readme.md`
2. `:set buflisted`
3. `:Startify`
4. `q` returns to `readme.md`

**Comment by winsphinx** [comment]
Perfect job! Thanks!

**Comment by wsdjeg** [comment]
>    nvim readme.md
    :set buflisted
    :Startify
    q returns to readme.md

this step works well for me .I can use q go back to readme.md.
BTW, I am using neovim latest version,and startify commit log is here
![2016-03-17 20-26-53](https://cloud.githubusercontent.com/assets/13142418/13845967/9fa47a30-ec7e-11e5-81ce-c26dcde34d3f.png)

**Comment by mhinz** [comment]
Ehm, you commit log doesn't even include `41b5338`?

**Comment by wsdjeg** [comment]
yes,I updated yesterday

**Comment by mhinz** [comment]
@wsdjeg You're confusing me. If you have problems with the _latest_ master, tell me on IRC, please.

@winsphinx Thanks for raising this issue!

**Comment by wsdjeg** [comment]
I am sorry,I will test for this latest version.
