### ISSUE TITLE
Alter list of recent files

### ISSUE THREAD

**Issue by lervag** [mhinz/vim-startify#209]
I am curious if it is possible to alter the list of recent files. In particular, I want to substitute the beginning of paths with the path to a symlink in my home folder, e.g. something like:

```
/some/path/to/doc/file -> ~/doc/file
```

Here `~/doc` is a symlink to `/some/path/to/doc`. I notice that Vim stores the paths with the actual paths, not the symlinked paths.

**Comment by mhinz** [comment]
Yea, Startify resolves all symlinks to avoid duplicates and for proper file matching etc.

If your intention is to get shorter displayed paths, I pushed a new option ~2 weeks ago. See `:h g:startify_use_env`. Afterwards you could put `export DOCS=/some/path/to/doc` and your entry would be shown as `[1]  $DOCS/file`.

Does this help you?

**Comment by lervag** [comment]
Yes, it sort of helps. But It is not quite as smooth.

Would it not be possible to add a hook so that I can apply a custom map to the list before it is printed?

**Comment by mhinz** [comment]
I silently pushed a new feature that I call "transformations". It let's you transform the _displayed_ path, of any matched file, to whatever you want. This is done for all entries but sessions. (Not documented yet.)

:arrow_right:  [screenshot](http://imgur.com/LXrB6Tn)

It's a quite general feature that's supposed to make Startify future-proof. Since it has to explicitly done in the vimrc, it still might not be the solution you're looking for, though.

**Comment by lervag** [comment]
Thanks, that looks like an interesting solution! It seems to be very close to what I want. However, it seems I have to manually add every single file explicitly.

I would think that it should be possible to use the same idea but allow patterns on the "left hand side". Instead of checking if an absolute path is a key, you could check if the path matches any keys, in which case the transformation could e applied.

**Comment by mhinz** [comment]
And that's the exact reason why I haven't documented it yet. :]

I agree that a pattern would be more useful (and could even replace options like `g:startify_relative_path`), although then we lose the advantage of having O(1) access which was the whole point of using a dictionary in the first place.

We basically need a list of lists then.

```vim
let g:startify_transformations = [
  \ [ '.*foo.*', 'alias'],
  \ [ '.*bar.*', function('do_what_i_want') ],
  \ ]
```

But it's probably worth the cost. I'll just add a little warning to the docs about this potential drawback.

**Comment by lervag** [comment]
You could allow both the pattern approach and the current O(1) approach, if you used a separate option for the patterns. In that case, you could still use a dictionary, where the keys are patterns and the values are targets/filters.

In any case, I don't think that this will lead to a noticable delay, at least not if one does not have any patterns.

**Comment by mhinz** [comment]
> if you used a separate option for the patterns

At this point we have 25 options already, so I'm reluctant to add even a single one. ;] In hindsight I'm not happy with every option, but breaking backward-compatibility would be even worse.

And sure, a single option doesn't have much of an impact performance-wise, but other options take a similar approach and stuff just piles up. Nevertheless, it will never be a problem as long as people don't throw hundreds of complicated patterns into it. :-)

I'm busy today but will make the change some time this weekend.

**Comment by lervag** [comment]
I can relate to not wanting more options.

But: Why do we need a list of lists? Every sublist has two elements, and so it should still work using a dictionary where the keys can be both patterns and atomic entries. One possibility is to use something like:

```vim
let g:my_opt = {
	\ 'path' : '...',
	\ 're:pattern' : '...',
	\}
```

In any case, I think whichever solution you choose will be fine. And I agree, I think this option could replace more than just the `g:startify_relative_path`. It could also, at least in principle, replace the `g:startify_use_env` option.

**Comment by mhinz** [comment]
The problem is that dictionary don't keep order, but that's pretty important in this case, so more general patterns can be put at the bottom. E.g.

```vim
function! s:foo(filename)
  return fnamemodify(a:filename, ':t')
endfunction

let g:startify_transformations = [
      \ ['.*vimrc$', 'vimrc'],
      \ ['.*', function('s:foo')],
      \ ]
```

**Comment by lervag** [comment]
It is working very well! It solves my issue and then some. Thanks!

**Comment by mhinz** [comment]
Thank you for the valuable feedback!
