### ISSUE TITLE
Disable Cowsay header

### ISSUE THREAD

**Issue by Konfekt** [mhinz/vim-startify#210]
How to disable the Cowsay Header? 
The naive try

let g:startify_custom_header =[] 

adds an empty line.

**Comment by mhinz** [comment]
Thanks for mentioning!

**Comment by joenye** [comment]
Note that let `g:startify_custom_header =['']` still adds an empty line. You have to put `let g:startify_custom_header =[]`

**Comment by mhinz** [comment]
@joenye 

It's documented that way under `:h g:startify_custom_header` (_"Every string will be written on its own line, hence you can use empty strings for blank lines."_) and `:h startify-faq-13`.
