### ISSUE TITLE
Feature Request: Option to disable start screen.

### ISSUE THREAD

**Issue by still-dreaming-1** [mhinz/vim-startify#211]
I only use startify to automatically load and save to my Session.vim files. It would be nice to have an option to disable the start screen. For me personally, I don't find the start screen helpful. Actually it gets in the way when I open a buffer from NERDTree and then the startify buffer is still open. I'm sure there is a way to get around that, but it would be nice to have this option. I have tried setting `g:startify_disable_at_vimenter`, but that also disables the session management stuff I use.

**Comment by mhinz** [comment]
What exactly isn't working? Setting `g:startify_disable_at_vimenter` should really just disable immediately  executing `:Startify` after starting up. All other commands (`:SL` and friends) and options should work as usual.

**Comment by still-dreaming-1** [comment]
@mhinz Interesting. It is not loading the Session.vim file located in the current directory. Or at least it does not open the buffers from that session. These are my startify options:

```
let g:startify_session_autoload= 1
let g:startify_session_delete_buffers= 1
let g:startify_session_persistence= 1
let g:startify_disable_at_vimenter= 1
```

I have confirmed that if I remove that last line, it will load my last session and skip the start screen. That is good, but I want it to do the same thing when that option is on.

**Comment by mhinz** [comment]
Please update and see if it's working for you now.

**Comment by still-dreaming-1** [comment]
@mhinz It's working now. Thanks!

**Comment by mhinz** [comment]
Splendid, thanks for bringing it up!
