### ISSUE TITLE
q key not work correctly when integrate with Goyo.vim

### ISSUE THREAD

**Issue by letientai299** [mhinz/vim-startify#216]
I try to make the start page centered using [vim-goyo](https://github.com/junegunn/goyo.vim). Here my attemp:

```vim
" ~/.vim/after/ftplugin/startify.vim
set nospell
Goyo
au BufLeave <buffer> Goyo
```

Everything works well, except the `q` key. I have to press `q` triple times to quit vim. 

FYI, I have added the following code to ensure that `:q` always quit the current buffer  (copied from [Goyo-wiki](https://github.com/junegunn/goyo.vim/wiki/Customization))

```vim
" ~/.vim/plugin/goyo_custom.vim
function! s:goyo_enter()
  let b:quitting = 0
  let b:quitting_bang = 0
  autocmd QuitPre <buffer> let b:quitting = 1
  cabbrev <buffer> q! let b:quitting_bang = 1 <bar> q!
endfunction

function! s:goyo_leave()
  " Quit Vim if this is the only remaining buffer
  if b:quitting && len(filter(range(1, bufnr('$')), 'buflisted(v:val)')) == 1
    if b:quitting_bang
      qa!
    else
      qa
    endif
  endif
endfunction

autocmd! User GoyoEnter call <SID>goyo_enter()
autocmd! User GoyoLeave call <SID>goyo_leave()
```

**Comment by mhinz** [comment]
Since this is not an issue in Startify, I close this.

Anyway, here's why it happens: The Startify buffer is _not_ a listed buffer, that's why the comparison against `1` in `s:goyo_leave()` won't be true. Try using `<= 1` instead.

(Feel free to ask further questions, if this doesn't work out in other cases!)

**Comment by letientai299** [comment]
Thank you very much. 
Apply your suggestion, and it works like a charm.

**Comment by Konfekt** [comment]
Perhaps it deserves a new issue, but the FAQ entry about starting Startify on every tabpage has to take `Goyo` into account, like this
```vim
  autocmd BufWinEnter *
        \ if !exists('t:startify_new_tab') &&
        \ empty(expand('%')) && empty(&l:buftype) && &l:modifiable &&
        \ !exists('t:goyo_master') |
        \   let t:startify_new_tab = 1 |
        \   Startify |
        \ endif
```
Otherwise, `:Goyo` will throw a slew of errors.

Maybe there are incompatibilities with other plug-ins that should be listed in a wiki?

**Comment by Konfekt** [comment]
Yes, the additional checks
```vim
empty(&l:buftype) && &l:modifiable
```
make it compatible with the built-in manpager plug-in.
