### ISSUE TITLE
g:startify_update_oldfiles off by default

### ISSUE THREAD

**Issue by jm3** [mhinz/vim-startify#217]
I use Startify all day, and the missing files in the recent files list confused me until I discovered the `g:startify_update_oldfiles` option. Any reason why `g:startify_update_oldfiles` should not be on by default? I can't think of any reason why you would want to see a list of "recent" files WITHOUT the most recently modified ones, which I think is what the default behavior does. *I also notice also that you have that option enabled by default in your configs, like i do :)*

Maybe, instead of  `g:startify_update_oldfiles`, a name like `g:startify_auto_update` would be more intuitive, to signal that the list will auto-update when enabled?  The "update oldfiles" name was unclear to me when I was searching the docs for how to make recent files show *all* recent files automatically.

I could submit a tiny PR for this if you think it's a good idea. And thanks for making Startify!

**Comment by mhinz** [comment]
I'd like to enable it by default, but unfortunately that doesn't play well with some [other plugins](https://github.com/mhinz/vim-startify/pull/192).

And yes, that option name would be better, but no use in renaming it at this point. :)

Thanks for bringing it up anyway!
