### ISSUE TITLE
Sort sessions by modification time

### ISSUE THREAD

**Issue by noscript** [mhinz/vim-startify#221]
I really miss having sessions sorted by time, the same way as the `"dir"` list. Would it be possible to add such option?

**Comment by mhinz** [comment]
That's certainly possible. I'll add an option for this.

**Comment by mhinz** [comment]
Done!

Put this in your vimrc:

```vim
let g:startify_session_sort = 1
```

**Comment by noscript** [comment]
Wow, thank you!

**Comment by mhinz** [comment]
You're welcome!
