### ISSUE TITLE
Feature request: option to run commands before saving session

### ISSUE THREAD

**Issue by a-m-s** [mhinz/vim-startify#222]
I'd like to be able to do something like this:

```
let g:startify_session_presavecmds = ['NERDTreeTabsClose']
```

Right now, I can do this manually, before `SSave`, of course, and I can set `autocmd VimLeave * NERDTreeTabsClose` in my `.vimrc` to catch the persistent session case, but it would be nice if there were an official way to do it.

**Comment by mhinz** [comment]
Implemented as `g:startify_session_before_save`.

Thanks for bringing this up, seems like a useful addition.
