### ISSUE TITLE
Frequently unable to open saved sessions.

### ISSUE THREAD

**Issue by MeanEYE** [mhinz/vim-startify#227]
![screenshot from 2016-06-08 12-34-05](https://cloud.githubusercontent.com/assets/1911594/15889810/4dc37904-2d75-11e6-9c9d-0a3b37c41918.png)
As seen on image above Startify complains about opening saved session tool itself listed. This problem doesn't occur all the time. It seems it might have something to do with spaces but it's not always reproducible.

**Comment by mhinz** [comment]
Yup, I escaped paths one time too often. It should work now!

**Comment by MeanEYE** [comment]
Thanks. Works now.

**Comment by mhinz** [comment]
Thanks for letting me know!
