### ISSUE TITLE
The background of directory path is white

### ISSUE THREAD

**Issue by chengshiding** [mhinz/vim-startify#228]
![qq 20160612163303](https://cloud.githubusercontent.com/assets/1284476/15990022/722d6572-30bb-11e6-96d9-3b947cf00ea2.png)

How changes the background so that it looks like.
Thinks!

**Comment by mhinz** [comment]
Hi,

have a look at `:h startify-colors`. In your case, the highlight group is called `StartifyPath`.

For example, put this in your config:

```vim
highlight StartifyPath ctermfg=blue ctermbg=NONE cterm=NONE
```

**Comment by chengshiding** [comment]
Good, thanks
