### ISSUE TITLE
Config to open file without change current path

### ISSUE THREAD

**Issue by chengshiding** [mhinz/vim-startify#229]
In my case, I map leader r to run shell make commad. But open a file by using vim-startify, the current path of vim is changed, So I cannot run make's mapkey.
          nnoremap <leader>r :!make<CR>
lookupfile which is a plugin of vim also not change path when open a file.
So, I hope you could add a configure with Whether open file with whether changing the path.
Thanks!

**Comment by mhinz** [comment]
`let g:startify_change_to_dir = 0`

**Comment by chengshiding** [comment]
Yeah, thanks!
