### ISSUE TITLE
Error detected while processing function startify#open_buffers[8]

### ISSUE THREAD

**Issue by durgaswaroop** [mhinz/vim-startify#230]
I keep getting this error when I try to open `.vim` files in the bundle directory from the Startify front page.

The full error is, 
`Error detected while processing function startify#open_buffers[8] ..<SNR>61_open_buffer[14]..<SNR>61_check_user_options: 
line    8: E344: Can't find directory "C:\Program\ Files\Vim\vimfiles\bundle\vim-mpc\autoload" in cdpath E472: Command failed`

I don't get this error for any other filetypes or even for .vim files located somewhere else.
I am using Gvim 7.4 on windows 7. 
![startfiyerror](https://cloud.githubusercontent.com/assets/8543652/16378673/c66a5156-3c8a-11e6-8865-960eda610c42.PNG)

**Comment by mhinz** [comment]
Is `C:\Program\ Files\Vim\vimfiles\bundle\vim-mpc\autoload` a correct path?

**Comment by durgaswaroop** [comment]
Yes. It is a valid path and the file exists. The file is opened just fine after I press ENTER when i get this error. But it still shows that error for some reason.

**Comment by mhinz** [comment]
Yea, the problem is that the `:cd` command fails. Unfortuantely I don't have a Windows VM for testing around. I try to come up with a solution anyway.

**Comment by durgaswaroop** [comment]
Ok Thanks. Is there anything that I can do temporarily to fix this issue? 
Mean while if there is some setting or some function that I can tweak to make it work at least temporarily, do let me know.

**Comment by mhinz** [comment]
If you don't need the "directory switching" feature, disable it like this:

```vim
let g:startify_change_to_dir = 0
```

**Comment by mhinz** [comment]
Please update the plugin and see if it works now. Without `g:startify_change_to_dir = 0`, of course. :-)

**Comment by durgaswaroop** [comment]
Yes. Its working now. :+1: Thanks .

**Comment by mhinz** [comment]
Awesome, thanks for bringing it up!
