### ISSUE TITLE
Is any option to disable save open buffers in session

### ISSUE THREAD

**Issue by JunfengJia** [mhinz/vim-startify#232]
The session's opened buffers will be huge after long time use.

keep opened window and tabs is enough for me.

**Comment by mhinz** [comment]
Startify doesn't handle how sessions behave. See `:h 'sessionoptions'`.

You could try putting this in your vimrc:

```vim
set sessionoptions-=buffers
```

**Comment by JunfengJia** [comment]
Great!

**Comment by mhinz** [comment]
:)
