### ISSUE TITLE
Line numbers for bookmarks?

### ISSUE THREAD

**Issue by for-coursera** [mhinz/vim-startify#235]
As far as I understand, vim-startify doesn't support line numbers for bookmarks? Like `'~/.vimrc:22'` or anything like that?

Is it possible to add that functionality somehow?

**Comment by mhinz** [comment]
Nope, that's not really the task of this plugin. :-)

Two possible solutions come to my mind:

**1)**

Use the _command_ list instead of the _bookmark_ list. E.g.

```vim
let g:startify_commands = [
      \ ['my zshrc', 'edit +22 ~/.zsh/.zshrc' ]
      \ ]
```

See `:h g:startify_commands`.

**2)**

```vim
let g:startify_bookmarks = [ '~/.zsh/.zshrc' ]
autocmd BufRead ~/.zsh/.zshrc 22
```

**Comment by for-coursera** [comment]
Not plugin's task to understand Vim's native syntax? oook.
