### ISSUE TITLE
Error when opening file with space(s) in name

### ISSUE THREAD

**Issue by Asheq** [mhinz/vim-startify#239]
When opening a file with a space in the name (e.g. "This File Has Spaces.txt"), the following error displays:

![image](https://cloud.githubusercontent.com/assets/4657140/19294421/4f848fc0-8fe1-11e6-8255-c94475be1b7c.png)

The file still opens, but it would be nice not having this annoying error show up (which, as you can see, requires pressing the enter key to continue).

**My Vim Info**
 VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jun 27 2016 22:06:17)
 MS-Windows 64-bit GUI version with OLE support
 Included patches: 1-1965
 Compiled by hp@HP-PC

**Comment by mhinz** [comment]
There was a similar problem a few months ago, so I have to ask: are you using the latest version of the plugin?

I can't reproduce it on OSX, but it might be related to Windows, so I'll get a Win 10 tablet later today and check again.

**Comment by mhinz** [comment]
Okay, I can reproduce it with Vim 8.0 in Git Bash.

**Comment by mhinz** [comment]
It should work now!

**Comment by Asheq** [comment]
Great, works for me now. Thanks for the speedy resolution!

**Comment by mhinz** [comment]
Thank you for bringing it up!
