### ISSUE TITLE
Supress unncesessary error

### ISSUE THREAD

**Issue by meain** [mhinz/vim-startify#240]
If I try to open a startify window in the same split which already has a startify window, it throws this error:

![error](http://i.imgur.com/iJI5pop.png)

Now if I press enter, it brings up startify without any syntax highlighting.
Maybe we could just suppress the error message and not do nothing?

**Comment by mhinz** [comment]
What are the exact commands to provoke this error?

**Comment by meain** [comment]
In the new update it it line `115`. 
And a bit more to add, it happens only if I have more than one split open with startify on them. Now if use `:Startify` it shows this error on any of those, it shows this error.

**Comment by mhinz** [comment]
Ah, I can reproduce that.

**Comment by meain** [comment]
That was pretty quick, thanks.

**Comment by mhinz** [comment]
Thanks for bringing this up. The error itself is now properly silenced.

But I noticed a different problem:

```
:Startify
:vsplit
:Startify
:wincmd p
```

If the entries start at different heights now (because of dynamic quotes for example), the first Startify buffer will throw weird problems, since the entries are kind of global and the second Startify buffer overwrote them..

Anyway, I'll look into that, too.

Thanks!

**Comment by meain** [comment]
Yup, on selecting any option it just removes any kind of highlighting and gets stuck in there without going to the file. Oops, the fix created a bigger mess.

**Comment by mhinz** [comment]
Could you please update and see if there are still problems for you?

**Comment by mhinz** [comment]
Argh, I forgot one important variable.

**Comment by mhinz** [comment]
Could you please update and see if there are still problems for you?

**Comment by meain** [comment]
Everything is working fine now. Thanks!

**Comment by mhinz** [comment]
Awesome. Thanks for bringing up the original issue and the consecutive feedback!

**Comment by meain** [comment]
Sure, thanks for the great plugin!
