### ISSUE TITLE
g:startify_update_oldfiles = 1 should still skip empty v:oldfiles entries

### ISSUE THREAD

**Issue by Konfekt** [mhinz/vim-startify#242]
With
```vim
let g:startify_update_oldfiles = 1
let g:startify_update_oldfiles= 1
```
:Startify causes in  [0] = last file (OK!) and [1] = dir of [0] (BAD!) because `v:oldfiles[0] = ''`.

**Comment by mhinz** [comment]
Did you mean to paste two different options? :-)

At least with only `g:startify_update_oldfiles = 1` I can't seem to reproduce it. (As in, empty entries actually get skipped.)

**Comment by Konfekt** [comment]
Oops, of course. Sorry for the wrong paste. Unsafe was meant. 

Even though it's unsafe, at least empty entries should be skipped.

**Comment by mhinz** [comment]
Hmm, actually empty entries get skipped already. But this only happens in the `dir` list (recent files in current directory), not in the `files` list (recent files), right?

The problem I see is that with unsafe set, even directories get added to the lists. This is the root problem, as they should contain files only. I can probably filter them by checking if the last character is a path separator.

Apart from that, directories are shown correctly -- except in one case! If the entry describe the current working directory.

This probably gets you an empty output:

```vim
:echo fnamemodify(getcwd . '/', ':.')
```

Do you agree with filtering all directories instead?

**Comment by Konfekt** [comment]
I agree. And, Yes, they are only shown in the upper half, 0-9, of the Startify screen.

**Comment by mhinz** [comment]
So, is it still happening with the latest commit?

**Comment by Konfekt** [comment]
Works perfectly, Thanks!
