### ISSUE TITLE
Get current session name.

### ISSUE THREAD

**Issue by MeanEYE** [mhinz/vim-startify#244]
It would be nice to have equivalent of `fugitive#head()` function to call. This would make it possible to include session name inside of `rulerformat` or custom status line.

For example, my current `rulerformat` looks like this:
```
set rulerformat=%40(%=%{fugitive#head()}\ %Y\ %P%)
```
![screenshot from 2016-11-06 17-14-30](https://cloud.githubusercontent.com/assets/1911594/20039452/7fbe0186-a444-11e6-96d4-00728e6fc83d.png)

**Comment by mhinz** [comment]
You could simply use `:h v:this_session`, unless I missed the point. :)

**Comment by MeanEYE** [comment]
That sort of works. Is there a way to just get the file name? `expand` doesn't seem to work.

**Comment by mhinz** [comment]
`fnamemodify(v:this_session, ':t')`

**Comment by MeanEYE** [comment]
Yup, this works. Thanks. Slight modification is needed though: `%{fnamemodify(this_session,':t')}`. Had to remove v: and space. Just in case someone else runs into same desires.
