### ISSUE TITLE
Startify custom indices is delayed when pressing certain keys

### ISSUE THREAD

**Issue by natebass** [mhinz/vim-startify#246]
My startify_custom_indices is ['f', 'd', 's', 'a']. When I press f or d it waits for timeoutlen before opening the file. I am wondering why it only does this for f and d, not s or a? Is there a way to fix this besides setting timeoutlen to a small number? I want to avoid [this](https://github.com/mhinz/vim-startify/issues/236) problem.

**Comment by mhinz** [comment]
You most probably have other mappings that start with `f` or `d`, but none that start with `s` or `a`. Check `:verb nmap f` etc.

See if enabling `:h g:startify_mapping_nowait` works for you.

**Comment by natebass** [comment]
```vim
let g:startify_mapping_nowait=1
```
Yes, this fixes the problem.

**Comment by mhinz** [comment]
Great!
