### ISSUE TITLE
Make startify_mapping_nowait default

### ISSUE THREAD

**Issue by natebass** [mhinz/vim-startify#247]
```let g:startify_mapping_nowait=1``` should be default so that global mappings do not interfere with startify mappings. As stated https://github.com/mhinz/vim-startify/issues/246, I am still able to type 12, 13, etc. without immediately jumping to 1.

I am using NVIM 0.1.6

**Comment by natebass** [comment]
In VIM 7.4, and it still has the problem. It jumps to 1 before I can type 12

**Comment by mhinz** [comment]
> In VIM 7.4, and it still has the problem.

Even with `g:startify_mapping_nowait = 1`?

**Comment by natebass** [comment]
Sorry nvm! I seems to wait timeoutlen as it should.

**Comment by mhinz** [comment]
Right, I just compiled 7.4.100 and it seems to work there as well.

**Comment by mhinz** [comment]
Done, thanks for the feedback!
