### ISSUE TITLE
default g:startify_mapping_nowait value to 1 prevents use of key mappings above 9

### ISSUE THREAD

**Issue by enricobacis** [mhinz/vim-startify#252]
Commit df32cef08b4376ffcbf09f7b8e5bf1bfc2a0bf24 makes `g:startify_mapping_nowait` default to `1`.

I'm using vim 8.0 and this prevents me from using mappings assigned to number above 9. When I set it back to 0 everything works as expected. I would consider reverting the change or have a workaround.

**Comment by mhinz** [comment]
Could you please test if it still happens on master?

As far as I see it, the `<nowait>` isn't the problem per-se, the mapping order is. Looping over a dictionary in VimL doesn't guarantee an order (which I thought was okay), but it isn't if `<nowait>` is used as well.

**Comment by enricobacis** [comment]
I confirm it is working now. Thank you

**Comment by mhinz** [comment]
Splendid. Can't believe there was such a bug in Startify all the time. :\

Thanks for bringing this up (again)!
