### ISSUE TITLE
Custom bookmark conflict with 'q' key

### ISSUE THREAD

**Issue by ar1xwe** [mhinz/vim-startify#255]
In my _vimrc, I've adjust 

`let g:startify_enable_special = 0`

and one custom bookmark,

`let g:startify_bookmarks = [ {'q' : '~\foo\bar.ahk' } ]`

but the 'q' key keep quits vim.

I've already search/read all closed issues and the document of startify, but I still can not understand how to disable the 'q' key's behavior.

**Comment by mhinz** [comment]
You can't. See the note at the bottom of `:h g:startify_bookmarks`.
