### ISSUE TITLE
Fortune: Alan Perlis

### ISSUE THREAD

**Issue by Alok** [mhinz/vim-startify#256]
>  Like punning, programming is a play on words.

http://www.cs.yale.edu/homes/perlis-alan/quotes.html

In my opinion, the most quotable man in computer science.

**Comment by natebass** [comment]
> 120. Adapting old programs to fit new machines usually means adapting new machines to behave like old ones.

Sounds like vim in a terminal emulator. :laughing:

**Comment by mhinz** [comment]
> Sounds like vim in a terminal emulator.

Hah!

@Alok Thanks! Really good quotes

I added a handful of the shorter and general ones that serve as good advice and are hopefully understood by everyone.

**Comment by Alok** [comment]
Rob pike's 5 rules are also good, especially the one about data structures.
