### ISSUE TITLE
Startify append text after current buffer.

### ISSUE THREAD

**Issue by wsdjeg** [mhinz/vim-startify#257]
test with tagbar openned:

before `Startify` command:
![2016-12-26-23 38 46](https://cloud.githubusercontent.com/assets/13142418/21483879/a202e0b6-cbc4-11e6-8cc3-bf789641fe99.png)
in nvim, after `Startify` command I see:
![2016-12-26-23 38 52](https://cloud.githubusercontent.com/assets/13142418/21483977/2694b8da-cbc6-11e6-9035-182c5e053cd8.png)

I think it should be a bug.

but in vim it is, and has no bug.
![2016-12-26-23 41 03](https://cloud.githubusercontent.com/assets/13142418/21483976/26948d6a-cbc6-11e6-9edc-4e4f62bbf6bf.png)

**Comment by mhinz** [comment]
I would argue it's more an issue with tagbar than with Startify, but it's easy enough to prevent from Startify, so I added a `:noautocmd`.

**Comment by wsdjeg** [comment]
@mhinz thanks, it works well now.
