### ISSUE TITLE
Wrong filename by echo @% command when the file was open with startify

### ISSUE THREAD

**Issue by monkoose** [mhinz/vim-startify#258]
Here is the problem, when i have `let g:startify_change_to_dir = 0` option in my vimrc(actually in neovim's init file), and when i open a file from startify startpage `:echo @%' command returns full path to the file. Maybe i missed some other option to disable/enable?
Example:
```
:pwd or echo getcwd()
>>> /home/user
:echo @%
>>> /home/user/.config/somefile.txt
```

Expected to return path related to the current working directory.
Example:
```
:pwd or echo getcwd()
>>> /home/user
:echo @%
>>>  .config/somefile.txt
```

**Comment by mhinz** [comment]
Hmm, I can't reproduce that. It shows just `.config/somefile.txt` for me, as expected. The working directory is never tempered with, if `g:startify_change_to_dir = 0`. 

What's the output of `:echo getcwd() @%` after opening a file from Startify?

Maybe another plugin is interfering? It might be worth to check `:verb au BufEnter`.

**Comment by monkoose** [comment]
Let me check. I didn't completely check this problem. Because i just opened file with startify and without and recived different results as i described early. Thank you for some advises, going to try them now and will respond after that.

**Comment by monkoose** [comment]
`:echo getcwd() @%` returns `/home/user /home/user/.config/somefile.txt`

And here is output of `:verb au BufEnter`
```
--- Auto-Commands ---
filetypedetect  BufEnter
    *.xpm     if getline(1) =~ "XPM2" |   setf xpm2 | else |   setf xpm | endif
	Last set from /usr/share/nvim/runtime/filetype.vim
    *.xpm2    setf xpm2
	Last set from /usr/share/nvim/runtime/filetype.vim
delimitMate  BufEnter
    *         if !exists('b:delimitMate_was_here') |   call <SID>setup() |   let b:delimitMate_was_here = 1 | endif
	Last set from ~/.local/share/nvim/site/dein/.cache/init.vim/.dein/plugin/delimitMate.vim
gitgutter  BufEnter
    *         if gettabvar(tabpagenr(), 'gitgutter_didtabenter') |   call settabvar(tabpagenr(), 'gitgutter_didtabenter', 0) | else |   call gitgutter#process_buffer(bufnr(''), 0) | endif
	Last set from ~/.local/share/nvim/site/dein/.cache/init.vim/.dein/plugin/gitgutter.vim
FileExplorer  BufEnter
    *         sil call s:LocalBrowse(expand("<amatch>"))
	Last set from /usr/share/nvim/runtime/plugin/netrwPlugin.vim
```
I don't any suspicious commd. You?

**Comment by monkoose** [comment]
Rechecked. Disable all plugins and except plugin manager and startify + disable all my options and `:echo getcwd() @%` still returns `/home/user /home/user/.config/somefile.txt`

Neovim compability issue?

**Comment by mhinz** [comment]
Hmm, I tested with Neovim master as well, same result. Technically, if you choose an entry by index or `<cr>`, Startify simply does `:edit /home/user/.config/somefile.txt` (check `:StartifyDebug`).

So, do you have the same behaviour with this?

```
$ cd
$ nvim
:edit .config/somefile.txt
:echo @%
```

**Comment by monkoose** [comment]
Yes. Didn't disable `g:startify_change_to_dir = 0`
And yes `:edit` with full path output same result as file opened with startify. So there is some problem.
Hm, so why you don't have this problem. I don't get it.

**Comment by mhinz** [comment]
Hm, maybe it's a platform thing. I'm on OSX. Are you on Linux by any chance?

**Comment by monkoose** [comment]
@mhinz yes, im on linux. 
So can we keep this open so maybe some linux + neovim user can confirm or negate the issue?

**Comment by mhinz** [comment]
Current status: I played around with `vim -u NORC` and I'm pretty sure that showing an absolute path is correct when using `:e ~/.config/somefile` and a relative path is corret when using `:e .config/somefile`. So just how Vim works.

Interestingly I only get a relative path in both cases, when I have my own plugin vim-signify enabled. I'll take a closer look now.

**Comment by mhinz** [comment]
An easy way to reproduce it:

```
$ nvim -u NORC
:cd
:edit ~/.config/somefile.txt
" absolute path
:echo @%
:cd .config
:cd -
" relative path
:echo @%
```

**Comment by mhinz** [comment]
See https://github.com/neovim/neovim/pull/5845

**Comment by monkoose** [comment]
So, mine neovim+startify behavior is right(as it should be)? 
Is it hard(even possible) to make that when you inside some dir and open file under MRU THIS DIR that it opens not with full path. Sorry bad english, dunno how to describe properly. Like if you open MRU files it will `:edit "fullpathhere"`, but when you open MRU THIS DIR it will execute `:edit "relativepath"`?

**Comment by monkoose** [comment]
Yes we can close it if this is not startify problem.
But what's about your pull request to neovim. I think `@%` should return relative path. Maybe i made you think wrong or something.

**Comment by mhinz** [comment]
Yea, well, obviously that's a subjective topic. Personally I'd prefer it to always show absolute paths, because they're exact. ;-) But yeah, as long as it's consistent, I'll accept relative paths as well.

**Comment by monkoose** [comment]
Just for conclusion i don't know why `@%` isn't always return relative path. Bug or i read doc wrong, but there is `expand('%:.')` that seems always return right relative path.

**Comment by mhinz** [comment]
Oh, I didn't know you needed it for scripting purposes.

Yes, `expand('%:.')` or, if you have an absolute filename in a variable already, `fnamemodify(var, ':.')`.
