### ISSUE TITLE
Please allow users to choose whether to ignore eXtra session files

### ISSUE THREAD

**Issue by nkmathew** [mhinz/vim-startify#259]
I have a session file ending with an 'x' for a main side project which is not being displayed in the Startify session list as per the fix for issue #179.

I don't really use eXtra session files and would like to have all the sessions in the `~/.vim/session` folder to be displayed in the Starify session list regardless of the naming. Maybe add an option `g:startify_extra_sessions`?

**Comment by mhinz** [comment]
So, you have a session called `foox.vim`, but no accompanying session `foo.vim`, right?

**Comment by nkmathew** [comment]
Yes, `foox.vim` is being filtered

**Comment by mhinz** [comment]
But I mean would it be okay to filter `foox.vim` unless there's no `foo.vim` as well?

**Comment by nkmathew** [comment]
Yeah that's fine. Doubt I'd have two projects differing by a single character

**Comment by mhinz** [comment]
Okay, should work now!
