### ISSUE TITLE
My session files aren't showing up in order

### ISSUE THREAD

**Issue by nkmathew** [mhinz/vim-startify#260]
I have `g:startify_session_sort` set to `1` but my most recently written session doesn't show up at the top. I'm thinking it's probably due to the comparison in the sort function. The documentation for `sort()` has the comparison example as:

```vim
function MyCompare(i1, i2)
   return a:i1 == a:i2 ? 0 : a:i1 > a:i2 ? 1 : -1
endfunction
let sortedlist = sort(mylist, "MyCompare")

```
The one in autoload is:

```vim
function! s:sort_by_mtime(foo, bar)
  return getftime(a:foo) <= getftime(a:bar)
endfunction
call sort(sfiles, 's:sort_by_mtime')

```

Maybe the comparison has to be three-way? Because the first one works for me.
I haven't seen a similar issue on this, so I could be completely mistaken

**Comment by mhinz** [comment]
Well, it should be highly unlikely that two sessions have the same mtime. Can you reliably reproduce this?

Is this simple example working for you?

```
$ nvim
:SS foo
:SS bar
:Startify
(order: bar, foo)
:SS bar
(overwrite session)
:Startify
(order: bar, foo)
:SS foo
(overwrite session)
:Startify
(order: foo, bar)
```

**Comment by nkmathew** [comment]
Not really, the order stays foo, bar throughout and it doesn't appear at the top - foo and bar are the 2nd and 3rd last entries in the list. Maybe it's because you're using neovim?

**Comment by mhinz** [comment]
Could you please `git pull && git checkout fix-session-order`? It uses the 3-way comparison.

**Comment by nkmathew** [comment]
Sorts them from oldest to newest. I think the operator should be `<`

```vim
return foo == bar ? 0 : (foo < bar ? 1 : -1)
```

**Comment by mhinz** [comment]
Oh, of course. We want the biggers numbers first.. *cough* I merged the corrected version into master directly.

Thanks for bringing this up!
