### ISSUE TITLE
An empty dialog box on the right?

### ISSUE THREAD

**Issue by haifengkao** [mhinz/vim-startify#261]
![2017-01-10 1 22 10](https://cloud.githubusercontent.com/assets/4080524/21794716/d3ddbf2e-d737-11e6-92a4-3f0d3adf5382.jpg)

I noticed https://github.com/mhinz/vim-startify/commit/65d117764f89aea6fb44f1aa883c192c427dc2b8 adds an empty box on the right. What is it for?

**Comment by mhinz** [comment]
When it detects `:set encoding?` == `utf-8`, then it uses Unicode characters to draw the box, which usually looks better than the default which uses ASCII.

I think what happens is that your terminal emulator displays Unicode characters double-width (according to Google that's mostly the case for East Asian languages). Unfortunately this is impossible to test for from Vim.

If that's the issue, the plugin should probably default to use ASCII again and introduce an option for people who want the Unicode box.

**Comment by mhinz** [comment]
Yup, I can reproduce your exact problem when I enable double-width character. In my case, iTerm, `Preferences -> Profiles -> Text -> Treat ambiguous-width characters as double with`.

**Comment by mhinz** [comment]
Please update the plugin. Unicode characters in the fortune header are opt-in now.

**Comment by haifengkao** [comment]
Thanks~~
