### ISSUE TITLE
`SOpen` after `SClose` pollutes buffer list.

### ISSUE THREAD

**Issue by MeanEYE** [mhinz/vim-startify#262]
Calling `SClose`, does indeed close currently open session however all the buffers remain open. After session is closed, _Startify_ window is presented where one can open new session. Opening new session causes all the currently opened buffers to become part of the new session and in that way pollute projects.

**Comment by mhinz** [comment]
Hmm, I see why this is happening. It should work if you set `g:startify_session_delete_buffers = 1`. But in the case of `:SClose` it should always work, right.

p.s. I hope you mean `:SLoad`, not `:SOpen`. :-)

**Comment by mhinz** [comment]
I wonder if we should just be pragmatic and always close all buffers when loading and closing a session.. hmm.

**Comment by MeanEYE** [comment]
Yes, I did mean `SLoad`. Sorry about that mistake. As for pragmatism in my opinion the best approach would be to close buffers by default when calling `SClose`, but leave option in case someone needs it.

**Comment by mhinz** [comment]
Okay, if we simply make `g:startify_session_delete_buffers = 1` the default, this would happen:

1. All listed buffers get deleted when using `:SLoad`.
2. All listed buffers get deleted when using `:SClose`.
3. All listed buffers get deleted when choosing a session from the Startify buffer.
4. All listed buffers get deleted when `g:startify_session_autoload = 1`. (Thus you `:cd` to a directory that has `Session.vim` and execute `:Startify`.)

Is this sane?

**Comment by MeanEYE** [comment]
Sounds right to me. Thanks!

**Comment by mhinz** [comment]
Done.

I also updated the doc to mention those 4 cases and cross-linked the option from all affected options and commands.

Thanks for bringing this up!

**Comment by MeanEYE** [comment]
Thanks!
