### ISSUE TITLE
neovim issue with opened help

### ISSUE THREAD

**Issue by whitecolor** [mhinz/vim-startify#263]
- `:e ~/.config/nvim/init.vim`
- `:h startify`
- `:SS`
So saved session looks like:
![image](https://cloud.githubusercontent.com/assets/736697/21995215/774c477c-dc45-11e6-8c3e-40961f12662c.png)
Then I load this session in another `nvim`, it looks a little bit different:
![image](https://cloud.githubusercontent.com/assets/736697/21995247/a0e457b4-dc45-11e6-9d79-5ef85ddca833.png)
buffer has now two file (init.vim, startify.txt)

**Comment by mhinz** [comment]
See `:h 'ssop'`. You may want to remove `help` from it.

E.g. `set sessionoptions-=help`.

**Comment by whitecolor** [comment]
A like situation with NERDTree plugin (I install it using `dein.vim` manager)
I save this session, with opened NERDTree:
![image](https://cloud.githubusercontent.com/assets/736697/21995394/88563a5e-dc46-11e6-9a28-65198b73bee6.png)

And load this, with empty side pane, and in buffer with additional `NERD_tree_2` file (which is empty)
![image](https://cloud.githubusercontent.com/assets/736697/21995447/cb6dffca-dc46-11e6-884d-79c9495091ad.png)

**Comment by mhinz** [comment]
What gets saved in a session is only affected by `'sessionoptions'`. Startify is not the problem.

`:SSave` and `:SLoad` are convenience wrappers around `:mksession` and `:souce`.

The problem with NERDTree is probably that it doesn't set its own window as `buftype=nofile`. So Vim think it's a file and includes it in a session. But it was dynamically created, so restoring the session will only lead to an empty window.

I'm not 100% sure, but I think you can avoid restoring empty windows by using `:set sessionoptions-=blank`.

Also, have a look at `:h g:startify_session_before_save` which seems to use NERDTree as an example.

**Comment by whitecolor** [comment]
Ok `:set sessionoptions-=blank` seem not to show the black nerd tree. think may be close.

Thank!
