### ISSUE TITLE
Disable the cow by default ?

### ISSUE THREAD

**Issue by inDigiNeous** [mhinz/vim-startify#266]
This is a great plugin, but the need to disable the stupid cow by default seems silly. Maybe disable it by default ? Just a suggestion. 

Or at least make it very clear how to disable this. I can't seem to find any clear documentation on how to do this. Takes space from the startup screen.

**Comment by mhinz** [comment]
Silly or not is obviously highly subjective.

The README mentions the FAQ. See `:h startify-faq-13`.
