### ISSUE TITLE
Neovim named terminal buffer turns to text

### ISSUE THREAD

**Issue by whitecolor** [mhinz/vim-startify#267]
Probably not vim-startify issue, but session related.

- create neovim terminal buffer
- I save a session
- quit neovim
- load saved session

I see the opend terminal - this works as expected.

If I give a terminal buffer name using `:file someterminalname`, I can work with it, but when I quit (with saved session), launch neovim and load saved session, instead of terminal I see a buffer with given name (`someterminalname`) with empty text, not a terminal buffer.

Any Ideas how to have persistent named terminal between sessions? Or this is a neovim issue?

**Comment by mhinz** [comment]
Yes, Vim sessions simply save the filenames and try reopening them at source time. Obviously that can't work for non-file buffers that are often used by plugins, the quickfix window would be empty etc.

In the case of terminal buffers it doesn't really save the shell session as well, it simply restarts the shell using the terminal buffer name. Try it yourself: `:e term://ls` works.

So, a Neovim feature. :-)

**Comment by mhinz** [comment]
By the way, see `:h terminal-emulator-spawning` for a few more details.
