### ISSUE TITLE
When scrolling with keyboard, can't get back to top of the screen to see the cow

### ISSUE THREAD

**Issue by Leeshe** [mhinz/vim-startify#270]
**VIM** - Vi IMproved 7.4 (2013 Aug 10, compiled Apr 27 2016 18:39:37)
Included patches: 1-1795

**OS**: Ubuntu 16.04.1 LTS

**Startify**: last version (Thu 09 Feb 2017)

**Issue**:  When scrolling down with the keyboard, if the cow is hidden like this:

![vimstartifycowhidden](https://cloud.githubusercontent.com/assets/16366403/22779181/021217e8-eeba-11e6-917f-f3cb97be84a5.png)

I can't scroll back up with the keyboard to see the cow, but it works fine with the mouse.

**Comment by mhinz** [comment]
That's just how Vim works if you use `k` or `gg` etc.  :)

Things that do work:

1. Going back a paragraph (`{`) or section (`[[`).
2. Adjusting the screen relative to the cursor position (`zb` or `zz`).

**Comment by Leeshe** [comment]
Thanks, solved.
