### ISSUE TITLE
Make "paste" (/ middle click) open a new buffer

### ISSUE THREAD

**Issue by anntzer** [mhinz/vim-startify#272]
I often start a vim just to temporarily store the contents of something I copied into my clipboard (or I'll use these contents as a starting point for further edits).  It'd be nice if in the startify screen, pasting commands ("<register>p", "<register>P", middle click) automatically opened a new buffer first.

Thanks in advance.

**Comment by mhinz** [comment]
Please update and see if it works as expected!

**Comment by anntzer** [comment]
It does, thanks for the quick reply.  Any chance it can work for `"<register>p` (in practice, `"+p`) as well?

**Comment by mhinz** [comment]
I'd rather not. Maybe I could do a weird hack for every key sequence that starts with `"`, but not for the general case when no register is given, e.g. `p` or `P`, because those characters could be used for `:h g:startify_custom_indices`.

**Comment by mhinz** [comment]
BTW, you can also define your own mappings for Startify: `:h startify-autocmd`.

**Comment by anntzer** [comment]
Sounds fair.  Feel free to close, then.
