### ISSUE TITLE
Intro screen flashes when launching vim

### ISSUE THREAD

**Issue by winsphinx** [mhinz/vim-startify#273]
After commit <967ea44>, the Intro screen (help Uganda) flashes when launching vim, and 2 or 3 secondes later the Startify screen appears.

So I had to add ` set shortmess+=I ` now.

I took quick view about the last 2 commits, and found nothing about Uganda. LOL... Would you please check what happened about Uganda?

**Comment by mhinz** [comment]
The last 2 commits merely added a single mapping for pasting via the middle mouse button. I can't see any way how that change could lead to the behaviour you describe.

When you checkout `5e9e6a4` in the repo, does it work?

**Comment by winsphinx** [comment]
Thank you. It seems that now I may find out the plug that results the screen. I made an issue on `vim-signity`, and closed this one.
