### ISSUE TITLE
changing startify_list_order loses headings.

### ISSUE THREAD

**Issue by tmccombs** [mhinz/vim-startify#276]
If you set g:startify_list_order, then you lose the headers for the sections ("MRU", "MRU {pwd}", "Bookmarks" etc).

I can work around this with something like

```vim
let g:startify_list_order = [['Bookmarks'], 'bookmarks', ['MRU ' . getcwd()], 'dir', ['MRU'], 'files', ['Commands'], 'commands', ['Sessions'], 'sessions',]
```

But the syntax isn't really documented, and the headers aren't indented the same as they are with the default (which I am personally ok with).

**Comment by mhinz** [comment]
Huh? :-)

I wouldn't claim it's the most elegant syntax ever, but it's all documented [here](https://github.com/mhinz/vim-startify/blob/master/doc/startify.txt#L164-L190).

**Comment by tmccombs** [comment]
Ah, I must have missed that.
