### ISSUE TITLE
 StartifySelect?

### ISSUE THREAD

**Issue by for-coursera** [mhinz/vim-startify#277]
What exactly does` StartifySelect` mean? The documentation states it's supposed to highlight selected entries -- however, the defining regex is way far from it:

    syntax match StartifyNumber  /^\s*\[\zs[^BSVT]\{-}\ze\]/
    syntax match StartifySelect  /^\s*\[\zs[BSVT]\{-}\ze\]/

i.e., it specifically highlights `B`, `S`, `V` or `T` letters in square brackets ([example](http://i.imgur.com/FAmpZQJ.png)).

Why is so?

**Comment by mhinz** [comment]
You can open multiple files in Startify by "marking" an entry by hitting <kbd>b</kbd>, <kbd>s</kbd>, <kbd>v</kbd>, or <kbd>t</kbd>. After you marked multiple entries, hit <kbd>cr</kbd> to execute the actions.

It's documented [here](https://github.com/mhinz/vim-startify/blob/master/doc/startify.txt#L61-L65).

And the `StartifySelect` highlight group is simply meant to highlight those actions.

**Comment by for-coursera** [comment]
Thanks!
