### ISSUE TITLE
What's the font being used in the screenshot?

### ISSUE THREAD

**Issue by retroalgic** [mhinz/vim-startify#280]
What's the font being used in the screenshot?

![Image](https://github.com/mhinz/vim-startify/raw/master/images/startify-menu.png)

**Comment by mhinz** [comment]
It's [InputMono](http://input.fontbureau.com/preview/?size=12&language=python&theme=monokai&family=InputMono&width=300&weight=400&line-height=1.4&a=0&g=0&i=0&l=0&zero=0&asterisk=0&braces=0&preset=default&customize=please). :]
