### ISSUE TITLE
MiddleMouse should paste from "* register when v:register is empty

### ISSUE THREAD

**Issue by anntzer** [mhinz/vim-startify#281]
Right now, by default, MiddleMouse pastes from the unnamed register.  To match the behavior that would happen in a normal buffer, it should instead paste from the PRIMARY (`"*`) register.  Something like
```
execute "nnoremap <buffer>". s:nowait ."<silent> <MiddleMouse> :enew <bar> execute 'normal! \"'.(v:register?v:register:'"*').'gp'<cr>"
```
should work (untested, and my vim-foo is not strong).

**Comment by mhinz** [comment]
Good catch!

Unfortunately I see a problem. `v:register` is never empty, and set to `"` by default _unless_ `'clipboard'` is set to either `unnamed` or unnamedplus`. 

`v:register` isn't writable neither.

Maybe we could go for `v:register == '"' ? '*' : v:register`?

We woudn't be able to detect `""<MiddleMouse>` anymore, but I'd argue that most people use directly `<MiddleMouse>` right after starting Vim (opposed to calling `:Startify` directy).

What do you think?

**Comment by anntzer** [comment]
Good catch, but similarly to your point, if you bothered to type `""` I think you're much more likely to follow with `p` rather than a middle click, so the approximation seems good enough to me.

**Comment by mhinz** [comment]
> I think you're much more likely to follow with p rather than a middle click

*\*nods\**

Thanks for bringing this up!
