### ISSUE TITLE
using an scp path as a bookmark works but throws an error

### ISSUE THREAD

**Issue by caedn** [mhinz/vim-startify#283]
I've added a remote file (`scp://10.1/logs/dhcp.log`) to `g:startify_bookmarks`. It shows up fine in the bookmark list and opening it works too but it throws an error:

```vimscript
Error detected while processing function startify#open_buffers[2]..<SNR>101_open_buffer[14]..<SNR>101_check_user_options:
line   10:
E472: Command failed
```

Accessing the file via `:e scp://10.1/logs/dhcp.log` does not produce an error.

**Comment by mhinz** [comment]
Oh, yeah. It tries changing the directory to `scp://10.1/logs`.

Please see if the latest version works for you.

**Comment by mhinz** [comment]
Please reopen this issue in case the fix doesn't work for you.

**Comment by caedn** [comment]
Sorry, I missed that. It works great!
