### ISSUE TITLE
Use text from cmd with built-in cowsay

### ISSUE THREAD

**Issue by Taverius** [mhinz/vim-startify#285]
Most of the spiffier cowfiles are way, way too big for startify's purpose, so you might as well get the nice UTF-8 box from the built-in.

Can you add a way to pass it a command's output?

Setting it from command when vimrc is sourced is trivial, but this *serious business*.

**Comment by mhinz** [comment]
> way too big for startify's purpose

I'd argue that's a font size / screen resolution issue. ;-)

See `Dynamic example` under `:h g:startify_custom_header`.

**Comment by Taverius** [comment]
But but, if I use the system cowsay (and what an adventure getting a working cowsay on windows is) I don't get the fancy unicode box! D:

Jokes aside, I peeked at the code and it seems impossible to do what I want, that is:

Pass Startify a command, and have in interpreted every time it runs, and fed to `startify#fortune#cowsay()`.

**Comment by mhinz** [comment]
Please update the plugin and try something like this:

```vim
let g:startify_custom_header_quotes = [ {-> systemlist('date')} ]
```

This uses a lambda expression which got added to recent Vims (`:h expr-lambda`).

For older Vims this works just as well:

```vim
function! s:date() abort
  return systemlist('date')
endfunction

let g:startify_custom_header_quotes = [ function('s:date') ]
```

**Comment by Taverius** [comment]
Works great, thanks :D
