### ISSUE TITLE
vim-startify doesn't work with neovim

### ISSUE THREAD

**Issue by sitilge** [mhinz/vim-startify#286]
So I decided to give a try to `vim-startify`. It was supposed to work right out of the box, however, it didn't go so smoothly in my case - instead of having the fancy startup screen, my good ol' `NERDTree` showed up. I read the `startify-faq` and modified the init.vim accordingly

````
set viminfo+=n$HOME/.config/nvim/files/info
set viminfo='100,n$HOME/.config/nvim/files/info

"Make them both live in peace and harmony
let NERDTreeHijackNetrw=0 
````

The method didn't work either. The info is not empty, data is stored, permission bits are `755` for the file and the dir.

**Comment by mhinz** [comment]
The `let NERDTreeHijackNetrw = 0` is only needed when you also `let g:startify_session_autoload       = 1`.

Usually NERDTree doesn't start by default. I assume you didn't post the whole init.vim.

If you want both to run at start, see `:h startify-faq-06` (after you disabled whatever you do to make NERDTree start by default).
