### ISSUE TITLE
Remember projects

### ISSUE THREAD

**Issue by chernyshof** [mhinz/vim-startify#287]
It will be great if startify can remember your projects(git directories for example)

**Comment by mhinz** [comment]
Do you know that you can hardcode directories as bookmarks?

E.g.

```vim
let g:startify_bookmarks = [
      \ '/tmp',
      \ { 'c': '~/.vim/vimrc' },
      \ ]
```

**Comment by chernyshof** [comment]
Thanks for the reply.
Yes, but I mean automatically do that with search .git(for example) path and save it as one of the projects.
I think this is not something important so you can close issue if you think the same.

**Comment by mhinz** [comment]
Okay, I'll created an issue for a more general approach that could be used to do exactly what you want. But it might take some time until I start implementing it.

https://github.com/mhinz/vim-startify/issues/288
