### ISSUE TITLE
Implement custom lists

### ISSUE THREAD

**Issue by mhinz** [mhinz/vim-startify#288]
Currently we have a fixed number of list types, e.g. `files`, `dir`, `session`, etc.

It would be great if we'd allow custom lists. For that I'd like to extend `g:startify_list_order`:

```vim
let g:startify_list_order = ['custom list title', function('s:callback', ...) ]

" This function gets a list of recently used files and is free to return whatever it likes.
" It can also ignore a:entries entirely. It returns any list.
function! s:callback(entries)
  for entry in a:entries
    startify#register(...)
  endfor
endfunction
```

This could be used to for creating a new list that shows recently accessed repositories (by searching for `.git` and `.hg` directories from the directory of each entry upwards) etc.

**Comment by RivasandPrather** [comment]
Code  Issues 2  Pull requests 0  Pulse
 duo_java/ cb11428
Updating Duo Web SDK to version 2.6
@AaronAtDuoAaronAtDuo committed with mschwager 4 months ago
3 changed files
81 additions and 17 deletions
DuoWeb/pom.xml
js/Duo-Web-v2.js
js/Duo-Web-v2.min.js
DuoWeb/pom.xml
@@ -12,7 +12,7 @@
 
   <groupId>com.duosecurity</groupId>
   <artifactId>DuoWeb</artifactId>
-  <version>1.2-SNAPSHOT</version>
+  <version>1.3</version>
 
   <dependencies>
     <dependency>
@@ -49,4 +49,4 @@
     </repository>
   </distributionManagement>
 
-</project> 
+</project>
js/Duo-Web-v2.js
@@ -1,10 +1,38 @@
 /**
  * Duo Web SDK v2
- * Copyright 2015, Duo Security
+ * Copyright 2017, Duo Security
  */
-window.Duo = (function(document, window) {
+
+(function (root, factory) {
+    /*eslint-disable */
+    if (typeof define === 'function' && define.amd) {
+        // AMD. Register as an anonymous module.
+        define([], factory);
+    /*eslint-enable */
+    } else if (typeof module === 'object' && module.exports) {
+        // Node. Does not work with strict CommonJS, but
+        // only CommonJS-like environments that support module.exports,
+        // like Node.
+        module.exports = factory();
+    } else {
+        // Browser globals (root is window)
+        var Duo = factory();
+        // If the Javascript was loaded via a script tag, attempt to autoload
+        // the frame.
+        Duo._onReady(Duo.init);
+
+        // Attach Duo to the `window` object
+        root.Duo = Duo;
+  }
+}(this, function() {
     var DUO_MESSAGE_FORMAT = /^(?:AUTH|ENROLL)+\|[A-Za-z0-9\+\/=]+\|[A-Za-z0-9\+\/=]+$/;
     var DUO_ERROR_FORMAT = /^ERR\|[\w\s\.\(\)]+$/;
+    var DUO_OPEN_WINDOW_FORMAT = /^DUO_OPEN_WINDOW\|/;
+    var VALID_OPEN_WINDOW_DOMAINS = [
+        'duo.com',
+        'duosecurity.com',
+        'duomobile.s3-us-west-1.amazonaws.com'
+    ];
 
     var iframeId = 'duo_iframe',
         postAction = '',
@@ -149,7 +177,8 @@ window.Duo = (function(document, window) {
             typeof event.data === 'string' &&
             (
                 event.data.match(DUO_MESSAGE_FORMAT) ||
-                event.data.match(DUO_ERROR_FORMAT)
+                event.data.match(DUO_ERROR_FORMAT) ||
+                event.data.match(DUO_OPEN_WINDOW_FORMAT)
             )
         );
     }
@@ -214,7 +243,7 @@ window.Duo = (function(document, window) {
             }
 
             if (options.iframe) {
-                if ('tagName' in options.iframe) {
+                if (options.iframe.tagName) {
                     iframe = options.iframe;
                 } else if (typeof options.iframe === 'string') {
                     iframeId = options.iframe;
@@ -256,15 +285,53 @@ window.Duo = (function(document, window) {
      */
     function onReceivedMessage(event) {
         if (isDuoMessage(event)) {
-            // the event came from duo, do the post back
-            doPostBack(event.data);
+            if (event.data.match(DUO_OPEN_WINDOW_FORMAT)) {
+                var url = event.data.substring("DUO_OPEN_WINDOW|".length);
+                if (isValidUrlToOpen(url)) {
+                    // Open the URL that comes after the DUO_WINDOW_OPEN token.
+                    window.open(url, "_self");
+                }
+            }
+            else {
+                // the event came from duo, do the post back
+                doPostBack(event.data);
 
-            // always clean up after yourself!
-            offMessage(onReceivedMessage);
+                // always clean up after yourself!
+                offMessage(onReceivedMessage);
+            }
         }
     }
 
     /**
+     * Validate that this passed in URL is one that we will actually allow to
+     * be opened.
+     * @param url String URL that the message poster wants to open
+     * @returns {boolean} true if we allow this url to be opened in the window
+     */
+    function isValidUrlToOpen(url) {
+        if (!url) {
+            return false;
+        }
+
+        var parser = document.createElement('a');
+        parser.href = url;
+
+        if (parser.protocol === "duotrustedendpoints:") {
+            return true;
+        } else if (parser.protocol !== "https:") {
+            return false;
+        }
+
+        for (var i = 0; i < VALID_OPEN_WINDOW_DOMAINS.length; i++) {
+           if (parser.hostname.endsWith("." + VALID_OPEN_WINDOW_DOMAINS[i]) ||
+                   parser.hostname === VALID_OPEN_WINDOW_DOMAINS[i]) {
+               return true;
+           }
+        }
+        return false;
+    }
+
+    /**
      * Point the iframe at Duo, then wait for it to postMessage back to us.
      */
     function ready() {
@@ -308,7 +375,7 @@ window.Duo = (function(document, window) {
         iframe.src = [
             'https://', host, '/frame/web/v1/auth?tx=', duoSig,
             '&parent=', encodeURIComponent(document.location.href),
-            '&v=2.3'
+            '&v=2.6'
         ].join('');
 
         // listen for the 'message' event
@@ -353,14 +420,11 @@ window.Duo = (function(document, window) {
         }
     }
 
-    // when the DOM is ready, initialize
-    // note that this will get cleaned up if the user calls init directly!
-    onReady(init);
-
     return {
         init: init,
+        _onReady: onReady,
         _parseSigRequest: parseSigRequest,
         _isDuoMessage: isDuoMessage,
         _doPostBack: doPostBack
     };
-}(document, window));
+}));
js/Duo-Web-v2.min.js
(diff suppressed)
0 comments on commit cb11428

Comment on cb11428
Sign in to comment
or sign up to join this conversation on GitHub
 Desktop version

**Comment by GianniGi** [comment]
I agree that having a configurable list at startup would considerably speed up my workflow.

**Comment by mhinz** [comment]
@GianniGi Could you give an example? What do you want to see at startup?

**Comment by sanmiguel** [comment]
I too would love to see custom lists for vim-startify!

A couple of lists I'd love are:
 - MRU Directories (maybe this could tie into the sessions list somehow?)
 - [vim-notes](https://github.com/xolox/vim-notes) integration: I would love to have quick access to my notes from the start screen
 - github notifications for user (i.e. github.com/notifications or enterprise GH equivalent)
 - github pull requests for user (i.e. github.com/pulls or enterprise GH equivalent)

Above all though, I'd love to see what you suggested above - a way to define our own callbacks to populate a list with data from wherever we please. Then it's just a case of hooking up a function that calls out to e.g. [octokit.rb](https://github.com/octokit/octokit.rb) (or one of the million python GH API libs) and handing it to vim-startify.

For specifying the config, I could imagine something such as:

```vim
let g:startify_list_order = [
  \ { 'name': 'github.com notifications',
  \    'function': function('s:list_github_notifications') },
  \ { 'name': 'notes',
  \    'function': function('s:list_notes') } ]
```
Where each of those callback functions returns a list of things that are a name and a command to run or something?

I got to thinking about this and realised that you could go one step further and, if we're currently in a `git` directory, and the remote matches a configured pattern (e.g. `github.com` or `your-enterprise-gh.org`) then show the pulls/issues for that repo... I don't know if that would prove to be useful but I feel like it might be.

**Comment by mhinz** [comment]
Okay.. since the old name `g:startify_list_order` is long out-of-date anyway, I introduced a new option `g:startify_lists`. That option does the same as the old one, but uses a different format.

If `g:startify_list_order` exists but not `g:startify_lists`, it gets converted to the new format automatically. I will mark `g:startify_list_order` as deprecated in the docs later.

Since we're using an undocumented new option, I pushed the code to master, since it won't break backward compatibility.

So, update the plugin and put this in your vimrc:

```vim
function! s:neovim_commits()
  let git = 'git -C /data/repo/neovim'
  let commits = systemlist(git .' log --oneline | head -n10')
  " use :Git from vim-fugitive
  let git = 'G' . git[1:]
  return map(commits, '{"line": v:val, "cmd": "'. git .' show ". matchstr(v:val, "^\\x\\+") }')
endfunction

let g:startify_lists = [
      \ { 'header': ['   Neovim commits'], 'type': function('s:neovim_commits') },
      \ { 'header': ['   MRU'],            'type': 'files' },
      \ { 'header': ['   MRU '. getcwd()], 'type': 'dir' },
      \ { 'header': ['   Sessions'],       'type': 'sessions' },
      \ { 'header': ['   Bookmarks'],      'type': 'bookmarks' },
      \ { 'header': ['   Commands'],       'type': 'commands' },
      \ ]
```

You probably have to adjust the function a bit, but it should explain the general approach.

If the `type` key is a function, that function should return a `list of dicts`, whereas each dict requires a `line` and `cmd` key.

To make it clear, `s:neovim_commits()` returns this in my case:

```
[{'cmd': 'Git -C /data/repo/neovim show cca407b43',
  'line': 'cca407b43 DirChanged: support <buffer> (#8140)'},
 {'cmd': 'Git -C /data/repo/neovim show 0093c25dd', 'line': '0093c25dd doc: nodejs'},
 {'cmd': 'Git -C /data/repo/neovim show 338664e96',
  'line': '338664e96 node/provider: support g:node_host_prog #8135'},
 {'cmd': 'Git -C /data/repo/neovim show 5ce8158a5',
  'line': '5ce8158a5 vim-patch:8.0.0316: :help z? does not work (#8134)'},
 {'cmd': 'Git -C /data/repo/neovim show f5b0f5e17',
  'line': 'f5b0f5e17 Merge pull request #8127 from jamessan/update-pvs-headers'},
 {'cmd': 'Git -C /data/repo/neovim show e24e98534',
  'line': 'e24e98534 ci/AppVeyor: use PowerShell (#8124)'},
 {'cmd': 'Git -C /data/repo/neovim show 4e5e6506b',
  'line': '4e5e6506b pvscheck: Ignore exit code of pvs-studio-analyzer'},
 {'cmd': 'Git -C /data/repo/neovim show 8bd1bbcec',
  'line': '8bd1bbcec Add missing PVS headers to new files'},
 {'cmd': 'Git -C /data/repo/neovim show c7f95fde1',
  'line': "c7f95fde1 ci/travis: Don't destroy cache during prepare"},
 {'cmd': 'Git -C /data/repo/neovim show 241c380da',
  'line': "241c380da Merge #8117 'build/CI/MSVC/LuaRocks'"}]
```

Does it work for you? Do you miss anything?

**Comment by sanmiguel** [comment]
This all sounds fantastic and exactly what I was after. I'll try to give it
a whirl tonight or over the weekend and let you know how it goes!

Thanks so much for such a comprehensive and swift answer! :+1:

**Comment by mhinz** [comment]
It's now all documented under `:h g:startify_lists`.

Thanks for the feedback. This is a pretty neat feature!

**Comment by sanmiguel** [comment]
Thanks for putting it together! I'm looking forward to getting it up and running in anger... I had a quick play with it at the weekend but picked the wrong plugin to try to integrate, which turned out not to be as helpful as vim-startify. :) I might be back with more questions or requests once I've got a couple of things going with it....
