### ISSUE TITLE
Docs says that it must open at start, but it doesn't

### ISSUE THREAD

**Issue by alex-shamshurin** [mhinz/vim-startify#290]
When I run `:Startify` it works, but does not start when I open macVim.

**Comment by mhinz** [comment]
Two possible explanation come to my mind:

1. Another plugin interferes. Please try disabling all plugins but vim-startify and see if it still happens.
2. How do you start MacVim? Via Spotlight and typing `MacVim`?

**Comment by alex-shamshurin** [comment]
Via Spot

**Comment by mhinz** [comment]
What about the other question?

**Comment by alex-shamshurin** [comment]
Yes, It does work when I open vim from console. Any ideas?

**Comment by mhinz** [comment]
How did you install MacVim? As far as I know homebrew doesn't link programs to `/Applications` on its own anymore. But it must be in `/Applications` or `~/Applications`, otherwise you couldn't run it via Spotlight.

**Comment by alex-shamshurin** [comment]
As far as I remember I've installed it via `brew cask install macvim`

**Comment by mhinz** [comment]
Hmm, I tried `brew install macvim` and running `mvim` from the shell and `brew cask install macvim` and running `MacVim` from Spotlight. Startify works for me in both cases.

Startify runs on Vim's startup under these conditions: [code](https://github.com/mhinz/vim-startify/blob/7f910ed4367de96310fedc98d5a12b97173a405f/plugin/startify.vim#L36). So, it runs when no file was specified _and_ the first buffer is completely empty.

What bugs me, is that it seems to work for you when you start it from the shell.. I think it must be something in your environment, but I can't name it. The best suggestion I can come up with currently is still disabling all other plugins and see if it makes any difference.

**Comment by alex-shamshurin** [comment]
I will disable other plugins and report results

**Comment by mhinz** [comment]
Please reopen, if you have results. :)
