### ISSUE TITLE
How to trigger actions when g:startify_change_to_vcs_root runs?

### ISSUE THREAD

**Issue by ahmedelgabri** [mhinz/vim-startify#292]
I have `let g:startify_change_to_vcs_root=1` in my setup but I also have some configs for linters & stuff that change depends if I'm inside a `.git` repo or not. Mainly to pick up project's configs instead of my global configs.

This works fine when I open a file where the `cwd()` is the git repo, but won't run properly when `let g:startify_change_to_vcs_root=1` is triggered, so how can I fix this if possible?

**Comment by mhinz** [comment]
I can only guess that your other plugin runs on events like `BufAdd` which get issued when a new file is opened. Changing to VCS root happens afterwards.. obviously. :> So, `BufAdd` and the plugins listening to it run already.

When does your plugin run? Or is it your own code?

FWIW, Neovim has a `DirChanged` event, which would be perfect for this kind of situation, but Vim has not.

**Comment by ahmedelgabri** [comment]
That's what I'm trying to do for example (not the best I know :), trying to make it better) https://github.com/ahmedelgabri/dotfiles/blob/master/vim/.vim/after/plugin/ale.vim#L13-L19 

> FWIW, Neovim has a `DirChanged` event, which would be perfect for this kind of situation, but Vim has not.

That's enough for me, I mainly use Neovim. Will give it a try!

**Comment by mhinz** [comment]
I just looked at the dotfiles you posted.. it's in `~/.vim/after/plugin`, so it's only run once directly at start, right? So, no matter what events get issued, that file will never be reread.

When you opened the file with Startify and the settings don't get set.. does it work after `:runtime! plugin/ale.vim`?

**Comment by ahmedelgabri** [comment]
I tried both things you mentioned & both of them didn't work.

What if I moved my check into an autoloaded function & called it with an `autocmd` instead of inside `~/.vim/after/plugin` will this work?

**Comment by mhinz** [comment]
I was just about to suggest that you simply change the file from..

```vim
...
" If local config file is availabe use it, otherwise use custom config
if !empty(glob(getcwd() .'/.prettierrc')) || !empty(glob(getcwd() .'/prettier.config.js'))
  let g:ale_javascript_prettier_use_local_config = 1
else
  let s:PARSER = empty(glob(getcwd() .'/.flowconfig')) ?  'babylon' : 'flow'
  let g:ale_javascript_prettier_options = '--parser ' . s:PARSER . ' --single-quote --trailing-comma all --no-semi'
endif
...
```

to

```vim
...
function! s:set_javascript_options()
  " If local config file is availabe use it, otherwise use custom config
  if !empty(glob(getcwd() .'/.prettierrc')) || !empty(glob(getcwd() .'/prettier.config.js'))
    let g:ale_javascript_prettier_use_local_config = 1
  else
    let s:PARSER = empty(glob(getcwd() .'/.flowconfig')) ?  'babylon' : 'flow'
    let g:ale_javascript_prettier_options = '--parser ' . s:PARSER . ' --single-quote --trailing-comma all --no-semi'
  endif
endfunction

autocmd DirChanged * call s:set_javascript_options()
...
```

**Comment by ahmedelgabri** [comment]
Yeah that worked, thanks!

I assume the same concept will apply to this too, I have this in my `vimrc` to be able to change some settings from a `.local.vim`. So also wrapping it in a function & calling it should work. (sorry if this is not directly related to the main issue)

```vim
let s:vimrc_project = $PWD . '/.local.vim'
if filereadable(s:vimrc_project)
  execute 'source ' . s:vimrc_project
endif
```

**Comment by mhinz** [comment]
Yup, running that code on `DirChanged` makes sense as well.

For the same purpose I use something like this:

```vim
function! s:source_project_config() abort
  let projectfile = findfile('.project.vim', expand('%:p').';')
  if filereadable(projectfile)
    execute 'source' projectfile
  endif
endfunction

autocmd BufRead,BufNewFile * call s:source_project_config()
```

So, the path of the current file doesn't even matter, since it simply searches each directory above the current one. So, when you switch to `/foo/bar/quux/file.vim` and the $PWD gets set to `/foo/bar/quux`, this snippet will look for the following files and in this order:

- `/foo/bar/quux/.project.vim`
- `/foo/bar/.project.vim`
- `/foo/.project.vim`
- `/.project`

This way you could even have different settings for different sub-directories of your project. This is especially useful if it's a big project that uses different languages etc.

**Comment by ahmedelgabri** [comment]
That's perfect, thanks very much! 👍

**Comment by mhinz** [comment]
You're welcome! ✨
