### ISSUE TITLE
Problems with custom j/k bindings

### ISSUE THREAD

**Issue by aaronc-bixly** [mhinz/vim-startify#294]
More of a question than an outright issue, maybe this could be solved on my end or there might be a better idea that can be added to the project.

I use a colemak keyboard layout when I type, which comes with it's own set of issues when it comes to vim. One of the tricks I use to make it work for me is to remap j to k and k to j in normal mode. When in the startify buffer, I noticed that my bindings weren't respected, which makes it a little confusing. So I went searching and found the offending code.

https://github.com/mhinz/vim-startify/blob/22ccf5861397dd2365756c24ce1952736632cd8c/autoload/startify.vim#L749-L756

I'm not sure I understand the gj mapping issue, but could this be solved by changing the if statement to: `if maparg('j', 'n') != 'gj'`? That way the plugin is explicitly checking for the mapping it wants to avoid, instead of messing with any custom mapping.

**Comment by mhinz** [comment]
It was a workaround: Some people use gj and friends by default. This makes a difference when text is wrapped, but then the cursor doesn't change the line, only the column, which confused the cursor setting code that acts on the `CursorMoved` event.

But.. that code is fixed now and I removed the above local mappings.

Should be working as expected now!

**Comment by aacunningham** [comment]
Just updated and it works great! Thanks for the quick fix!

**Comment by aaronc-bixly** [comment]
Just updated and it works perfectly! Thanks for the quick fix!

**Comment by mhinz** [comment]
Thanks for bringing this up!
