### ISSUE TITLE
[Feature Request] Add an option to disable session overwrite check?

### ISSUE THREAD

**Issue by spacewander** [mhinz/vim-startify#295]
First of all, I should thank you for your helpful work! The `vim-startify` plugin saves me a lot of time.

Could it possible to add an option to disable the session overwrite check, so `vim-startify` won't prompt me `Session already exists. Overwrite? ` each time I update the session? Or is there a better way to update the existent session?

**Comment by mhinz** [comment]
> thank you for your helpful work!

Thank you for using it!

> Could it possible to add an option to disable the session overwrite check, so vim-startify won't prompt me Session already exists. Overwrite? each time I update the session? Or is there a better way to update the existent session?

Using `!` after a command is a typical Vim idiom. It already worked for `:SDelete!` and I now added support for `:SSave!` as well.

Does this work for you?

**Comment by spacewander** [comment]
@mhinz 
It works as expected! Thank you so much!

**Comment by mhinz** [comment]
Thank you for bringing this up!
