### ISSUE TITLE
Is it possible to have a colored header?

### ISSUE THREAD

**Issue by filipekiss** [mhinz/vim-startify#297]
First of all, thanks for the amazing plugin @mhinz! I love it!

Now, to my question

Is it possible to use ASCII codes or something like that to have colored output on the custom header?

I've changed my header to a NeoVim logo and today it looks like this:

![pasted_image_13_12_17_13_27](https://user-images.githubusercontent.com/48519/33946585-535ca8de-e009-11e7-99a6-e1a92b044bcd.jpg)

It's nice and all, but would it be possible to do something like this?

![pasted_image_13_12_17_13_29](https://user-images.githubusercontent.com/48519/33946696-99f81b02-e009-11e7-90c4-6d13ec8779e1.jpg)

I've found #205 but that seems to apply the same color to the whole header and I wanted to make it multiple colors.

Is this possible and, if not, any idea if this will ever be supported? 

Thank you!

**Comment by mhinz** [comment]
Sorry, but that won't happen.

I could imagine a a list of tuples whereas the first value contains the highlighting group and the second value the actual text. But that would lead to an enormous list and the need to dynamically build the syntax file which is expensive.

Another idea: there are plugins that support ANSI escape sequences, but those usually also remove all other highlighting (including the one from this plugin).

[AnsiEsc](https://github.com/vim-scripts/AnsiEsc.vim) is such a plugin. Here's what its help says:

```
	PROBLEM WITH EMBEDDING:

		AnsiEsc plugin highlighting cannot be embedded in another
		syntax language.

		AnsiEsc uses the syntax highlighting engine, so it is
		effectively another syntax highlighting language.  But,
		there are major differences:

			* It supports being turned on and off

			* AnsiEsc is not a syntax highlighting file, it
			  is a plugin

			* AnsiEsc dynamically determines some syntax
			  highlighting by analyzing what's needed in the
			  current file.

		To do a syntax highlighting file would involve an inordinate
		quantity of permutations, resulting in a file that would take
		much time to load (about a half hour with only a partially
		complete set of permutations on my system).

		Normally to embed a syntax highlighting language in another
		would involve a pair of syntax highlighting commands such as:

		  syn include @AnsiEsc
		  syn region ... defines the region where AnsiEsc
		  \              highlighting is to occur ...  contains=@AnsiEsc

		placed in the other syntax file's definitions.  That won't
		work with AnsiEc because, again, AnsiEsc is not a syntax
		highlighting file.
```

So, sorry, but it really won't happen. :sob:

**Comment by filipekiss** [comment]
No worries! I'll just make it completely blue :P It's good enough for me.

**Comment by micalexander** [comment]
@filipekiss do you happen to still have the vim ascii for that neovim logo? I have generated one myself, however I think the one you have is better.

**Comment by korganrivera** [comment]
If anyone, for some reason, wants the text version of this but can't be bothered typing it out, I just did it. Here it is:
```
          .          .
        ';;,.        ::`
      ,:::;,,        :ccc,
     ,::c::,,,,.     :cccc,
     ,cccc:;;;;;.    cllll,
     ,cccc;.;;;;;,   cllll;
     :cccc; .;;;;;;. coooo;
     ;llll;   ,:::::`loooo;
     ;llll:    `:::::loooo:
     :oooo:     .::::llodd:
     .;ooo:       ;cclooo:.
       .;oc        `coo;.
         .`         .,.

```
