### ISSUE TITLE
Set Titlestring to session name

### ISSUE THREAD

**Issue by BonaBeavis** [mhinz/vim-startify#301]
Hi,

switched over from vim-session. I set my titlestring to the name of the current session:

`auto BufEnter * let &titlestring = "Neovim " . xolox#session#find_current_session()`

Does Startify has a function like `xolox#session#find_current_session()`

Cheers

**Comment by mhinz** [comment]
Well, what does that function do? :-)

In general, Vim has an internal variable `v:this_session` which points to the file of the current session or is empty when there was no session sourced yet.

Does that help already?

**Comment by BonaBeavis** [comment]
It did help, thanks!

```vim
set title
auto BufEnter * let &titlestring = "Neovim " . fnamemodify(v:this_session, ':t:r')
```

If this is inside `vimrc` then the title of the terminal-window is set to the name of the current session.

**Comment by mhinz** [comment]
Good! I guess this can be closed then.

By the way, using the `SessionLoadPost` event might be even better, since it triggers less often than `BufEnter`.
