### ISSUE TITLE
vim sessions

### ISSUE THREAD

**Issue by GianniGi** [mhinz/vim-startify#302]
Hello, my vim doesn't show persistent sessions in the startup dialogue.

I save the sessions in the home folder, using 
`mksession`

VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Oct 26 2017 00:51:47)
ubuntu 17.10

**Comment by mhinz** [comment]
Hi,

Startify can't magically find sessions saved somewhere on the disk. Listing the sessions works because all sessions managed by Startify are put into the same directory.

Use `:SS` instead of `:mksession`.

See `:h startify-commands` and the session options in `:h startify-options`.
