### ISSUE TITLE
Add an option to disable default marker mappings.

### ISSUE THREAD

**Issue by kiooss** [mhinz/vim-startify#303]
The marker mappings `b,s,t,v` doing the <nowait> mappping, it overwrite my own mappings.
Can this feather be configurable?

**Comment by mhinz** [comment]
Why do you overwrite such important normal mode mappings and are they really that important in the Startify buffer?

I'm asking because I usually try to avoid adding even more options unless it's really needed. :)

**Comment by kiooss** [comment]
The problem is about `s`, I found I rarely use the `s` key in normal mode, so I use it as `[Window]` prefix key.  I have the mappings like below in my config.

```
nnoremap [Window]   <Nop>
nmap     s [Window]
nnoremap <silent> [Window]p  :<C-u>vsplit<CR>:wincmd w<CR>
nnoremap <silent> [Window]o  :<C-u>only<CR>
nnoremap <silent> [Window]h  :wincmd H<CR>
nnoremap <silent> [Window]j  :wincmd J<CR>
nnoremap <silent> [Window]k  :wincmd K<CR>
nnoremap <silent> [Window]l  :wincmd L<CR>
```

**Comment by mhinz** [comment]
Unusual! But whatever works. :-)

When the Startify buffer is fully set up, it emits an User event called _Startified_.

You could hook into it like this:

```vim
autocmd User Startified for key in ['b','s','t','v'] | exe 'nunmap <buffer>' key | endfor
```

Does this work for you?

**Comment by kiooss** [comment]
It works! Thank you very much.
