### ISSUE TITLE
Refresh MRU lists after DirChanged

### ISSUE THREAD

**Issue by sanmiguel** [mhinz/vim-startify#305]
As per title, I found it a bit confusing when I did a `cd ~/git/foo/bar` and the MRU list was still relative to `~`. Would be nice if the MRU got updated when `DirChanged` event fires.

**Comment by sanmiguel** [comment]
Oh I wanted to add a 'Feature Requested' label but only authors can do that :)

**Comment by mhinz** [comment]
Simply re-running `:Startify` should do it.

While fixing this I noticed a bug in Neovim: https://github.com/neovim/neovim/pull/8140

Thanks for bringing this up! ✨

**Comment by sanmiguel** [comment]
Thanks for fixing this so quickly! 👍
