### ISSUE TITLE
startify: Can't read viminfo file. Read :help startify-faq-02

### ISSUE THREAD

**Issue by mboughaba** [mhinz/vim-startify#306]
Hi,

First of all I really enjoy using this plugin :) it make session handling, MRU and quick access a breeze 🥇  
Thanks for putting it all together.

I keep all my plugs including Startify up to date almost daily. However, this morning when I opened my ViM Startify wasn't happy at all.

When closing or opening vim Startify displays ton of error message.
``` 
E575: viminfo: Illegal starting char in line: INDX(
E575: viminfo: Illegal starting char in line: ^BA
E575: viminfo: Illegal starting char in line: ^BA
E575: viminfo: Illegal starting char in line: ^BA
E575: viminfo: Illegal starting char in line: ^AA
E575: viminfo: Illegal starting char in line: ^BA
E575: viminfo: Illegal starting char in line: ^BA
E575: viminfo: Illegal starting char in line: ^AA
E575: viminfo: Illegal starting char in line: ^BA
E575: viminfo: Illegal starting char in line: ^BA
E136: viminfo: Too many errors, skipping rest of file
``` 
`:messages` will results in `startify: Can't read viminfo file. Read :help startify-faq-02`

I am using this plugin since a long time now and never had issues on any of the platforms `Window 10` and `Ubuntu 16.04`.

My viminfo is accessible and my sessions are displayed correctly, seems that only the MRU list is impacted.

I am not sure this is related to Startify...
I saw that my viminfo contains a garbage on the first line like:
`INDX(@BA @BA...)` I didn't find anything related to that on vim or startify documentation or even google.
 does anyone who what is that? if not I will close this issue.

After removing the first line from viminfo it is working properly now. Very strange.

**Comment by mhinz** [comment]
Yeah, the Startify issue was a consequential error of an corrupt viminfo file.

As to why it got corrupted.. almost impossible to say. Personally, I'd try to upgrade Vim (viminfo patches happen every now and then) and forget about it.

That's all the advice I can give. :-)

**Comment by ryancheung** [comment]
I got this error because my `~/.vimfile` owner is root, `sudo rm -rf ~/.vimfile` and then restart vim.

**Comment by RonaldZhao** [comment]
```bash
$ sudo rm ~/.viminfo
$ vim
:q
$ sudo chmod 777.viminfo
$ vim
```

**Comment by ayush-mandowara-bst** [comment]
Reinstalling vim solved the problem for me. 
- Official download link: https://www.vim.org/download.php#pc
