### ISSUE TITLE
How to get dev-icons working?

### ISSUE THREAD

**Issue by kreedz** [mhinz/vim-startify#307]
Solved, I should read doc before creating issue.
I'm sorry.

Solution:
```vim
    function! StartifyEntryFormat()
        return 'WebDevIconsGetFileTypeSymbol(absolute_path) ." ". entry_path'
    endfunction
```

---

nvim 0.2.2
OS: Windows 8.1
[Patched nerd fonts](https://github.com/ryanoasis/nerd-fonts#font-installation) (Option 2 used)
`ginit.vim`:
```vim
"I've tried these fonts
Guifont ProFontIIx Nerd Font Mono
"Guifont Inconsolata Nerd Font Mono
"GuiFont Anonymice Nerd Font Mono
"Guifont TerminessTTF Nerd Font Mono
```
`init.vim`:
```vim
call plug#begin('~/.local/share/nvim/plugged')
	Plug 'scrooloose/nerdtree'
	Plug 'Xuyuanp/nerdtree-git-plugin'
	Plug 'mhinz/vim-startify'
	Plug 'ryanoasis/vim-devicons'
call plug#end()

set termguicolors
set t_Co=256
```

### Expected
![image](https://user-images.githubusercontent.com/2128965/37603975-b9629e7e-2bb1-11e8-995c-cb09e0519529.png)

### What I've got
![1903-nerdtree](https://user-images.githubusercontent.com/2128965/37604815-a660c1fa-2bb3-11e8-8fc2-7b2121f2549b.png)

As you can see NERDTree showing the symbols.

Answers to [this](https://github.com/ryanoasis/vim-devicons/wiki/FAQ-&-Troubleshooting#not-working-general):
 - check what the vim/gvim font is set to, from ex mode:
```vim
:set guifont? " gives  E519: Option not supported: guifont?
```
But
```vim
let g:Guifont " gives me my current font: ProFontIIx Nerd Font Mono:h11
```
 - check if the plugin is loaded (should give '1'), from ex mode:
```vim
:echo loaded_webdevicons " gives 1
```
 - check if the plugin is enabled (should give '1'), from ex mode:
```vim
:echo g:webdevicons_enable " gives 1
```
 - check if the plugin is enabled for NERDTree (should give '1'), from ex mode:
this should NOT need to be set under normal circumstances
```vim
:echo g:webdevicons_enable_nerdtree " gives 1
```
 - check if you are able to see the characters, from ex mode:
```vim
:echo g:WebDevIconsUnicodeDecorateFileNodesDefaultSymbol " gives nothing
```
 - if all this looks correct you may try this to see if any files show flags

last resort, see if you can even set the default symbol and have it display anywhere (NERDTree, vim-airline's statusline, vim-airlines's tabline), from ex mode:
```vim
" It doesn't change symbols in NERDTree and doesn't add any symbol to Startify.
:let g:WebDevIconsUnicodeDecorateFileNodesDefaultSymbol='x' 
```

**Comment by lee-shun** [comment]
![屏幕截图](https://user-images.githubusercontent.com/46647235/131707458-ef17b998-1362-475b-b3ec-07536975ae1c.png)
