### ISSUE TITLE
Problems with viewing man-pages inside 

### ISSUE THREAD

**Issue by durcheinandr** [mhinz/vim-startify#310]
First things first: Thanks for `startify` and your other work for vim.

Now the problem: I view man-pages inside of vim and set therefor an environment-variable:

```
echo $MANPAGER
vim -c "%! col -b" -c "set ft=man nomod nolist ignorecase" -
```

Viewing a man-page with `man command` opens vim with starify in the visible buffer. After hitting `:b<cr>` startify disapears and the man-page is shown as expected. Is there any way to hide/disable startify wenn reading man-pages from STDIN?

**Comment by mhinz** [comment]
Argh, that was a regression I introduced yesterday. It's fixed now.

Thanks for reporting this! ✨

**Comment by durcheinandr** [comment]
Thanks for fixing this issue that fast
