### ISSUE TITLE
Slow on Windows

### ISSUE THREAD

**Issue by wrichert** [mhinz/vim-startify#311]
When clicking on a file c:\test.txt on Windows, it hangs for a couple seconds and then opens it as c:\\test.txt.

Each time I move to another tab and then back again it hangs again for a couple seconds.

**Comment by mhinz** [comment]
Why do you think Startify is the culprit here? It usually does nothing on switching tabs.

I'd suggest disabling all other plugins for testing purposes. And maybe checking `:verb au BufEnter`, since it sounds like it happens every time you change the buffer.

**Comment by wrichert** [comment]
It is not only the tab switching. Whenever I switch to a buffer that was first opened with Startify, it is that slow.

**Comment by mhinz** [comment]
Ah, above you mentioned `c:\test.txt` twice. It wasn't put in ``, so the one `\` got lost.

I'm not sure why it should make a difference if the file gets loaded correctly. Maybe `c:\\` means accessing the network as well, or some such? I'm no Windows user.

I'll check this the next time I'll play around with Windows.

**Comment by wrichert** [comment]
I just replaced all double-backslashes in _viminfo with a single-backslash and everything is fast now.
Maybe you could add some regex replacement into Startify that would normalize those malformed filenames?

**Comment by wrichert** [comment]
In any case, thanks for the productive plugin! 😃

**Comment by mhinz** [comment]
What's the output of `:set shell? shellslash?` on your system?

**Comment by wrichert** [comment]
```shell=C:\WINDOWS\system32\cmd.exe
noshelslash```

**Comment by mhinz** [comment]
I could never reproduce this issue and I think it shouldn't the task of this plugin to fix broken viminfo files. Getting this kind of "detect broken viminfo file" detection right seems to be almost impossible.

I think it would be the best to find out why the paths ended up like that in the viminfo file in the first place.

Hope you understand and thanks for bringing this up anyway.
