### ISSUE TITLE
Suggestions for more quotes

### ISSUE THREAD

**Issue by Alok** [mhinz/vim-startify#312]
At the risk of duplicates (was too lazy to check against existing quotes):

> Every great developer you know got there by solving problems they were unqualified to solve until they actually did it.

> A primary cause of complexity is that software vendors uncritically adopt almost any feature that users want.

> No one in the brief history of computing has ever written a piece of perfect software. It's unlikely that you'll be the first.

> One of the best programming skills you can have is knowing when to walk away for awhile.

> For a long time it puzzled me how something so expensive, so leading edge, could be so useless. And then it occurred to me that a computer is a stupid machine with the ability to do incredibly smart things, while computer programmers are smart people with the ability to do incredibly stupid things. They are, in short, a perfect match.

> I don't care if it works on your machine! We are not shipping your machine!

> Debugging is twice as hard as writing the code in the first place. Therefore, if you write the code as cleverly as possible, you are, by definition, not smart enough to debug it.

> Sometimes it pays to stay in bed on Monday, rather than spending the rest of the week debugging Monday's code.

> People think that computer science is the art of geniuses but the actual reality is the opposite, just many people doing things that build on each other, like a wall of mini stones.

> Debugging is twice as hard as writing the code in the first place. Therefore, if you write the code as cleverly as possible, you are, by definition, not smart enough to debug it.

> Most of you are familiar with the virtues of a programmer. There are three, of course: laziness, impatience, and hubris.

> To iterate is human, to recurse divine.

> There are two ways of constructing a software design. One way is to make it so simple that there are obviously no deficiencies. And the other way is to make it so complicated that there are no obvious deficiencies.

> They know enough who know how to learn.

> Think twice, code once.

> Think (design) globally; act (code) locally.

> Weeks of programming can save you hours of planning.

> Why do we never have time to do it right, but always have time to do it
over?

> He who asks is a fool for five minutes; he who does not ask remains a
fool forever.

> The first step towards wisdom is calling things by their right names.

> No matter how far down the wrong road you have gone, turn back now.

> The most exciting phrase to hear in science -the one that heralds new
discoveries- is not *"Eureka!"* but *"That's funny..."*.

**Comment by mhinz** [comment]
Thanks! ✨ 

I used some of these and added a bunch of others.

**Comment by Alok** [comment]
Another one my old data structures teacher mentioned was:

> Learning how to program gives you a robotic mind. Be careful, for when you stare into the machine you get the soul of a machine.
