### ISSUE TITLE
KJP quotes

### ISSUE THREAD

**Issue by Alok** [mhinz/vim-startify#313]
[A bit of humor never hurt anybody](http://kingjamesprogramming.tumblr.com/).

> Well-designed computational systems, like well-designed automobiles or
nuclear reactors, are designed in such a way as to not allow side
effects or aliasing.

> Well-designed computational systems, like well-designed automobiles or
nuclear reactors, are designed in such a way as to not allow side
effects or aliasing.

> Fortunately, learning to program is considerably less dangerous than
learning sorcery.

> And, behold, I will deliver you up to the programmer tendency to build
overelaborate castles of abstractions.

> ./configure; make; make believe

**Comment by mhinz** [comment]
I don't think I want Markov-generated quotes to be the default. They probably confuse people who don't know they were generated. :>

Thanks anyway!

**Comment by Alok** [comment]
I do think the one about "overelaborate castles of abstraction" is eerily accurate.
