### ISSUE TITLE
neovim: startify prevents reading from stdin/pipe via `-`

### ISSUE THREAD

**Issue by davidnorthetal** [mhinz/vim-startify#317]
e.g.: `echo "ASD" | vi -` doesn't work as long as I use startify, instead of reading from stdin it opens startify

because I use this a lot, I sadly have to disable startify for now
would really appreciate it if we can fix this

**Comment by mhinz** [comment]
Are you really using the latest version of vim-startify? This should be fixed as of https://github.com/mhinz/vim-startify/commit/532f3db6be8c6e123abb3f6523c419b6b19436da

**Comment by davidnorthetal** [comment]
Thanks that seems to have been it. - Could've sworn I updated before but I guess I didn't.
Works now.
