### ISSUE TITLE
nerdtree

### ISSUE THREAD

**Issue by yaserrahimi** [mhinz/vim-startify#319]
hi
i use startify alongside nerdtree 
and when i run vim i can't see startify first page
just i see nerdtree first page
![screenshot from 2018-05-04 12-50-58](https://user-images.githubusercontent.com/19384196/39616406-7f235c8c-4f90-11e8-82b3-7e802e02659c.png)

**Comment by mhinz** [comment]
`:h startify-faq--6` should be helping here.

**Comment by mhinz** [comment]
To be more precise, Startify will only show at start when there's nothing else shown already. There must be an empty buffer as if you started `vim` without any arguments (and other plugins that show things at start).

If NERDTree runs first and opens it typical file list window, Startify won't run. But as said above, `:h startify-faq-06` shows how to make sure that NERDTree runs first.

**Comment by Ruby-Dick** [comment]
Put this in your vimrc:
>
    autocmd VimEnter *
                \   if !argc()
                \ |   Startify
                \ |   NERDTree
                \ |   wincmd w
                \ | endif
<
