### ISSUE TITLE
Does it work with vim-obsession?

### ISSUE THREAD

**Issue by alex-shamshurin** [mhinz/vim-startify#320]

**Comment by mhinz** [comment]
Perhaps? Have you tried?

The session options are all opt-in, so you're free to choose any other plugin for session handling.

**Comment by Cybolic** [comment]
You can make vim-startify and vim-obsession work together a bit more closely by letting vim-obsession write/handle the session after each save. One way is by replacing the `SSave` command:

```
command! -nargs=? -bar -bang -complete=customlist,startify#session_list SSave   call startify#session_save(<bang>0, <f-args>) | if !empty(v:this_session) | execute "Obsession " . v:this_session | endif
```

**Comment by Artem-Schander** [comment]
Hi everyone,
I thought I share [my solution](https://github.com/dhruvasagar/vim-prosession/issues/40#issuecomment-791983037).

Here you can see both types of sessions coexisting.
![75964315-4c4f7500-5ec7-11ea-9689-87f387373fb8](https://user-images.githubusercontent.com/1243826/110213980-be73e480-7ea2-11eb-9f56-d3ecc3478520.png)
The session with the folder icon comes from ProSession (a wrapper for Tim Popes Obsession) and the one with the globe comes from Startify.
