### ISSUE TITLE
more quotes

### ISSUE THREAD

**Issue by alok** [mhinz/vim-startify#322]
Apologies for any reposts

---

It's not worth doing something unless someone, somewhere, would much
rather you weren't doing it.

The more that you read, the more things you will know. The more that you
know, the more places you'll go.

One of the sources of pride in being a human being is the ability to
bear present frustrations in the interest of longer purposes.

Proper preparation prevents poor performance.

Don't worry about people stealing your ideas. If your ideas are any
good, you'll have to ram them down people's throats.

If you can imagine a society in which the computer is the only menial,
you can imagine anything.

When you don't create things, you become defined by your tastes rather
than ability. Your tastes only narrow and exclude people. So create.

Wisdom is earned through disgrace, through painful realization of the
inadequacy of your personal world view.

Illegitimi non carborundum

If you've chosen the right data structures and organized things well,
the algorithms will almost always be self-evident. Data structures, not
algorithms, are central to programming.

anyone can cook, but only the fearless can be great (from ratatouille, mentioned in Norvig's Teach yourself programming in 10 years)

A good system aggressively uses a small number of abstractions.

Most people overestimate what they can do in a day and underestimate
what they can do in a year.

If you learn only methods, you'll be tied to your methods. But if you
learn principles, you can devise your own methods.

The only difference between science and screwing around is writing it
down.

**Comment by alok** [comment]
A relevant one for programming:

If you have a function with 10 parameters, you probably missed some.

**Comment by mhinz** [comment]
We added quite a lot of new quotes lately and the list is pretty long by now. Thus I won't add new things right now.

But I collect new quotes in a local QUOTES file, in case I'll ever feel like adding even more. (But then I'll probably remove some of the old quotes as well.)

Thanks, Mr. Quotes! ;-)
