### ISSUE TITLE
Disable from the command line?

### ISSUE THREAD

**Issue by 097115** [mhinz/vim-startify#332]
Is there any way to disable Startify from the command line? As much as I love it, sometimes (when reading from stdin, from example) I just don't need it :).

**Comment by mhinz** [comment]
Huh, it shouldn't appear when you read from stdin (e.g. `echo foo | vim -`)

Can you give an example?

**Comment by 097115** [comment]
Yeah, `vim -` doesn't launches Startify. That's my bad in formulating a question. However, there also other cases.

I actually had in mind something like passing some command line parameter that would tell Vim not no launch Startify. But solved it via something like `-c "call feedkeys('e')"`, which simply bypasses Startify and opens an empty buffer.

**Comment by mhinz** [comment]
Ah, okay. I thought there would be a bug. :)

Another way that keeps the plugin from even running would be:

```
$ vim -c 'let g:startify_disable_at_vimenter = 1'
```

**Comment by 097115** [comment]
More like "should be" :) 

I mean, I tried that before opening the issue, but it didn't work for me. Probably because of [this](https://github.com/mhinz/vim-startify/issues/139#issuecomment-378209188).

**Comment by mhinz** [comment]
Maybe change it to this:

```vim
if has('nvim')
  autocmd TabNewEntered * Startify
else
  autocmd BufEnter *
        \ if !exists('t:startify_new_tab') && empty(expand('%'))
        \     && (get(g:, 'startify_disable_at_vimenter', 1) && bufnr('') != 1) |
        \   let t:startify_new_tab = 1 |
        \   Startify |
        \ endif
endif
```

I'm not sure about the corner cases, because it's all just a big hack. (The Nvim version works as expected.)
