### ISSUE TITLE
the saved session does not keep the buftype infomation

### ISSUE THREAD

**Issue by liushapku** [mhinz/vim-startify#333]
When a session containing help docs is restored, the help buffer's `buftype` is not restored to `help`. Instead they are treated as normal files. Running `:h` will then create a new window instead of reusing the window editing the help doc.

**Comment by mhinz** [comment]
I can reproduce it, but it's a Vim quirk.

See `:h 'ssop'`. IMHO, it should work correctly out of the box, because `help` is included by default. But the buftype is not remembered without the non-default `localoptions`.

So, put this in your vimrc:

```vim
set sessionoptions+=localoptions
```

Hope this helps!
