### ISSUE TITLE
May I reuse the same "Startify-View_File" across Ubuntu and Windows?

### ISSUE THREAD

**Issue by llinfeng** [mhinz/vim-startify#337]
My daily driver is a Windows 10 machine, and I am experimenting the "Windows Subsystem for Linux" on it. I have got `ubuntu.exe` installed, and have made Vim to source its configuration files (`*.vim`) from the Windows OS.

## Cannot open Windows-saved sessions on Ubuntu-Vim
Now, I get the following error when I try to load existing sessions from Startify when I am in the Vim hosted by "Ubuntu on Windows":
![startify_trailing_char](https://user-images.githubusercontent.com/5890407/47049033-1db5ea80-d16a-11e8-89fb-a1e34a7b8fea.png)

Please advise what to specify when it comes to how Vim saves these views.

## Cannot open Ubuntu-saved session on Windows-Gvim
I have also tried to save a Startify session on the Ubuntu-vim, and it worked well: I can save and load it within the Ubuntu Vim environment. Yet, I got the following error when trying to load such "Ubuntu-saved" session on Windows-Gvim
![open_ubuntu_session_from_gvim](https://user-images.githubusercontent.com/5890407/47049218-ae8cc600-d16a-11e8-93e1-a9590cb5b202.png)

## Observation
It is clear that the sessions saved by each OS are OS-specific: 
* Gvim on Windows can save and load its own Startify sessions, and 
* Vim on Ubuntu can save and load its own Startify sessions as well.  
One way to live with the restrictions is to name the sessions strategiclly, by creating `u_Project1` sessions for Ubuntu-Vim specifically.

*Looking forward to a way to summon the sessions irrespective of the OS*.

**Comment by mhinz** [comment]
Sorry, but I almost never use Windows and never used WSL so far.

The way sessions are saved can be influenced with `:h 'ssop'`. It mentions:

```
	"slash" and "unix" are useful on Windows when sharing session files
	with Unix.  The Unix version of Vim cannot source dos format scripts,
	but the Windows version of Vim can source unix format scripts.
```

You probably have to play around with these values.

If you ever need to change where Startify saves sessions, use `:h g:startify_session_dir`. Maybe use different values for Win and Ubuntu. (Although that should be the default for both OS, but then again I have no idea how WSL really works.)

**Comment by llinfeng** [comment]
Thank you for pointing out that I shall tell Startify to source different `startify_session_dir`. Indeed, WSL has its own set of `~/.vimrc` files, and I can thus direct Startify to source a different folder for WSL. And, here goes a few good reasons for leaving the session files native to the file-system:
* After all, WSL is using its unique file-system, with its unique mounting directory and so on.
* This makes even the absolute path of, say, `fileA` to be different


However, here go a few observation that I see as opportu nities to have a saved-session shareable across OS/build:
* Enable an option to pass an environmental variable to the file-path, as saved by Startify. That is to say, improve the first line (found in a saved session) to the second line:
   ```
    edit Nutstore/Research/BEE_Lab/homepage/ref.md
    edit $PC_Home/Nutstore/Research/BEE_Lab/homepage/ref.md
   ```
* Add an option to specify the `fileformat` when saving the Startify session. As long as we can force `set ff=unix` per each saving attempt, the saved "session file" could be used by whatever OS?

PS: per my understanding of how sessions are saved, I call files that I store in `startify_session_dir` as "session files".

**Comment by mhinz** [comment]
Except for `'sessionoptions'` I can't alter how sessions get saved. For both points you mentioned one would have to open/edit/save/close them again. It's also not guaranteed that the session file used a relative path as in your example. That would always be an ugly hack.

I consider this use case as uncommon enough so that it doesn't warrant the time  for new code. The cost-benefit isn't worthwhile here.

Especially since this plugin is not a full-fledged plugin for managing sessions, but it provides a start screen and using its session saving capabilities are just a way to easily save all sessions to the same directory, so that Startify can list them in the start screen.

Thanks for bringing this up anyway! ✨
