### ISSUE TITLE
Make numbering behaviour more customizable

### ISSUE THREAD

**Issue by BenjaminBrandtner** [mhinz/vim-startify#338]
I'd like to have the startify lists in the following order: bookmarks, sessions, files (MRU)

In this case the numbering from 0 begins at the first bookmark that doesn't have a custom index, or if they all do, at the first session. Example:
```
   Bookmarks

   [cs] $OneDrive\C#\C# Notizen\Index.md
   [java]$OneDrive\Java\Java Notizen\Index.md
   [rc] $MYVIMRC

   Sessions

   [0]  Ratespiel
   [1]  Tierheim

   MRU

   [2]  $HOME\vimfiles\pack\readme.md
   [3]  $HOME\dotfiles\.gitignore

   ...
```
In my opinion it would be better if the numbering always started with the files-list, so the most recently used file can always be reached by pressing 0 (mimicking the behaviour of `:browse old`).

If there were three variables for custom indices, like `g:startify_custom_indices_files`, `g:startify_custom_indices_dir` and `g:startify_custom_indices_bookmarks` the user could customize the numbering behaviour just the way they like it.

Edit: I have to ask... 
https://github.com/mhinz/vim-startify/blob/556bf1d507dfaddfba4b5795716ea20f8ba902ac/autoload/startify.vim#L45
Why is this function named the way it is? :^)

**Comment by BenjaminBrandtner** [comment]
Yeah, that sounds a lot better than my suggestion. I like it.
I suppose it would deprecate the `g:startify_custom_indices` option?
<hr>

I know the song. So you liked it so much you decided to name a function after it?

**Comment by mhinz** [comment]
> I suppose it would deprecate the g:startify_custom_indices option?

Sometimes you notice things only when you start implementing them, but yeah, I guess so. :) I'll whip up a PR this weekend.

> So you liked it so much you decided to name a function after it?

Honestly? I don't remember why I did it. I probably just tried to be funny and do something unusual. The function used to be called `start()` in the beginning, but I changed it early on (almost 6 years ago): https://github.com/mhinz/vim-startify/commit/c91cfb2

**Comment by mhinz** [comment]
@BenjaminBrandtner Would be cool if you could test the above PR. Should be working as mentioned above.

**Comment by BenjaminBrandtner** [comment]
It works as expected when you start up vim, but when you execute `:Startify` afterwards the numbering goes back to all numbers.

This is in my vimrc:
```vim
let g:startify_lists = [
          \ { 'type': 'bookmarks', 'header': ['   Bookmarks']      },
          \ { 'type': 'sessions',  'header': ['   Sessions'],	'indices': ['A','B','C']      },
          \ { 'type': 'files',     'header': ['   MRU']		   },
          \ { 'type': 'commands',  'header': ['   Commands']       },
          \ ]
```

When I check the contents of `g:startify_lists` after starting vim (still on the Startify screen) it says the indices list is empty.

```vim
g:startify_lists      [{'header': ['   Bookmarks'], 'type': 'bookmarks'}, {'indices': [], 'header': ['   Sessions'], 'type': 'sessions'}, {'header': ['   MRU'], 'type': 'files'}, {'header': ['   Commands'], 'type': 'commands'}]
```

**Comment by mhinz** [comment]
Ah, it should have been..

```diff
diff --git i/autoload/startify.vim w/autoload/startify.vim
index 8e28021..479058b 100644
--- i/autoload/startify.vim
+++ w/autoload/startify.vim
@@ -457 +457 @@ function! s:show_lists(lists) abort
-    let b:startify.indices = get(list, 'indices', [])
+    let b:startify.indices = get(deepcopy(list), 'indices', [])
```

...because in this case `list` is a pointer into one of the hashes from `g:startify_lists`.

It should work now!

**Comment by BenjaminBrandtner** [comment]
Works great, `g:startify_custom_indices` still works as well.

Why is the `[B]` index highlighted differently, though? It has the highlightgroup `StartifySelect` instead of `StartifyNumber`. It's like in the screenshot in your readme. Not really a problem, just wondering.

**Comment by mhinz** [comment]
Merged! Thanks for bringing this up. :sparkles:
