### ISSUE TITLE
Opening file/session stacks up nerdtree + ctrlp

### ISSUE THREAD

**Issue by n1-cz** [mhinz/vim-startify#340]
If i open a file from MRU file or a session on startify page it gets loaded well. The thing is it changes current working dir (or something else silimar to this) to the directory of the file or of last focused file in the session. The result is NERDTree is in project nested directory instead of root but more importantly CtrlP plugin doesn't work properly. It cannot find any files nor tags because my `tags` file is in the project root.

Anything I or you can do about that? Need more info?

Thank you.

**Comment by mhinz** [comment]
Hi,

Yes, by default Startify changes to the directory of any opened file. You can disable that with:

```vim
let g:startify_change_to_dir = 0
```

Personally, I have a small custom code that automatically changes the working directory to that of an given repository, which is almost always also the root of the project.

I figured this could be useful to many people, so I added something similar to Startify as well. Enable it with:

```vim
let g:startify_change_to_vcs_root = 1
```

The above options don't work for session, though. Sourcing (loading) a session means simply running the commands written to a session file. How that session file is created depends on `:h 'sessionoptions'`. So, when your working directory is set to the root of the project when you save the session, it should also switch to the directory if you source the session.

**Comment by n1-cz** [comment]
Thank you. The first command works well!
