### ISSUE TITLE
E194: No alternate file name to substitute for '#'

### ISSUE THREAD

**Issue by FocusedWolf** [mhinz/vim-startify#346]
I have a '#' in my file path and it seems to be causing issues.
In the screenshot i'm trying to open the [2] file.
![startify error 2018-12-07 155221](https://user-images.githubusercontent.com/1034773/49672710-07296280-fa3a-11e8-83e5-fe2951630b50.png)

**Comment by mhinz** [comment]
Hi,

Thanks for the report. I can reproduce it on my Win 10 VM. Escaping on Windows is hell: https://github.com/vim/vim/issues/541

I'll look into finding a solution that doesn't break for non-Windows systems.

**Comment by mhinz** [comment]
Hey, it should be fixed now.

Please play around with different paths (and maybe another `'shellslash'` value) and see if you can break things! :)
