### ISSUE TITLE
Spaces not transparent with custom header

### ISSUE THREAD

**Issue by Brottweiler** [mhinz/vim-startify#348]
For some reason, the spaces *after* the characters in my custom show as red like this.
![image](https://user-images.githubusercontent.com/1613137/50408257-b2326e00-07e7-11e9-833a-bc07de72668a.png)

Here's the snippet:

```bash
let g:startify_custom_header=[
    \ '                    .                    ',
    \ '    ##############..... ##############   ',
    \ '    ##############......##############   ',
    \ '      ##########..........##########     ',
    \ '      ##########........##########       ',
    \ '      ##########.......##########        ',
    \ '      ##########.....##########..        ',
    \ '      ##########....##########.....      ',
    \ '    ..##########..##########.........    ',
    \ '  ....##########.#########.............  ',
    \ '    ..################JJJ............    ',
    \ '      ################.............      ',
    \ '      ##############.JJJ.JJJJJJJJJJ      ',
    \ '      ############...JJ...JJ..JJ  JJ     ',
    \ '      ##########....JJ...JJ..JJ  JJ      ',
    \ '      ########......JJJ..JJJ JJJ JJJ     ',
    \ '      ######    .........                ',
    \ '                  .....                  ',
    \ '                    .                    ',
    \ ]
```

What can cause this? My init.vim is here https://gist.github.com/77d6dc1e5c3fea78666761759da0a633

**Comment by Brottweiler** [comment]
I just removed the spaces before the `',` part, they probably shouldn't be there anyway.

**Comment by mhinz** [comment]
> I just removed the spaces before the ', part, they probably shouldn't be there anyway.

That's one way to work around it. ;-)

It usually happens for either of these two reasons:

1. The search register is set to something like `\s*$` (not necessarily by you, but by any of your plugins) and `'hlsearch'` is enabled. (Try it yourself: Do `:set hlsearch`, add a few spaces to the end of a line and do `/\s*$<cr>`. The red color you see stems from `:hi Search`.)
2. `'listchars'` is shows trailing spaces. (`:let &listchars = 'trail: '` and `:hi Whitespace ctermbg=red`.)

**Comment by Brottweiler** [comment]
Oh you know what, I have `ntpeters/vim-better-whitespace'` installed and it confused me, because since the whitespaces are *before* the `',`, i thought it was fine, which it is, but only in the config. As much as the plugin cares about vim-startify, it thinks startify is a regular file im editing, and there's trailing whitespaces after the ASCII art.

It confused me because I didn't expect, for whatever reason, it to affect vim-startify, especially when it's fine in the config. But it makes sense now!

**Comment by Brottweiler** [comment]
That is probably the best solution, what you just provided, because startify is nothing I edit anyway. Thank you!
