### ISSUE TITLE
q from menu does not quit (like after a tab open/close ...)

### ISSUE THREAD

**Issue by mckellyln** [mhinz/vim-startify#349]
Hi,
Thank you for awesome startify !
One minor issue I would like to ask about, if I start vi and get the startify menu and then I create a new tab, do something in that tab, and then close that tab - I am back at the startify menu, but then a 'q' does not quit but leaves me at a "[No Name]" --No lines in buffer-- 
I am wondering if it is some setting in my .vimrc or if I can change 'q' to quit even if there are buffer(s) that have no data and do not need to be saved ?
thx,
-m

**Comment by mckellyln** [comment]
ok, I may have found a way to solve my issue by changing a vim setting:
set nohidden
And now it seems the hidden empty buffer is no longer there after a tabclose and 'q' in startify menu really quits.
I am not sure why I had hidden set, will need to check all my other plugins.
But thank you again for great startify,
-m

**Comment by mhinz** [comment]
> Thank you for awesome startify !

:-)

I consider this mostly a documentation bug. `q` always meant to quit the Startify buffer, not necessarily Vim itself. It only does so, if after closing the Startify buffer there would be no other _listed_ Vim buffer to switch to: https://github.com/mhinz/vim-startify/blob/9c26c7e8dcee2e580f137610ccde1af40a19d2bb/autoload/startify.vim#L917-L927

For reference: `:h unlisted-buffer`.

A lot of people have `'hidden'` set. It keeps you from having to save changes all the time when working in multiple buffers at the same time.

I think this happened:

```
$ vim
(shows startify buffer)
:tabedit ~/.vim/vimrc
:bd
(You're now in an empty _listed_ buffer in the second tab. The buffer list is global, so you can access this empty buffer from the first tab as well.)
:set hidden
:tabclose
(Back at Statify buffer. If you now hit `q`, there is stil the one empty buffer and Startify will switch to it.)
```

If you would have used `:set nohidden` instead, the empty buffer would have been _abandoned_ on `:tabclose`. So, back in the Startify buffer, there would be no other listed buffer left and `q` would quit.

For reference: `:h 'hidden'` and `:h abandon`.

I hope this sheds some light on what was happening!

**Comment by mckellyln** [comment]
Thanks so much
