### ISSUE TITLE
vimtips rather than quotes

### ISSUE THREAD

**Issue by sanga** [mhinz/vim-startify#350]
Feel free to close this is you like but I thought I'd mention it in any case. Whilst I like the quotes (I always read them and often find them informative or entertaining) I was wondering if one might optionally rather include some tip on vim usage. For example excerpt from your own vim-galore repo. It's possible that I'm biased as I'm a medium-term vim user but I feel like vim is sufficiently complex that basically any user would still have things to learn. Anyway, just a random suggestion, feel free to close and thanks for creating this.

**Comment by mhinz** [comment]
That's actually a big task! Creating a list of diverse tips is much harder than finding popular quotes on the internet. ;-) And currently I don't want to invest time into that.

But maybe someone wants to create a plugin (`vim-startify-vimtips`?) that simply sets `:h g:startiy_custom_header_quotes` to a list of, well, Vim tips. Then, when both plugins are installed, Startify would automatically show the tips without any change in the vimrc needed. (Well, except maybe for adding a line for a plugin manager.)

Anyway, I'm glad you're liking the plugin!
