### ISSUE TITLE
Slow or no startup when files on a remote (SMB) directory have been accessed

### ISSUE THREAD

**Issue by jackgu1988** [mhinz/vim-startify#353]
On Linux, when I try to start vim and have in my history remote files (SMB), the start-up time becomes very slow (increasingly slow, depending on how many remote files are in the history).

When the remote files are not accessible (e.g. there is no internet connection any more), vim just hangs and does not open at all.

A similar issue has been reported on Windows (https://github.com/mhinz/vim-startify/issues/199), but since it is closed and the workaround does not work for me on Linux, I am opening a new one.

**Comment by mhinz** [comment]
How does the `g:startify_skiplist` approach does not work for you?

**Comment by jackgu1988** [comment]
I tried:
```
let g:startify_skiplist = [
 			\ '/run/user/1000/gvfs/.*', " The dir where the folder mounts
 			\ ]
```
and even though the remote files do not show in the list, when (and if) vim loads, it does not solve the speed issue. It seems as if it is still reading them, but just does not present them.

I also tried in combination with `let g:startify_enable_unsafe = 1`, which makes it faster when the remote directory is not available, but no change when it is not.

**Comment by mhinz** [comment]
Oh, does it help if you simply swap these two lines?

https://github.com/mhinz/vim-startify/blob/69e835d1f779140f7c0a27f6fd30ae4d1f9dac77/autoload/startify.vim#L556-L557

**Comment by jackgu1988** [comment]
Nothing changed. It might not be the only place where it reads the files maybe? (I also changed lines 606-609)

I am using vim-plug so I edited `$HOME/.vim/plugged/vim-startify/autoload/startify.vim`.

The files are hidden, so I indeed have the correct `g:startify_skiplist`.

Also, `<C-c>` does not stop it.

**Comment by mhinz** [comment]
Do you start Vim outside of `/run/user/1000/gvfs`?

**Comment by jackgu1988** [comment]
Yes, I start it from my home directory.

**Comment by mhinz** [comment]
> I also tried in combination with `let g:startify_enable_unsafe = 1`, which makes it faster when the remote directory is not available, but no change when it is not.

You mean it makes it faster when the remote directory is available? Because otherwise it would hang?

When not using `g:startify_enable_unsafe`, the only I/O access I see when wading through the code processing `v:oldfiles`, is the small change I mentioned above and the use of `resolve()` 2 lines above it.

These are my best guesses when going through the code manually. I'll try to find a way to emulate a slow file system under macOS.

**Comment by jackgu1988** [comment]
> You mean it makes it faster when the remote directory is available? Because otherwise it would hang?
Exactly.

I figured that the problem is here: `let absolute_path = glob(fnamemodify(fname, ":p"))` (lines 553 and 604). If I hardcode some value there it is not slow.

Also, when I comment out the for loop that is underneath, without altering this specific line, the problem persists.

**Comment by jackgu1988** [comment]
When I `ls` into `/run/user/1000/gvfs`, it takes a few seconds before it responds that there is a problem. It seems like a bug. This must be slowing down `fnamemodify()`.

**Comment by jackgu1988** [comment]
Adding an if statement fixes the issue, however it mostly looks like a workaround and will probably cause other issues for many users.

Anyway, I am pasting it here:

```
    if  !s:is_in_skiplist(fname)
      let absolute_path = glob(fnamemodify(fname, ":p"))
      if empty(absolute_path)
            \ || has_key(entries, absolute_path)
            \ || (absolute_path =~ is_dir)
            \ || match(absolute_path, path_prefix)
            \ || s:is_in_skiplist(absolute_path)
        continue
      endif

      let entry_path              = fnamemodify(absolute_path, a:path_format)
      let entries[absolute_path]  = 1
      let counter                -= 1
      let oldfiles               += [[fnameescape(absolute_path), entry_path]]
    endif
```

**Comment by mhinz** [comment]
Should be fixed now. Thanks for bringing this up!

**Comment by jackgu1988** [comment]
Thanks a lot! It works fine after updating :)
