### ISSUE TITLE
Error detected while processing function <SNR>87_get_session_path

### ISSUE THREAD

**Issue by talysonleocadio** [mhinz/vim-startify#356]
Hello, @mhinz how are you doing?

I installed vim-startify using vim-plug as descripted on documentation.

On neovim startup an error appears as the following message:

> Error detected while processing function <SNR>87_get_session_path:                                                                                                                                                                            
line    4:
E117: Unknown function: stdpath
Press ENTER or type command to continue

Below is my neovim version:

> NVIM v0.2.2
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -g -O2 -fdebug-prefix-map=/build/neovim-_mzR4z/neovim-0.2.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -DDISABLE_LOG -Wdate-time -D_FORTIFY_SOURCE=2 -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -O2 -g -DMIN_LOG_LEVEL=3 -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/build/neovim-_mzR4z/neovim-0.2.2/build/config -I/build/neovim-_mzR4z/neovim-0.2.2/src -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/build/neovim-_mzR4z/neovim-0.2.2/build/src/nvim/auto -I/build/neovim-_mzR4z/neovim-0.2.2/build/include
Compiled by pkg-vim-maintainers@lists.alioth.debian.org
Features: +acl +iconv +jemalloc +tui 
system vimrc file: "$VIM/sysinit.vim"
fall-back for $VIM: "/usr/share/nvim"

Can you help me?

Thank you.

**Comment by mhinz** [comment]
Hi,

Opposed to Vim users, I expect Nvim users to have rather up-to-date version. You're using v0.2.2, but the current one is v0.3.4 and there were ~2500 patches since then. Please update your Nvim. 

...oh, this is Nvim from [strech-backports](https://packages.debian.org/search?keywords=neovim&searchon=names&suite=all&section=all), eh?

I'll hardcode the proper path for older versions.
