### ISSUE TITLE
Feature Request: Session lock files are displayed in the list

### ISSUE THREAD

**Issue by talha131** [mhinz/vim-startify#361]
Thanks a for creating and maintaining this plugin. It has been very useful. 

I mainly use it to display my sessions at launch time. I have noticed if a session is open in another instance, then startify displays it as `.lock` in the list. For example,

```
   [e]  <empty buffer>

   Sessions

   [0]  bmtool.vim
   [1]  connect.vim
   [2]  default.vim
   [3]  dotfiles.vim
   [4]  jump-viewer-mac.vim
   [5]  jvm-logs.vim
   [6]  lms-admin.vim
   [7]  lms-client.vim
   [8]  neuron-frontend.vim
   [9]  neuron-frontend.vim.lock
   [10] neuron.vim
   [11] tiddly-wiki-scripts.vim
```

Notice the `.lock` file at number 9. It affects the musle memory. I know my dotfiles session is at 3. So I could quickly launch the Vim and then press 3 to get into dotfiles session. But the presence of lock files affects the order.

Is it possible to have following features

1. Not show `.lock` files in the list?
2. Sessions that are already opnened are displayed with a `*` or "already open" in front of their names

**Comment by mhinz** [comment]
Where are these lock files coming from? That's not a Startify thing.

**Comment by talha131** [comment]
Thank you @mhinz. I looked into my plugins and discovered that [vim-session](https://github.com/xolox/vim-session) plugin creates lock files.

I will probably remove it and use Startify to manage my sessions.
