### ISSUE TITLE
List of all dirs containing a git repo

### ISSUE THREAD

**Issue by Jomik** [mhinz/vim-startify#363]
I would like to be able to add a section to my startify that showed all my project roots in `~/projects`.
That is I will need to crawl into the subdirectories, looking for `.git`.
I have some projects directly in `~/projects/X` but some may be in a sub directory `~/projects/category/X`.

I realize I should use `startify_lists`, my issue is writing the function to return the dictionary as I am a complete vimscript newb.

**Comment by mhinz** [comment]
Searching _forward_ is an expensive operation, so it might be better to just hardcode your favourite projects via `:h g:startify_bookmarks`.

Anyway, here's a possible solution (I took my own projects directory as example):

```vim
function! s:list_projects() abort
  return map(finddir('.git', '/data/github/**', -1),
        \ {_, dir -> {'line': fnamemodify(dir, ':h:t'), 'path': fnamemodify(dir, ':h')}})
endfunction

let g:startify_lists = [{'header': ['Projects'], 'type': function('s:list_projects')}]
```

Hope this helps!

**Comment by Jomik** [comment]
That looks like what I need, I sort of want to avoid the ** glob, as that would search into subdirs of an already found project. I will need with that function of yours and update this for others. Thank you!

**Comment by mhinz** [comment]
It sounds as if limiting the depth to 2 or 3 directories would be good enough in your case?

Because I just learned that you can do that via `**2` or `**3` (`:h file-searching`).

**Comment by Jomik** [comment]
That is amazing!

**Comment by Jomik** [comment]
Modified it a bit, it shows category and project.

I just realized that pointing at a dir, instead of a file gives me an empty buffer. So I suppose it'd make more sense, in my case, to call Defx.

So I end up with this as my final solution. Thanks a lot @mhinz  :)

```
function! s:list_projects() abort
  return map(finddir('.git', $HOME . '/projects/**2', -1),
        \ {_, dir -> {'line': fnamemodify(dir, ':h:s?.*projects/??'), 'cmd': 'Defx ' . fnamemodify(dir, ':h')}})
endfunction

let g:startify_lists = [
      \ {'header': ['   Projects'], 'type': function('s:list_projects'), 'indices': map(range(1, 100), { _ -> 'p' . string(v:val)})}
      \ ]

```
