### ISSUE TITLE
Does not change to directory

### ISSUE THREAD

**Issue by Jomik** [mhinz/vim-startify#364]
When I select any of the files from my bookmark, my cwd is not actually changed to the directory of the file.
It works if I disable `change_to_vcs_root`.

I would expect it to first try to change to the vcs root, and if it does not exist, then change to the file dir.

```vim
let g:startify_change_to_vcs_root = 1
let g:startify_change_to_dir = 1

let g:startify_bookmarks = [
      \ {'v': '~/.config/nvim/init.vim'},
      \ {'n': '~/.config/nixpkgs/home.nix'}
      \ ]
```

**Comment by Jomik** [comment]
You are too quick :laughing:

**Comment by mhinz** [comment]
:) Thank you for finding these bugs! ✨
