### ISSUE TITLE
Double click opens a session one row below

### ISSUE THREAD

**Issue by noscript** [mhinz/vim-startify#365]
**To reproduce:**
Double click in the middle of the row where the cursor currently is.

**Expected:**
The session, where the cursor is, gets opened.

**Actual:**
Session one row below opens.

The problem basically happens when I first click some row, and then decide to double click it. Actual line jump occurs in `s:set_cursor()`, if cursor column is not the most left, which can be due to clicking somewhere in the middle of the row. I don't know the reasons for such logic, but I came up with a workaround. It will prevent `s:set_cursor()` from doing the line jump by correcting the column after click:

```diff
diff --git autoload/startify.vim autoload/startify.vim
index abd7b6c..6ba6f48 100644
--- autoload/startify.vim
+++ autoload/startify.vim
@@ -819,9 +819,15 @@ function! s:set_mappings() abort
   nnoremap <buffer><nowait><silent> t             :call <sid>set_mark('T')<cr>
   nnoremap <buffer><nowait><silent> v             :call <sid>set_mark('V')<cr>
   nnoremap <buffer><nowait><silent> <cr>          :call startify#open_buffers()<cr>
+  nnoremap <buffer><nowait><silent> <LeftMouse>   :call <sid>process_click()<cr>
   nnoremap <buffer><nowait><silent> <2-LeftMouse> :call startify#open_buffers()<cr>
   nnoremap <buffer><nowait><silent> <MiddleMouse> :enew <bar> execute 'normal! "'.(v:register=='"'?'*':v:register).'gp'<cr>

+  function! s:process_click()
+    call getchar()
+    call cursor(v:mouse_lnum, s:fixed_column)
+  endfunction
+
   " Without these mappings n/N wouldn't work properly, since autocmds always
   " force the cursor back on the index.
   nnoremap <buffer><expr> n ' j'[v:searchforward].'n'
 ```

**Comment by mhinz** [comment]
Huh, just single clicking on the same spot (with more than `:h 'timeoutlen'` between the clicks), makes the cursor alternate between the either the line above or below depending on whether the spot is left or right of the current line's index.

Looking into it!

**Comment by mhinz** [comment]
The problem lies here: https://github.com/mhinz/vim-startify/blob/c758d2a79ae0e4b8602e09834800ed0b3d71d0fe/autoload/startify.vim#L777-L779

This is used to move the cursor to the prev/next line for motions that don't change the line. E.g. `h` goes to the previous line and `w` to the next. Also https://github.com/mhinz/vim-startify/issues/294.

For a moment I pondered just removing that condition, because 95% of the users probably just use `j`/`k` and friends anyway. But then again, I don't want to regress and your suggestion does the job.

Will you make a PR for it or should I just merge your patch myself?

**Comment by noscript** [comment]
The problem with my workaround is that there is a blinking in command line when you click, maybe I don't do some kind of extra `silence`. But otherwise feel free to merge yourself :)

**Comment by mhinz** [comment]
You're totally right. I didn't notice that `getchar()` makes the cursor move to the command-line to wait for input, although the input is already there.

Anyway, Vim plugins (and especially the ones that try to display menus by abusing simple text buffers...) are just collections of workarounds.

...and the above patch adds another one! Should be fixed now.
