### ISSUE TITLE
StartifyAllBuffersOpenend does not fire

### ISSUE THREAD

**Issue by aforino** [mhinz/vim-startify#366]
I want to restart the YCM server once all buffers of a saved session are opened. Opening of the session happens normally over the startify "landing page". I put this line in .vimrc:

`autocmd User StartifyAllBuffersOpened YcmRestartServer`

However, this event never fires but no errors are generated. The same command works with the `StartifyReady` event. The same command generates an error with the `StartifyBufferOpened` event: 

`E216: No such group or event: <nomodeline> User StartifyBufferOpened`

Additional line regarding startify in .vimrc that may be of interest:

`let g:startify_change_to_dir =1`

**Comment by mhinz** [comment]
The above patch should fix the error message, but mind that `StartifyBufferOpened` and `StartifyBuffersOpened` are only emitted for buffers opened from the Startify buffer.

When you want to do something after loading a session, have a look at `:h SessionLoadPost`.
