### ISSUE TITLE
E484 after GVIM update

### ISSUE THREAD

**Issue by blayz3r** [mhinz/vim-startify#368]
After updating my vim version I am getting the error below:

E484: Can't open file C:\Users\....\AppData\Local\Temp\VIoCC2F.tmp

I am using GVIM on windows with the WSL subsytem. It looks like the way the escape sequences work has changed.

Line 645:
let g:startify_custom_header =
            \ map(split(system('fortune -s'), '\n'), '" ". v:val') + [''] 

![2019-04-30_0-35-40](https://user-images.githubusercontent.com/12205650/57106865-790d8b80-6cfc-11e9-8cc0-8e008d60e350.png)
![2019-04-30_0-29-48](https://user-images.githubusercontent.com/12205650/57106867-7ad74f00-6cfc-11e9-9332-8158f89aa40f.png)

Messages:
![2019-05-02_17-34-26](https://user-images.githubusercontent.com/12205650/57108406-a2301b00-6d00-11e9-980f-766f1a4f6d1b.png)
Startify still works though so that makes weirder

**Comment by mhinz** [comment]
Maybe it's the `system()` that fails? I never used WSL. Does `fortune` exist there?

**Comment by blayz3r** [comment]
I don't think WSL should affect it much. It was working fine before .
As per https://github.com/mhinz/vim-startify/issues/165
_**echo system('ls')**_ works fine and

_**:echo &shell &shellcmdflag &shellxquote shellescape('some command') &shellredir tempname() &shellxquote**_

Shows:
![image](https://user-images.githubusercontent.com/12205650/57108737-a1e44f80-6d01-11e9-9559-169dedfa45bf.png)

**Comment by mhinz** [comment]
So, what's the output of `:echo map(split(system('fortune -s'), '\n'), '" ". v:val')`?

**Comment by mhinz** [comment]
> :echo &shell &shellcmdflag &shellxquote shellescape('some command') &shellredir tempname() &shellxquote

The image looks as if `&shellxquote` is `(`? So the command ends with `(`? That doesn't look right.

**Comment by mhinz** [comment]
And honestly, maybe there's nothing you can do about it. It smells like a Vim bug. You're using a master version after all. :)

I'd try updating in the next days or just use the last known stable version, 8.1.996 in your case.

**Comment by blayz3r** [comment]
Cool I'll close it.
