### ISSUE TITLE
Conflicts with vim-go

### ISSUE THREAD

**Issue by jinleileiking** [mhinz/vim-startify#372]
when I click `ctrl + ]` cmdline shows `no room for queue`

**Comment by mhinz** [comment]
Startify doesn't map `<c-]>` and vim-go shouldn't set mappings for buffers where the filetype is not `go`.

**Comment by jinleileiking** [comment]
It really got some problems with vim-go. 

`no room for queue` and `vim-go: no file information for file:///da nte/quic-go/stream.go`

**Comment by mhinz** [comment]
Why are you using `<c-]>` anyway? This plugin doesn't have such a mapping.
