### ISSUE TITLE
can user add content to startify?

### ISSUE THREAD

**Issue by fgheng** [mhinz/vim-startify#376]
hello, i want to show some commands in common use to the startify, just like PlugUpdate..., and when i choose it, it can execute this command, does startify support it?

**Comment by mhinz** [comment]
Hi,

Yup, see `:h g:startify_commands`. E.g.

```vim
let g:startify_commands = [
      \ 'help',
      \ ['Update plugins', 'PlugUpdate']
      \ ]
```
