### ISSUE TITLE
Loading saved sessions from commandline: what is the magic marker?

### ISSUE THREAD

**Issue by llinfeng** [mhinz/vim-startify#378]
I wonder what is the magic syntax to achieve the following command in Vim through the command line?
![image](https://user-images.githubusercontent.com/5890407/60895550-dbba6080-a232-11e9-9741-fcc408c0b40a.png)

I tried to issue the following command, but can only get a Vim window with an empty buffer named `wiki`, and a prompt that is asking for the session name:
```
gvim -c :SLoad wiki
```

I tried to wrap things around `"wiki"`, but none of the following markers helped: 
![image](https://user-images.githubusercontent.com/5890407/60895888-63a06a80-a233-11e9-85d8-aa90a67e5372.png)

**Comment by mhinz** [comment]
You have to quote the whole argument for `-c`:

    gvim -c 'SLoad wiki'
