### ISSUE TITLE
Error detected while processing .../.vim/session/tests

### ISSUE THREAD

**Issue by AUsernameWhichIsNotTaken** [mhinz/vim-startify#381]
No matter what session I open I always get this error (of course with changing session name 'tests').  In this case it was:

line   99:
E517: No buffers were wiped out: bwipe 2

The line in question from ~/.vim/session/tests

<pre>
 98 if exists('s:wipebuf') && len(win_findbuf(s:wipebuf)) == 0
 99   silent exe 'bwipe ' . s:wipebuf
100 endif
</pre>

would '!' attached to silent solve this issue?  How would I get it there?

Thank you for this useful plugin!

**Comment by mhinz** [comment]
You can't add anything to it. Session files get generated by Vim itself. 

- What Vim version is this? Can you try a more recent version in case it was a Vim bug and got fixed already?
- What is the output of `:set ssop?` (don't forgot the trailing `?`)

(And for testing purposes, please disable any other plugins to make sure they're not interfering somehow.)

**Comment by mhinz** [comment]
Since this is not an issue with Startify itself, but Vim, I'm closing this. This is most probably fixed by upgrading Vim to a more recent version.

But feel free to ask further questions here!
