### ISSUE TITLE
Terminal Window not closing on :SClose

### ISSUE THREAD

**Issue by rationalis-petra** [mhinz/vim-startify#382]
Hi,
Recently installed Startify, and I often have sessions where I run a terminal in one tab from within neovim. When I use `SClose`, it closes the session and returns to the Startify homepage, as expected. When I press `q` to leave, however, instead of exiting neovim, it swaps to the terminal within neovim. If I instead use `:q` to exit, then this issue is not present.

**Comment by mhinz** [comment]
That's interesting. Eventually `:SC` uses `:%bdelete` to delete all buffers, but that won't work with terminal buffers.

Try it yourself:

```
$ nvim
:exe 'term' | %bdelete
E89: term://.//35178:/usr/local/bin/zsh will be killed(add ! to override)
```

I'll add the missing `!`.

Thanks for letting me know! ✨
