### ISSUE TITLE
Question: where do the amazing quotes come from ?

### ISSUE THREAD

**Issue by MartyLake** [mhinz/vim-startify#385]
I really **love** all the quotes when opening vim. When I cam, I force myself to just `vim`, then `:e my_file` just to see a quote. :)

**Comment by Andilutten** [comment]
@MartyLake I'm not sure , but i think it's something like [Fortune](https://wiki.archlinux.org/index.php/Fortune)

**Comment by mhinz** [comment]
🙏 

Startify doesn't rely on an external fortune/cowsay tool and has its own implementation: https://github.com/mhinz/vim-startify/blob/master/autoload/startify/fortune.vim

There are a lot of tech/programming quotes all over the internet and I collected them from several sources over time. Just search for _popular programming quotes_ etc.

And some quotes were added later on by other people. But please do not create PRs for adding even more quotes. We have enough already. :) See `:h g:startify_custom_header_quotes` instead.

Or you just build the whole header yourself, using `:h startify_custom_header`.


Hope that helps!
