### ISSUE TITLE
vim working directory change when open from MRU

### ISSUE THREAD

**Issue by pwang2** [mhinz/vim-startify#387]
When opening files from MRU, it seems it overrides `set noautochdir`, is it by design?

**Comment by mhinz** [comment]
The default behaviour of changing the directory is separate from `'autochdir'`.

Use [`let g:startify_change_to_dir = 0`](https://github.com/mhinz/vim-startify/blob/master/doc/startify.txt#L365-L370) instead.

**Comment by pwang2** [comment]
Thanks for help, I should have read the docs first.
