### ISSUE TITLE
Unidentified unicode characters in files listing with neovim

### ISSUE THREAD

**Issue by iTZAvishay** [mhinz/vim-startify#389]
Hey!

I've started using startify with [this dotfile](https://github.com/nicknisi/dotfiles/blob/master/config/nvim/init.vim) and my startify screen looks like this ![startify](https://i.imgur.com/4kirkax.png)

All of the unidentified unicode characters can be replaced with a simple `~/`, I am not sure what causes them to print, I tried installing the [Hack Nerd Font](https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts/Hack) but the result is the same.

The relevant startify section in my `init.vim`:
```
" Startify: Fancy startup screen for vim {{{
        Plug 'mhinz/vim-startify'

        " Don't change to directory when selecting a file
        let g:startify_files_number = 5
        let g:startify_change_to_dir = 0
        let g:startify_custom_header = [ ]
        let g:startify_relative_path = 1
        let g:startify_use_env = 1
        let g:webdevicons_enable_startify = 1

        let g:startify_lists = [
        \  { 'type': 'dir',       'header': [ 'Files '. getcwd() ] },
        \  { 'type': 'sessions',  'header': [ 'Sessions' ]       },
        \  { 'type': 'bookmarks', 'header': [ 'Bookmarks' ]      },
        \  { 'type': 'commands',  'header': [ 'Commands' ]       },
        \ ]

        let g:startify_commands = [
        \   { 'up': [ 'Update Plugins', ':PlugUpdate' ] },
        \   { 'ug': [ 'Upgrade Plugin Manager', ':PlugUpgrade' ] },
        \ ]

        let g:startify_bookmarks = [
            \ { 'c': '~/.config/nvim/init.vim' },
            \ { 'g': '~/.gitconfig' },
            \ { 'z': '~/.zshrc' }
        \ ]

        autocmd User Startified setlocal cursorline
        nmap <leader>st :Startify<cr>
    " }}}

```

Any help is appreciated, thank you!

**Comment by mhinz** [comment]
It's most probably a font problem.

The [unicode symbols come from the vim-devicons plugin](https://github.com/ryanoasis/vim-devicons/blob/master/plugin/webdevicons.vim#L129) (enabled through `let g:webdevicons_enable_startify = 1`). :)

**Comment by iTZAvishay** [comment]
That's the thing - it still happens when this line is omitted (it wasn't present at first) and I added it to try and resolve the issue - which didn't help.

**Comment by iTZAvishay** [comment]
Anyway, I didn't get to pinpoint what exactly caused it - but I removed the NerdTree portion in the original init.vim and everything is well now, hopefully it might help to other people.

Thanks anyway mhinz!

**Comment by mhinz** [comment]
Well, looking at the paths in your screenshot, you can see the full relative path, so something with unicode got prepended.

See `:h startify-misc`.

You should be able to find out what set it by doing `:verb func StartifyEntryFormat`.

**Comment by mhinz** [comment]
BTW, I closed this because I'm pretty sure it's not an issue with this plugin, but feel free to ask further questions!
