### ISSUE TITLE
remap bstv

### ISSUE THREAD

**Issue by Freed-Wu** [mhinz/vim-startify#390]
I don't like b,s,t,v. Can I remap bstv? I find you use <SID> make it cannot to realize. Thank you.

**Comment by mhinz** [comment]
You can hook into the `User Startified` event. E.g.

```vim
autocmd User Startified call s:on_startify()

function! s:on_startify()
  nnoremap <buffer> b :echomsg "B!"<cr>
  " ...
endfunction
```

**Comment by Freed-Wu** [comment]
Oh, I wanna know how to use other key to replace bstv, it looks hard because the bstv use <SID> , thank you.

**Comment by mhinz** [comment]
Oh! I see. Let me change them to autoload functions.

**Comment by mhinz** [comment]
You can now use this for example:

```vim
autocmd User Startified call s:on_startify()

function! s:on_startify()
  nnoremap <buffer> x :call startify#set_mark('B')<cr>
endfunction
```
