### ISSUE TITLE
Can't read cowsay because of wrong cursor position.

### ISSUE THREAD

**Issue by danbruegge** [mhinz/vim-startify#391]
Hi, on nvim start i can't read the cowsay sentences anymore. How can i fix this? Looks like the cursor position isn't at top, which is not a problem. But would be nice to read cowsay without hitting `gg`. ;)

![vim-startifiy-position](https://user-images.githubusercontent.com/1296438/65220994-510ca200-dabc-11e9-928e-91874b33af22.png)

**Comment by mhinz** [comment]
It now does `zb` after starting, which makes the current line the bottom line of the window. That way, you should see as much of the header as possible.

Grüsse ins Havelland!

**Comment by danbruegge** [comment]
Nice. Can verify that is working. Thanks. :)

Grüße zurück nach Potsdam. :)
