### ISSUE TITLE
Plugin not autostarting

### ISSUE THREAD

**Issue by Miziak** [mhinz/vim-startify#395]
Like in title plugin not autostart for me but when I type :Startify it works. Can you provide some information how to debug it?

Thanks!

**Comment by mhinz** [comment]
How is the plugin getting loaded and how do you start Vim? 

[This function](https://github.com/mhinz/vim-startify/blob/master/plugin/startify.vim#L36) is getting called when Vim starts.

Maybe the condition in the next line is false for some reason? Maybe another plugin is writing to the first buffer before startify? You could add `echomsg !argc() (line2byte('$') == -1)` to the start of that function and it should show `1 1` when starting Vim.

**Comment by Miziak** [comment]
Thanks `!argc()` help me solve issue. My alias generator do something like:
```
cd path/to/project
nvim .
```

So condition you shoe me fail on startup.
Thank You so much! ;)

**Comment by nerdneilsfield** [comment]
I add the `echomsg !argc() (line2byte('$') == -1)` to the line, and it shows `1 1` when I start vim. But the plugin didn't start too.

**Comment by mhinz** [comment]
@nerdneilsfield 

It's most probably another plugin interfering, but it's impossible to say without more info. Maybe check `:verb au VimEnter`.

Or just good old print debugging. Put `echomsg "FOO"` at the start of https://github.com/mhinz/vim-startify/blob/20898979ea81d3ff9f0c288102ffffdfb9f0cb96/autoload/startify.vim#L42 and move it further down below until you don't see the "FOO" message on starting Vim anymore. (Make sure to check `:messages` in case another message overwrote ours.)

**Comment by nerdneilsfield** [comment]
@mhinz 
Unfortunately, the printing msg didn't show when the vim start after add the `echomsg` command to the function.

The output of `:verb au VimEnter` is as follows:

```
:verb au VimEnter
--- Autocommands ---
dirvish_ftdetect  VimEnter
    *         if exists('#FileExplorer') | exe 'au! FileExplorer *' | endif
        Last set from ~/.vim/bundles/vim-dirvish/plugin/dirvish.vim line 17
              if exists('#NERDTreeHijackNetrw') | exe 'au! NERDTreeHijackNetrw *' | endif
        Last set from ~/.vim/bundles/vim-dirvish/plugin/dirvish.vim line 18
sig_autocmds  VimEnter
    *         call signature#utils#SetupHighlightGroups()
        Last set from ~/.vim/bundles/vim-signature/plugin/signature.vim line 56
gutentags_detect  VimEnter
    *         if expand('<amatch>')==''|call gutentags#setup_gutentags()|endif
        Last set from ~/.vim/bundles/vim-gutentags/plugin/gutentags.vim line 99
airline  VimEnter
    *         call <sid>on_window_changed('VimEnter')
        Last set from ~/.vim/bundles/vim-airline/plugin/airline.vim line 135
lsp_auto_enable  VimEnter
    *         call lsp#enable()
        Last set from ~/.vim/bundles/vim-lsp/plugin/lsp.vim line 49
unimpaired  VimEnter
    *         call s:maps()
        Last set from ~/.vim_light/plugin/unimpaired.vim line 526
```
It seems that `Startify` didn't register for `on_vimenter` event.

**Comment by mhinz** [comment]
> It seems that Startify didn't register for on_vimenter event.

Nope, the autocmd just removes itself after it was executed.

Please put the `:echomsg` in this function then: https://github.com/mhinz/vim-startify/blob/20898979ea81d3ff9f0c288102ffffdfb9f0cb96/plugin/startify.vim#L36 It's the very first function that gets called on `VimEnter`.

You have quite a lot of things that run on `VimEnter`, though. It probably also helps to disable your other plugins one after the other until you find the culprit.
