### ISSUE TITLE
Error when trying to open files with batchmode

### ISSUE THREAD

**Issue by EtiamNullam** [mhinz/vim-startify#398]
## Steps:

1. Run `Vim8` or `Nvim` on `Windows 10 x64`.
2. Press `B0`.
3. Get error.

```
Error detected while processing function startify#open_buffers:
line    4:
E117: Unknown function: <SNR>78_set_mark
```

**Comment by mhinz** [comment]
Oops.. in a recent refactoring this function was fogotten to be renamed.

Should be working now!

**Comment by EtiamNullam** [comment]
It works, thanks!
