### ISSUE TITLE
Can't figure out why characters don't show up

### ISSUE THREAD

**Issue by imajes** [mhinz/vim-startify#403]
Hey- noticing that these glyphs are not rendering correctly:

<img width="106" alt="Screen Shot 2019-12-18 at 12 24 59" src="https://user-images.githubusercontent.com/2073/71112654-9317b380-2191-11ea-84cd-aed163005b67.png">

did a big review of the faq/config but i can't see anything obvious to clarify this up :( 

sorry!

**Comment by mhinz** [comment]
These don't come from this plugin. :)

It's most probably vim-devicons hooking into vim-startify. Make sure to install the proper font as described [here](https://github.com/ryanoasis/vim-devicons#installation).

**Comment by imajes** [comment]
ah. thanks @mhinz! sorry for the 🤦‍♂
