### ISSUE TITLE
idea: include git-relevant lists

### ISSUE THREAD

**Issue by residualmind** [mhinz/vim-startify#405]
I really love Startify, thanks for the awesome plugin.

In my workflow I am usually interested which files in the current git repo are dirty - modified or untracked.

So I've come up with this - maybe you want to think about it. It could perhaps be another example in the help.

Also: It would be interesting to know what custom configurations other people are using with your plugin. Are you considering a crowd-sourced "startify cookbook" section in the wiki here? Where people could share their ideas and setups?

Anyways... keep up the great work!

```
" returns all modified files of the current git repo
" `2>/dev/null` makes the command fail quietly, so that when we are not
" in a git repo, the list will be empty
function! s:gitModified()
    let files = systemlist('git ls-files -m 2>/dev/null')
    return map(files, "{'line': v:val, 'path': v:val}")
endfunction

" same as above, but show untracked files, honouring .gitignore
function! s:gitUntracked()
    let files = systemlist('git ls-files -o --exclude-standard 2>/dev/null')
    return map(files, "{'line': v:val, 'path': v:val}")
endfunction

let g:startify_lists = [
        \ { 'type': 'files',     'header': ['   MRU']            },
        \ { 'type': 'dir',       'header': ['   MRU '. getcwd()] },
        \ { 'type': 'sessions',  'header': ['   Sessions']       },
        \ { 'type': 'bookmarks', 'header': ['   Bookmarks']      },
        \ { 'type': function('s:gitModified'),  'header': ['   git modified']},
        \ { 'type': function('s:gitUntracked'), 'header': ['   git untracked']},
        \ { 'type': 'commands',  'header': ['   Commands']       },
        \ ]
```

**Comment by mhinz** [comment]
I put it on the wiki and mention it in the README now: https://github.com/mhinz/vim-startify/commit/593388d3dbe7bfdcc06a714550d3253442b2fc65

Thanks!
