### ISSUE TITLE
Declaration of variables

### ISSUE THREAD

**Issue by 7wmr** [mhinz/vim-startify#409]
I have noticed that if these variables are not declared before the plugin is loaded then they will not work (use the default values):

```
g:startify_change_to_dir
g:startify_files_number
g:startify_update_oldfiles
g:startify_fortune_use_unicode
g:startify_files_number
g:startify_skiplist
```

The line below indicates that the variable value is evaluated when the plugin is loaded resulting in the default value being used.

https://github.com/mhinz/vim-startify/blob/05122f08c6a553992f7b0a9ad88016a89f51548a/autoload/startify.vim#L1110

Please ignore me if this is intentional and I have missed something from the documentation stating so.

**Comment by toberge** [comment]
Was mystified by the same issue.

**Comment by mhinz** [comment]
I removed the internal variables now and use the global options right away. There was never a technical reason to do otherwise anyway.

Thanks!

**Comment by 7wmr** [comment]
Thanks!
