### ISSUE TITLE
Filter files for specific list

### ISSUE THREAD

**Issue by Shatur95** [mhinz/vim-startify#411]
Hello! Thank you for your plugin.
Is there a way to filter files for specific list? For example, add a list that contains only `CMakeLists.txt` files. I see that there is a `command` type for list but how can I access to the recent opened files in my custom function?

**Comment by mhinz** [comment]
Hey, sorry for the late response, but I wasn't active on GitHub in recent months.

In general, this plugin works by going through `:echo v:oldfiles`. By default, `v:oldfiles` is only seeded once by viminfo (Vim) or shada (Nvim) _at startup_. If you want to `v:oldfiles` to be up-to-date in longer sessions, you can use `:h g:startify_update_oldfiles`.

If you want a custom list that only shows `CMakeLists.txt` files, try this:

```vim
function! s:list_cmake_files() abort
  let files = filter(copy(v:oldfiles), 'v:val =~# "CMakeLists\.txt$"')
  return map(files, '{"line": fnamemodify(v:val, ":."), "path": v:val}')
endfunction

let g:startify_lists = [
      \ { 'header': ['   MRU'],            'type': 'files' },
      \ { 'header': ['   MRU '. getcwd()], 'type': 'dir' },
      \ { 'header': ['   Sessions'],       'type': 'sessions' },
      \ { 'header': ['   Cmake'],          'type': function('s:list_cmake_files') },
      \ ]
```

See `:h g:startify_lists` for more on custom functions.

**Comment by Shatur95** [comment]
Thank you a lot!
