### ISSUE TITLE
Startify dont work with ctrlspace

### ISSUE THREAD

**Issue by Wabri** [mhinz/vim-startify#416]
I post the same issue on the ctrlspace plugin [issue#264](https://github.com/vim-ctrlspace/vim-ctrlspace/issues/264), but I dont know where is the problem so I ask even here if I can do something to solve this. Thanks in advice.

**Describe the bug**
Before I start using [vim-ctrlspace](https://github.com/vim-ctrlspace/vim-ctrlspace) I tend to use the sessions handling with [vim-startify](https://github.com/mhinz/vim-startify), I need to load a session even with the same buffers and Startify works really good for this purpose. Now I need something better to move from buffer to another and vim-ctrlspace is a real good tool to do this, the problem is that when I load a session only the last buffer will open and not all others that I saved. The ctrlspace session dont replace the buffers, but simple dont load the other buffer in that session.

**To Reproduce**
1. enable the [vim-startify](https://github.com/mhinz/vim-startify) plugin
2. disable the ctrlspace plugin
3. open more than one buffer and save the session using the :SSave
4. close vim and try to open the session with :SLoad, the session should start correctly
5. enable the ctrlspace plugin and retry to open the same session

**Expected behavior**
I expected the same buffers opened in the same session, but when I use ctrlspace only the last one is open.

**Screenshots**
 To be more clear I attach some screenshot:

- Session load without ctrlspace enable

![2020-04-14-15-47-17_1920x1053](https://user-images.githubusercontent.com/12409541/79232039-4ace8080-7e67-11ea-8221-f9a337fa9fb2.png)

- Same session load with ctrlspace enable

![2020-04-14-15-48-49_1920x1053](https://user-images.githubusercontent.com/12409541/79232157-72254d80-7e67-11ea-8586-24dd24fe1e25.png)

Is possible to notice that the buffers are different.

**Version(s) (please complete the following information):**
 - OS:  Debian GNU/Linux 10 (buster)
 - Version: VIM - Vi IMproved 8.1 (2018 May 18, compiled Jun 15 2019 16:41:15)

**Additional context**
I have those settings on the vimrc for ctrlspace:

```
let g:CtrlSpaceLoadLastWorkspaceOnStart = 0
let g:CtrlSpaceSaveWorkspaceOnSwitch = 0
let g:CtrlSpaceSaveWorkspaceOnExit = 0
```

**Comment by you-n-g** [comment]
I have the exactly the same issue

**Comment by mhinz** [comment]
Your steps to reproduce actually proved that startify is working as expected. The plugin really just acts as a thin wrapper around `:mksession` by default. The only difference is that it saves all sessions always in the same directory (for listing purposes) opposed to the current working directory.

Session files are just a collection of Vim commands, so you can just have a look at them. See `:h g:startify_session_dir` for where the plugin saves session by default. When the session contains 3 buffers, then the session file will contain 3 lines that start with `badd <path>`. You can also just `:source path/to/sessionfile`.

If ctrlspace doesn't source that session file properly, ctrlspace is to blame. See https://github.com/vim-ctrlspace/vim-ctrlspace/issues/264#issuecomment-626301142 for a potential fix.
