### ISSUE TITLE
Startify opens another buffer?

### ISSUE THREAD

**Issue by Augists** [mhinz/vim-startify#419]
Hi~

I can't find the same issue.

* REPRODUCE

1. `vim` (didn't open any files, just vim)

2. `q`

3. It shows me the file (as a buffer) I have closed last time

* BESIDES

After `vim` and I check `:buffers` and there will be 2!

But if I comment `Plug '.../vim-startify` then `vim`, no buffer is opened

* SYSTEM

macOS 10.15.4

vim 8.1

---

thanks

**Comment by HassanZahin** [comment]
> After `vim` and I check `:buffers` and there will be 2!
> 
> But if I comment `Plug '.../vim-startify` then `vim`, no buffer is opened
> 
> * SYSTEM
> 
> macOS 10.15.4
> 
> vim 8.1
> 
> thanks

Can't fully understand what you are talking about. But I think your issue is similar to mine. When I vim, startify doesn't show up in `:ls`. But when I open a file from startify, it's in buffer number 2.

**Comment by mhinz** [comment]
If you just do `vim`, followed by `q`, it should quit right away. If not, I suspect another plugin is interferring somehow.

Can you please paste the output of `:ls!` just after starting Vim and then again after hitting `q`?

**Comment by mhinz** [comment]
@HassanZahin 

The startify buffer is an unlisted buffer, so you need to use `:ls!` to see it. Buffer numbers do not get reused, so if Startify is the first buffer, then any file opened from will have a buffer number larger than 1.

In practice that shouldn't lead to any problems, though.

**Comment by HassanZahin** [comment]
@mhinz Oh, I see. That feels awkward, though.
