### ISSUE TITLE
Prevent Startify to change working directory

### ISSUE THREAD

**Issue by kuntau** [mhinz/vim-startify#421]
Hi. Is there any way I can prevent Startify to change the current working directory when opening files from MRU list.

Example. 
1. I always start empty vim from the project root, let's say `~/projects/repo`
2. `CWD` now is `~/projects/repo`
3. I opened some file from MRU list, let's say `~/projects/repo/src/modules/file.ts`
4. `CWD` now is `~/projects/repo/src/modules/`
5. This isn't good since I want to use some fuzzy file finder, now it will only look in `~/projects/repo/src/modules` folder instead of the project root folder.

Thank you.

**Comment by GuillaumeDeconinck** [comment]
Hi @kuntau ,

I have just installed Startify and had the same issue as you 5 minutes ago.
The solution in https://github.com/mhinz/vim-startify/issues/387 fixes the issue on my side, I believe it should solve your issue as well

**Comment by kuntau** [comment]
Thank you @GuillaumeDeconinck
