### ISSUE TITLE
Proper way to auto-open startify when closing all buffers

### ISSUE THREAD

**Issue by jeyj0** [mhinz/vim-startify#424]
I'd like to automatically open startify after closing all buffers. I haven't been able to figure out how to do that without issues. It'd be great if we could figure out a way to do it, and then document it somewhere for people to find. (unless of course it already is documented somewhere, and I just haven't found it)

(I think @AndraSol, you've managed to do it?)

**Comment by Icy-Thought** [comment]
Add the following code to your .vimrc/init.vim (vim/neovim):
```vim
autocmd BufDelete * if empty(filter(tabpagebuflist(), '!buflisted(v:val)')) | Startify | endif
```
- [mhinz](https://github.com/mhinz/vim-startify/issues/331#issuecomment-413898037)

**Comment by jeyj0** [comment]
Actually this doesn't do what I wanted - I hadn't tried out everything, but now I did some work and noticed it doesn't work :sweat_smile: 
With your snippet Startify opens when I close a buffer in a window. However, other buffers might still be open. I am using the BClose plugin to close buffers, maybe that's what's creating this issue?

**Comment by mhinz** [comment]
Hi, I wasn't active on GitHub in recent months, hence the late reply. :)

Since this is no issue with the plugin itself, but rather a general Vim question, I'm closing this. But that doesn't mean we can't figure your issue out in here anyway.

You want Startify to run when all _loaded_ buffers are closed. But when you closed all buffers with `:bd`, you'll end up with the empty scratch buffer that is _listed_ and _loaded_.

`tabpagebuflist()` returns all buffers that are _loaded_. So, let's run Startify only if we enter an empty scratch buffer _and_ there's only one loaded buffer left (this empty scratch buffer):

```vim
autocmd BufEnter * if line2byte('.') == -1 && len(tabpagebuflist()) == 1 | Startify | endif
```

**Comment by jeyj0** [comment]
Thank you! That does exactly what I want it to do!

It doesn't open startify when I have multiple windows open and close the last buffer (causing all windows to open the empty scratch buffer); however, I don't know what behavior I would expect here (close all but one window and open startify? open startify in every window?), so until I actually know what I want here I won't go into implementation.

Thanks a lot!

**Comment by liangkarl** [comment]
> Hi, I wasn't active on GitHub in recent months, hence the late reply. :)
> 
> Since this is no issue with the plugin itself, but rather a general Vim question, I'm closing this. But that doesn't mean we can't figure your issue out in here anyway.
> 
> You want Startify to run when all _loaded_ buffers are closed. But when you closed all buffers with `:bd`, you'll end up with the empty scratch buffer that is _listed_ and _loaded_.
> 
> `tabpagebuflist()` returns all buffers that are _loaded_. So, let's run Startify only if we enter an empty scratch buffer _and_ there's only one loaded buffer left (this empty scratch buffer):
> 
> ```viml
> autocmd BufEnter * if line2byte('.') == -1 && len(tabpagebuflist()) == 1 | Startify | endif
> ```

I have another version. Modify like this that can prevent failed to open file with ":edit newfile" at the beginning : )
```viml
autocmd BufEnter * if bufname() == "" && len(tabpagebuflist()) == 1 | Startify | endif 
```

**Comment by gennaro-tedesco** [comment]
> ```viml
> autocmd BufEnter * if line2byte('.') == -1 && len(tabpagebuflist()) == 1 | Startify | endif
> ```

this would however prevent to even open any empty buffer, since it would then default back to `Startify` immediately, or am I wrong?

**Comment by ChrisTsou** [comment]
i would love a way to do this, i've searched a bit but i dont have enough knowledge to figure it out. 
when all buffers get closed -> open startify. but not when opening an empty file.

**Comment by hetranger** [comment]
> i would love a way to do this, i've searched a bit but i dont have enough knowledge to figure it out.
> when all buffers get closed -> open startify. but not when opening an empty file.

Hi, maybe you can consider adding a condition to determine whether the file name is empty before open startify? Just like this:
`autocmd BufEnter * if line2byte('.') == -1 && len(tabpagebuflist()) == 1 && empty(bufname()) | Startify | endif
`
It works fine for me.

**Comment by saurabhchardereal** [comment]
> Hi, maybe you can consider adding a condition to determine whether the file name is empty before open startify? Just like this:
> `autocmd BufEnter * if line2byte('.') == -1 && len(tabpagebuflist()) == 1 && empty(bufname()) | Startify | endif `
> It works fine for me.
This worked really well but then I noticed it somehow breaks netrw. Upon opening `:Explore` I can't navigate properly to directories.
