### ISSUE TITLE
Add the ability to use `:cd` instead of `:lcd`

### ISSUE THREAD

**Issue by Shatur95** [mhinz/vim-startify#425]
Currently Startify use `:lcd` to open files with `let g:startify_change_to_dir = 1` or `let g:startify_change_to_vcs_root = 1`. I suggest to add the ability to let user specify `:cd`, `:lcd` or `:tcd` command to change directory. This ca be useful because `:lcd` cannot be overwritten with `:cd` from other buffer (from drawer, for example).

**Comment by Shatur95** [comment]
Thank you!

**Comment by mhinz** [comment]
Hah, you're welcome!
