### ISSUE TITLE
Add global header indent

### ISSUE THREAD

**Issue by Rizhiy** [mhinz/vim-startify#432]
Currently, each header needs to be indented individually.
It would be better if by default they were indented to the same degree as selection options.

**Comment by mhinz** [comment]
That might not be desirable for people using graphics, centered text, or just don't want their header to be vertically aligned with the rest.

If we would indent by default, people would not be able to add anything that starts in the first column. And then people would create issues on how to work around that.

For convenience `:h g:startify_custom_header` also shows the use of `startify#pad()`, which indents a list of lines as you would expect.

The current way works for everyone and adding 2 spaces in front shouldn't be a showstopper. :-)

**Comment by Rizhiy** [comment]
I mean you can make it a setting and set it to 0 by default.
Using `#pad` does not work, as I would need to still include it in each entry.
