### ISSUE TITLE
StartifyAllBuffersOpened not working

### ISSUE THREAD

**Issue by Rizhiy** [mhinz/vim-startify#433]
I want to open coc-explorer after buffers are opened, but for some reason StartifyAllBuffersOpened is not working:
```vim
autocmd User StartifyAllBuffersOpened CocCommand explorer
```

Normal buffers works:
```vim
autocmd User StartifyBufferOpened CocCommand explorer
```
but obviously it opens multiple explorers when I open more than one buffer, which is undesirable.

**Comment by mhinz** [comment]
What does "not working" mean? Nothing happening?

Is a simple `autocmd User StartifyAllBuffersOpened echomsg 'foo'` working when opening multiple buffers at the same time? (`:messages` should show "foo" only once.)

**Comment by Rizhiy** [comment]
Yes, nothing happens. I tried your command, messages are empty.

**Comment by Rizhiy** [comment]
Vim version, just in case:
```
NVIM v0.4.3
Build type: RelWithDebInfo
LuaJIT 2.0.5
Compilation: /usr/bin/gcc-5 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -DMIN_LOG_LEVEL=3 -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/home/travis/build/neovim/bot-ci/build/neovim/build/config -I/home/travis/build/neovim/bot-ci/build/neovim/src -I/home/travis/build/neovim/bot-ci/build/neovim/.deps/usr/include -I/usr/include -I/home/travis/build/neovim/bot-ci/build/neovim/build/src/nvim/auto -I/home/travis/build/neovim/bot-ci/build/neovim/build/include
Compiled by travis@travis-job-9a287301-34f2-4b86-92e3-462594f51f36

Features: +acl +iconv +tui
```

**Comment by mhinz** [comment]
Is the autocmd triggered when you do `doautocmd <nomodeline> User StartifyAllBuffersOpened` manually?

If so, just to be sure, how do you open multiple files exactly? I quickly tested it like this:

```
:Startify
b
j
b
<cr>
```

This should open 2 files, but trigger `StartifyAllBuffersOpened` only once.

If not, please double check if your local copy of the plugin is really up-to-date and contains:

```vim
  if exists('#User#StartifyAllBuffersOpened')
    doautocmd <nomodeline> User StartifyAllBuffersOpened
  endif
```

..at the end of `startify#open_buffers()` in `autoload/startify.vim`.

**Comment by Rizhiy** [comment]
Using batching it works.
I tested it by opening a session.

**Comment by mhinz** [comment]
Well, that user event is only fired on batching. Try `autocmd SessionLoadPost * CocCommand explorer` instead.

If that's working, I'll change the doc to make it clearer.

**Comment by Rizhiy** [comment]
It works, thanks.
It would be nice if there was a single event that fires when startify is done.
