### ISSUE TITLE
possible to exclude directory from MRU?

### ISSUE THREAD

**Issue by prankousky** [mhinz/vim-startify#434]
Hi,

I have been using `Startify` for quite some time now, and it is awesome. However, I just added `firenvim` to my \$MYVIMRC, which allows me to use neovim in the browser.

![grafik](https://user-images.githubusercontent.com/11297070/89121950-ae86c300-d4c3-11ea-99fd-88d700231dd5.png)

When I start `Startify` now, I get `/run/user/<id>/firenvim/github.com_somethingsomething_txt` for **each and every** browser entry I made. Can exclude this path somehow so that it will no longer spam my entire `Startify` page?

Thank you and keep up the great work :)

**Comment by mhinz** [comment]
See `:h g:startify_skiplist`.

In your case probably something like `let g:startify_skiplist = ['^\V/run/user/<id>/firenvim']`.
