### ISSUE TITLE
only within Startify - Devicons do not work

### ISSUE THREAD

**Issue by thomas-repo** [mhinz/vim-startify#435]
Hi, 
I have maybe a quite stupid question, but I need to clear that one out in my mind.
I am using **ryanoasis** vim-devicons and so far they do work flawless without any configuration in all my other plugins (NerdTree, airline) but I can't get them to be shown in startify neither within MRU files as well as Bookmarks...

I already tried to add at the end of my .vimrc config the following to lines
```
let g:webdevicons_enable = 1
let g:webdevicons_enable_startify = 1
```

neither of those to options change anything in my apperence of vim.

Thanks for your help
Thomas

//: on the left picture you can see what I'd like to have (pic borrowed from chrisatmachine) and on the right it's a picture of my config
![2020-08-19_13-34](https://user-images.githubusercontent.com/39732028/90632477-c2048e80-e224-11ea-937d-cc3210fca85d.png)![2020-08-19_13-36](https://user-images.githubusercontent.com/39732028/90632480-c335bb80-e224-11ea-968e-7577634fad25.png)

**Comment by thomas-repo** [comment]
AHA got a half solution:
now I got it working for MRU by adding 
```
function! StartifyEntryFormat()
        return 'WebDevIconsGetFileTypeSymbol(absolute_path) ." ". entry_path'
    endfunction
```

**Comment by mhinz** [comment]
BTW, it should now work for bookmarks as well.
