### ISSUE TITLE
Tips from another plugin not displayed in custom header until vimrc is sourced manually

### ISSUE THREAD

**Issue by R0LA1mRifcF8yAkk** [mhinz/vim-startify#439]
Hello, I'm trying to display tips instead of quotes in the header. Alas, it only starts showing the tips after I've sourced my `.vimrc` and manually triggered Startify again.

If I remove the conditional from the function, I get the error `E117: Unknown function: GetTip`.

**Note:** it only diplays only one tip per vim session as well, maybe due to some optimization not to run the same code twice?

More info can be found here: https://github.com/michaelb/vim-tips/issues/3

```vim
" Custom startify header
function! s:tips_wrapper()
    redir => var
      if exists('*GetTip')
        runtime $HOME/.vim/bundle/vim-tips/plugin/vim-tips.vim
        let tip = GetTip()
        silent! echo tip
      endif
    redir END
    return map(split(var, '\n'), '"   " . v:val') + ['']
endfunction

let g:startify_custom_header = s:tips_wrapper()
```

**Comment by mhinz** [comment]
See `:h g:startify_custom_header_quotes` instead.

Afterwards `startify#fortune#quote()` will give you a random tip, so you can change the header to `let g:startify_custom_header = 'startify#fortune#quote()'`, if you only want the tip, without the cowsay around it.

**Comment by mhinz** [comment]
Ah, just re-read this. If vim-tips only provides `GetTip()` to get one one-line tip at a time, you can also use this:

```vim
let g:startify_custom_header = '["   " . GetTip()]'
```

See the bottom of `:h g:startify_custom_header`. If its value is a string, its content is evaluated every time `:Startify` is run.

**Comment by R0LA1mRifcF8yAkk** [comment]
Holy crap, that works! Thank you! I guess I have some studying to do, not many things about vimscript are clear to me yet.

**Comment by mhinz** [comment]
Hah, you're welcome. If you have VimL questions, just ask here in this issue.
