### ISSUE TITLE
Cannot change Startify colors when `termguicolors` is set

### ISSUE THREAD

**Issue by AkashKarnatak** [mhinz/vim-startify#456]
NVim version: v0.5.0
OS: Debian 10(Buster)

```
highlight StartifyHeader ctermfg=Blue
```
does not set header's color to blue when `set termguicolors` is also included in `init.vim`.

![Screenshot from 2021-01-21 17-15-18](https://user-images.githubusercontent.com/54985621/105347010-4e6c1080-5c0c-11eb-86a1-a8cd53e3b62c.png)

When I disable `termguicolors` then I get the expected result

![Screenshot from 2021-01-21 17-15-04](https://user-images.githubusercontent.com/54985621/105347004-4b712000-5c0c-11eb-8c92-fd3a99da4d41.png)

But I cannot compromise with `termguicolors` as it is required for `coc-highlight`.

**Comment by AkashKarnatak** [comment]
Guess when you set `ctermfg` color you need to also specify `guifg` color otherwise it just won't work. So 
```
highlight StartifyHeader ctermfg=10 guifg=#73d900
```
This will work

**Comment by zachliu** [comment]
in my case, all the `cterm*` have no effect

```
highlight StartifyHeader guifg=LightGreen
```

works fine

![2024-07-23_14-10](https://github.com/user-attachments/assets/060407aa-a983-47ce-97df-320dd0afb06c)
