### ISSUE TITLE
Startify command opens Startify in all empty buffers

### ISSUE THREAD

**Issue by reportaman** [mhinz/vim-startify#459]
If I open vim, and lets say I select-and-open an empty buffer from startify options (which closes the startify buffer). Then let's say I do vertical and horizontal splits & execute command `:Startify` again from one of the window. It opens startify in all the empty windows. This seems more like a Vim behavior, though I don't know (am new). Is there a way to get around this? I would like Startify to open only in the currently focused window. Thanks!

**Comment by tristenps** [comment]
I believe you're getting confused because creating a new split in vim will open that same buffer within two splits.  That means any file, or Startify, will look like it's being repeated unless another buffer already exists.  Hope I explained it correctly!

**Comment by mhinz** [comment]
Yup, that's just Vim's behaviour. When you only have one unnamed buffer in one window and split that window 2 times, then you end up with 3 windows all showing the same unnamed buffer.

When Startify is run in that _empty_ buffer, it will reuse that buffer automatically. Reason: https://github.com/mhinz/vim-startify/commit/6f621bd99a72781cf538d1cf28b07826ed17db26

So, if you really want the behaviour that you describe, you can use: `:enew | Startify`. 

Hope that helps!
