### ISSUE TITLE
Suggestion for NERDTree integration.

### ISSUE THREAD

**Issue by browser-bug** [mhinz/vim-startify#461]
I've been using startify for some days now and I love it. Since I'm a NERDTree user too I've been struggling with session management alongside it. In the docs there's a suggestion on how to workaround in case of session autosaving like on `startify_session_before_save`:
```
let g:startify_session_before_save = [
        \ 'echo "Cleaning up before saving.."',
        \ 'silent! NERDTreeTabsClose'
        \ ]
```
Since `NERDTreeTabsClose` seems to be a dead project and outdated I would suggest to change it to ([reference](https://github.com/preservim/nerdtree/issues/1222#issuecomment-777656010)):
```
let g:startify_session_before_save = [
        \ 'silent! :tabdo NERDTreeClose',
        \ 'silent! :bufdo NERDTreeClose'
        \ ]
```
Not sure if the second one is needed or not because the same instance of NERDTree should persist on multiple buffers but can't hurt.

**Comment by mhinz** [comment]
I think `:tabdo` should be good enough in that case.

Thanks for letting me know! ✨
