### ISSUE TITLE
Startify being displayed on vim start even when files are specified

### ISSUE THREAD

**Issue by kauer3** [mhinz/vim-startify#466]
I may be wrong, but from what I understand from the documentation, startify should be displayed only when starting vim without giving any filenames. In my case, even when I do provide a file (`vim filename`) it is displayed. And if I got it wrong and this is the expected behavior, is there a way to change it?

**Comment by mhinz** [comment]
No, that should not happen.

- Is `vim` a wrapper script by any chance?
- What does your Vim setup look like? Plugin manager? Any Startify options in your vimrc?

In Vim, `:echo argc()` tells how many arguments were given to Vim and that's what the plugin checks. So, can you confirm the following two examples?

- `vim -u NORC -N +'autocmd VimEnter * echomsg argc()'` echoes 0
- `vim -u NORC -N +'autocmd VimEnter * echomsg argc()' foo` echoes 1

**Comment by kauer3** [comment]
So, I was checking the startify options in my vimrc
