### ISSUE TITLE
Using the "mark" keys yank the underlying selection-letter into the unnamed ("quotequote") register

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [mhinz/vim-startify#467]
In my vim (with `'clipboard'` set to `"unnamedplus"`), every batchmode key I hit in a Startify buffer writes to the unnamed — and thus, system — register.

For instance, if I have the entry `[a] .gitignore`, position my cursor over the `a`, and hit `b` (for "open in same window"), then `a` gets written to the unnamed register. Further, if I then hit `b` again (to un-mark "open in same window"), then *`b`* gets written to the unnamed register.

This quickly leads to my system clipboard being overwhelmed with single characters:

![image](https://user-images.githubusercontent.com/200/110525782-9e2e6a80-80da-11eb-83c7-f8477305fae0.png)

**Comment by mhinz** [comment]
Should be fixed now. Thanks! ✨
