### ISSUE TITLE
Show devicons using nvim-web-devicons not vim-devicons

### ISSUE THREAD

**Issue by lalitmee** [mhinz/vim-startify#471]
How can I show devicons using [nvim-web-devicons](https://github.com/kyazdani42/nvim-web-devicons)? I am trying to use plugins which are written in lua so I am trying to loose [vim-devicons](https://github.com/ryanoasis/vim-devicons).

I am trying to use something like this. I don't know how to write `viml` or `lua`.

```vim
function! StartifyEntryFormat()
  return luaeval(
          \ "require('nvim-web-devicons').get_icon(vim.fn.fnamemodify(' " .. absolute_path .. "', ':e')) or ' '"
          \ ) . " " . entry_path
endfunction
```

Am I doing something wrong?

**Comment by Mathijs-Bakker** [comment]
Try this:
```lua
lua << EOF
function _G.webDevIcons(path)
  local filename = vim.fn.fnamemodify(path, ':t')
  local extension = vim.fn.fnamemodify(path, ':e')
  return require'nvim-web-devicons'.get_icon(filename, extension, { default = true })
end
EOF

function! StartifyEntryFormat() abort
  return 'v:lua.webDevIcons(absolute_path) . " " . entry_path'
endfunction
```

**Comment by lalitmee** [comment]
@Mathijs-Bakker , thanks for your solution. I got the same answer from a recent Reddit post. I solved it.

Thank you so much. :+1:
