### ISSUE TITLE
For the love of god, respect the users `autochdir` setting

### ISSUE THREAD

**Issue by mrjones2014** [mhinz/vim-startify#472]
I just spent hours debugging why, after setting `noautochdir`, it was still `autochdir`ing when selecting a file from startify. For the love of god, please make `g:startify_change_to_dir` default to the users `autochdir` setting, or better yet, just remove the Startify setting altogether and leave it to `autochdir` to handle it!

**Comment by mhinz** [comment]
> I just spent hours debugging why, after setting noautochdir, it was still autochdiring when selecting a file from startify.

It took you hours to realize that a behaviour you observed after using a plugin could actually be related to that plugin?

The plugin acted liked that from the beginning and `g:startify_change_to_dir` was only introduced afterwards, defaulting to `1` to not change behaviour.

And yes, it would have been a saner default, but it is like that for 8 years now. I understand that this would help your use case, but I have to think of the other already-existing users as well. Changing such a core behaviour now would lead to a lot of users wondering why it's suddenly acting differently. I prefer stability in this case.

And removing the option is no good either. I for myself want startify to change the directory (which can also be fine-tuned via `let g:startify_change_cmd` opposed to `'autochdir'`), but not to change for every single buffer opened afterwards, so using `'autochdir'` is not an option.

I think the documentation is in pretty good shape already, but I'll add a remark about `'autochdir'`.

For the love of God.
