### ISSUE TITLE
Configuration in LUA

### ISSUE THREAD

**Issue by jrock2004** [mhinz/vim-startify#478]
I am switching over to use LUA with neovim and having a hard time setting up. What I have below kinda works, just that the header is still `MRU` instead of `Files`. Thoughts?

```
vim.g.startify_list = { {
  type = 'dir',
  header = { 'Files', vim.fn.getcwd()}
}, }
```

**Comment by dhruvmanila** [comment]
You need to concatenate the 'Files' and 'cwd'. If you want, you can take a look at my startify config file (lua): https://github.com/dhruvmanila/dotfiles/blob/master/config/nvim/lua/plugin/startify.lua

**Comment by krzkrzkrz** [comment]
@dhruvmanila Could you paste your config instead. The link you posted doesnt exist anymore

**Comment by dhruvmanila** [comment]
@krzkrzkrz https://github.com/dhruvmanila/dotfiles/blob/bc282895f4aa686eed4cf02fb4da0ede1bd13408/config/nvim/lua/plugin/startify.lua

Although I've switched to a custom implementation which was inspired by [dashboard-nvim](https://github.com/glepnir/dashboard-nvim).
