### ISSUE TITLE
multiple buffers rings terminal bell

### ISSUE THREAD

**Issue by ds2606** [mhinz/vim-startify#479]
labeling any file on the startify screen with `t`, `s`, `v`, etc, rings the terminal bell. Any of these character inputs triggers a bell ring, which has gotten a little annoying after a few hundred times. 

The command line message is `Batchmode off`

**Comment by mhinz** [comment]
I can reproduce that. It just happens for the first entry of each list, right?

**Comment by mhinz** [comment]
It beeps because of `'showmatch'` although we set the `matchpairs=` for the Startify buffer already.

I reported this to Vim: https://github.com/vim/vim/issues/8053

Until it get fixed and for people using older versions, I'll just disable `'showmatch'` while toggling batchmode.
