### ISSUE TITLE
How to open NerdTree when a file is selected from Startify?

### ISSUE THREAD

**Issue by UmbralReaper** [mhinz/vim-startify#483]
How can I open NerdTree when a file is selected from the Startify menu, but not anywhere else. For example, 
```vim
autocmd BufEnter * NERDTreeCWD
```
won't work because it will open on every new buffer.

**Comment by mhinz** [comment]
Try putting this in your vimrc:

```vim
autocmd User StartifyBufferOpened NERDTreeCWD
```

**Comment by UmbralReaper** [comment]
Thanks!
