### ISSUE TITLE
My cow's box isn't nice

### ISSUE THREAD

**Issue by Amparose** [mhinz/vim-startify#488]
Where would I look to fix my terminal font / settings / etc when my cow's speech bubble looks like this:

<img width="442" alt="image" src="https://user-images.githubusercontent.com/949192/115288334-9dfda200-a151-11eb-8ec8-723431d70540.png">

**Comment by mhinz** [comment]
Unicode is disabled by default, us this:

```vim
let g:startify_fortune_use_unicode = 1
```
