### ISSUE TITLE
Vim-startify uncompatible with vim-polyglot.

### ISSUE THREAD

**Issue by hungpham3112** [mhinz/vim-startify#520]
> Messages maintainer: Bram Moolenaar <Bram@vim.org>
> "~\C_Project\effective_c\pointer.c" 32 lines, 739 bytes
> Error detected while processing function startify#open_buffers[13]..<SNR>116_open_buffer[12]..BufRead Autocommands for "*.c":
> E117: Unknown function: polyglot#ft#FTlpc
> 

It happened when I open `main.c` file.

**Comment by AniAggarwal** [comment]
Try just updating your vim-polyglot. I had similar error yesterday and updating fixed it.

**Comment by hungpham3112** [comment]
> Try just updating your vim-polyglot. I had similar error yesterday and updating fixed it.

It worked. Thanks.
