### ISSUE TITLE
Startify leaving an empty buffer and split after closing built-in terminal

### ISSUE THREAD

**Issue by tanner-d** [mhinz/vim-startify#537]
**Steps to recreate**
1. Startify screen
2. :term
3. exit the shell

**Screenshots**
![image](https://user-images.githubusercontent.com/88670305/183596988-ceef6e1d-ff6b-49d5-bb04-c91a0228108d.png)

Happens in vanilla vim as well
![image](https://user-images.githubusercontent.com/88670305/183597317-9d37e8dc-2290-41e7-93e2-c16817616ecd.png)

**Comment by legendaryzyper** [comment]
I ended up *kinda-fixing* it with a custom event and closing the empty buffer:
```
let s:terminal_opened = 0
function! s:trigger()
    if empty(filter(range(1, bufnr('$')), 'buflisted(v:val) && "terminal" ==? getbufvar(v:val, "&buftype")'))
        if s:terminal_opened == 1
            let s:terminal_opened = 0
            if exists('#User#TerminalClose')
                execute 'doautocmd User TerminalClose'
            endif
        endif
    endif
endfunction
augroup startify_fix
    autocmd!
    autocmd TerminalOpen * let s:terminal_opened = 1
    autocmd BufEnter * call s:trigger()
    autocmd User TerminalClose if line2byte('.') == -1 && winnr('$') > 1 && empty(bufname()) | execute winnr('#') ' wincmd w' | execute 'Bdelete! nameless' | endif
augroup END
```

I only tested it slightly so let me know if you have the same issue and found bugs in the solution above.

**Comment by tanner-d** [comment]
Right so I found out that this was covered in the FAQs but with vim-plug.
