### ISSUE TITLE
Latest neovim changes line2byte() and thus startify no longer launches

### ISSUE THREAD

**Issue by mckellygit** [mhinz/vim-startify#549]
Hi,
Thank you for awesome vim-startify.
Latest neovim has a change which makes startify no longer launch.
Should we change to something like this ?
```
  "if !argc() && line2byte('$') == -1
  if !argc() && line('$') == 1 && getline('.') =~ '^\s*$'
```
See https://github.com/neovim/neovim/commit/b051b131f5ce99ffe1b1bc22a2032ebc886e4e35#commitcomment-126028751
thx,
-m

**Comment by mhinz** [comment]
Thanks for pointing it out! I wasn't exactly active on GitHub recently, but try to do better in the near future. ;]
