### ISSUE TITLE
Splash screen doesn't show

### ISSUE THREAD

**Issue by phildobbin** [mhinz/vim-startify#7]
When starting Vim with no filenames the Startify splash screen doesn't appear. It works inside the buffer via ':Startify'

I've added the recommended mappings via my vimrc.

This on Ubuntu 12.04 & Vim 7.3.429 & I installed via Vundle...

**Comment by atomictom** [comment]
I know this is an old issue, but I came across this just recently, and for me the problem was that I was calling my vim executable "vim2". It seems that if the name of the executable (whether it be a symlink or actual file) affects the checks @mhinz mentioned.

In short:
```bash
$ vim2 # -> No startify
$ ./vim2 # -> No startify
$ vim # -> startify
$ ./some/path/vim # -> startify
```

**Comment by mhinz** [comment]
The plugin checks whether `v:progname` matches a certain regex: https://github.com/mhinz/vim-startify/blob/master/plugin/startify.vim#L27

Maybe this check should be removed. The original reason was to prevent showing the Startify buffer when Vim was called through vimdiff etc.

**Comment by mhinz** [comment]
@atomictom A word and a blow: https://github.com/mhinz/vim-startify/commit/9afab110e95b84c0170bcb81bb733c39b98b2065
