### ISSUE TITLE
warn if viminfo file can't be read

### ISSUE THREAD

**Issue by clutchski** [mhinz/vim-startify#89]
I had a weird situation where my viminfo was owned by root and my user didn't have permissions to read it. this meant that the "recently used files" section of vim-startify was empty. I eventually tracked down the issue, but it might nice to print a warning if viminfo can't be read for whatever reason. This is probably a rare situation, but noted here for posterity.

**Comment by expipiplus1** [comment]
Is it possible to avoid this when starting vim for the first time?
