### ISSUE TITLE
NERDTree split is empty when loading from session

### ISSUE THREAD

**Issue by baopham** [mhinz/vim-startify#91]
Hi,

Is it possible to save NERDTree buffer by calling `:NERDTree` on the split instead of just saving an empty one? Every time I load a session that has NERDTree open, the NERDTree split is always empty.

**Comment by flavius** [comment]
@mhinz Wouldn't it be possible to do it like the competition does it here https://github.com/xolox/vim-session/blob/9e9a6088f0554f6940c19889d0b2a8f39d13f2bb/autoload/xolox/session.vim#L300 ?

**Comment by gerazov** [comment]
This needs a fix :+1:
