### ISSUE TITLE
Ignore session files from MRU

### ISSUE THREAD

**Issue by stellarhoof** [mhinz/vim-startify#98]
Is is possible to ignore files which I have saved in a session when listing the MRU files?

**Comment by JunfengJia** [comment]
This can be very useful, otherwise mru is full of session files.

How about an option don't update mru when it's in an session?

**Comment by mhinz** [comment]
Do you mean the actual session files from `g:startify_session_dir` are shown in the files list? Because that shouldn't happen.

**Comment by JunfengJia** [comment]
What I mean is the files belong to a session is shown in mru.

If I want to open a file belong a session, I can open the session and locate the file quickly.
The facts is my mru is flushed after I worked in a session, because I have to open several files in a session. 

An option like g:vim-startify-don't-update-mru-in-session is good, but I don't known if vim have such mechanism to do it.

**Comment by mhinz** [comment]
Okay, please try this:

  - `git pull && git checkout ignore_session_files` in the startify repo
  - put `let g:startify_session_ignore_files = 1` in your vimrc

Now, if you're in a session, you shouldn't be able to see any files from the session file in the `files` and `dir` list.

**Comment by JunfengJia** [comment]
Seems still not working.

My session 'c':
/home/junfeng/c/1.c
                           2.c
                           3.c

after open 1 2 3.c, files still show 1 2 3.c
But if I add startify_skiplist /home/junfeng/c/*,
1 2 3.c will NOT shown.

And ~/.vim/session/c contains:
cd ~/c "I guess you get the session folder path here?

Did you expand the '~'?

**Comment by mhinz** [comment]
Hmm, actually it works with absolute paths internally.

Try this:

  - open a session
  - `:execute 'edit' v:this_session`
    - look for lines looking like `badd +42 pretty/path`
    - the latter part is parsed, expanded and should be ignored after another `:Startify`

**Comment by JunfengJia** [comment]
badd +686 1.c

So you will expanded it into /home/junfeng/c/1.c? seems not working in my system.

And what I expect is files under /home/junfeng/c/ are all ignored. Maybe it's not a good feature to implement?

skiplist can solve my problem, just a bit tedious, but theory is clear.

**Comment by mhinz** [comment]
Ignoring files that aren't even in the session itself, makes the MRU feature kind of useless. :-) I think in this case you should indeed go the skiplist route since it's a rather individual issue.
